pe.ConfirmationDialog=function(a,c){pe.init_widget(this,null);this.success_callback=c;this.container=$(this.html(a));this.container.appendTo("body");this.container.dialog({title:"Please confirm action",modal:!0,resizable:!1,width:300,buttons:{Yes:this.callback(this.confirm_clicked),Cancel:function(){$(this).remove()}}})};pe.ConfirmationDialog.prototype.html=function(a){return"<div>"+a+"</div>"};pe.ConfirmationDialog.prototype.confirm_clicked=function(){this.success_callback();this.container.remove()};
jQuery&&function(a){a.extend(a.fn,{uploadify:function(c){a(this).each(function(){settings=a.extend({id:a(this).attr("id"),uploader:"uploadify.swf",script:"uploadify.php",expressInstall:null,folder:"",height:30,width:110,cancelImg:"cancel.png",wmode:"opaque",scriptAccess:"sameDomain",fileDataName:"Filedata",method:"POST",queueSizeLimit:999,simUploadLimit:1,queueID:!1,displayData:"percentage",onInit:function(){},onSelect:function(){},onQueueFull:function(){},onCheck:function(){},onCancel:function(){},
onError:function(){},onProgress:function(){},onComplete:function(){},onAllComplete:function(){}},c);var d=location.pathname,d=d.split("/");d.pop();var d=d.join("/")+"/",b={};b.uploadifyID=settings.id;b.pagepath=d;settings.buttonImg&&(b.buttonImg=escape(settings.buttonImg));settings.buttonText&&(b.buttonText=escape(settings.buttonText));settings.rollover&&(b.rollover=!0);b.script=settings.script;b.folder=escape(settings.folder);if(settings.scriptData){var f="",n;for(n in settings.scriptData)f+="&"+
n+"="+settings.scriptData[n];b.scriptData=escape(f.substr(1))}b.width=settings.width;b.height=settings.height;b.wmode=settings.wmode;b.method=settings.method;b.queueSizeLimit=settings.queueSizeLimit;b.simUploadLimit=settings.simUploadLimit;settings.hideButton&&(b.hideButton=!0);settings.fileDesc&&(b.fileDesc=settings.fileDesc);settings.fileExt&&(b.fileExt=settings.fileExt);settings.multi&&(b.multi=!0);settings.auto&&(b.auto=!0);settings.sizeLimit&&(b.sizeLimit=settings.sizeLimit);settings.checkScript&&
(b.checkScript=settings.checkScript);settings.fileDataName&&(b.fileDataName=settings.fileDataName);settings.queueID&&(b.queueID=settings.queueID);!1!==settings.onInit()&&(a(this).css("display","none"),a(this).after('<div id="'+a(this).attr("id")+'Uploader"></div>'),swfobject.embedSWF(settings.uploader,settings.id+"Uploader",settings.width,settings.height,"9.0.24",settings.expressInstall,b,{quality:"high",wmode:settings.wmode,allowScriptAccess:settings.scriptAccess}),!1==settings.queueID&&a("#"+a(this).attr("id")+
"Uploader").after('<div id="'+a(this).attr("id")+'Queue" class="uploadifyQueue"></div>'));"function"==typeof settings.onOpen&&a(this).bind("uploadifyOpen",settings.onOpen);a(this).bind("uploadifySelect",{action:settings.onSelect,queueID:settings.queueID},function(j,b,c){if(j.data.action(j,b,c)!==false){var g=Math.round(c.size/1024*100)*0.01,d="KB";if(g>1E3){g=Math.round(g*0.1)*0.01;d="MB"}g=g.toString().split(".");g=g.length>1?g[0]+"."+g[1].substr(0,2):g[0];fileName=c.name.length>20?c.name.substr(0,
20)+"...":c.name;queue="#"+a(this).attr("id")+"Queue";j.data.queueID&&(queue="#"+j.data.queueID);a(queue).append('<div id="'+a(this).attr("id")+b+'" class="uploadifyQueueItem"><div class="cancel"><a href="javascript:jQuery(\'#'+a(this).attr("id")+"').uploadifyCancel('"+b+'\')"><img src="'+settings.cancelImg+'" border="0" /></a></div><span class="fileName">'+fileName+" ("+g+d+')</span><span class="percentage"></span><div class="uploadifyProgress"><div id="'+a(this).attr("id")+b+'ProgressBar" class="uploadifyProgressBar"><\!--Progress Bar--\></div></div></div>')}});
"function"==typeof settings.onSelectOnce&&a(this).bind("uploadifySelectOnce",settings.onSelectOnce);a(this).bind("uploadifyQueueFull",{action:settings.onQueueFull},function(a,b){a.data.action(a,b)!==false&&alert("The queue is full.  The max size is "+b+".")});a(this).bind("uploadifyCheckExist",{action:settings.onCheck},function(b,c,w,g,z){var o={},o=w;o.folder=d+g;if(z)for(var f in w)var n=f;a.post(c,o,function(d){for(var f in d)b.data.action(b,c,w,g,z)!==false&&(confirm("Do you want to replace the file "+
d[f]+"?")||document.getElementById(a(b.target).attr("id")+"Uploader").cancelFileUpload(f,true,true));z?document.getElementById(a(b.target).attr("id")+"Uploader").startFileUpload(n,true):document.getElementById(a(b.target).attr("id")+"Uploader").startFileUpload(null,true)},"json")});a(this).bind("uploadifyCancel",{action:settings.onCancel},function(b,c,d,g,f){b.data.action(b,c,d,g,f)!==false&&a("#"+a(this).attr("id")+c).fadeOut(f==true?0:250,function(){a(this).remove()})});"function"==typeof settings.onClearQueue&&
a(this).bind("uploadifyClearQueue",settings.onClearQueue);var u=[];a(this).bind("uploadifyError",{action:settings.onError},function(b,c,d,g){if(b.data.action(b,c,d,g)!==false){u.push([c,d,g]);a("#"+a(this).attr("id")+c+" .percentage").text(" - "+g.type+" Error");a("#"+a(this).attr("id")+c).addClass("uploadifyError")}});a(this).bind("uploadifyProgress",{action:settings.onProgress,toDisplay:settings.displayData},function(b,c,d,g){if(b.data.action(b,c,d,g)!==false){a("#"+a(this).attr("id")+c+"ProgressBar").css("width",
g.percentage+"%");b.data.toDisplay=="percentage"&&(displayData=" - "+g.percentage+"%");b.data.toDisplay=="speed"&&(displayData=" - "+g.speed+"KB/s");b.data.toDisplay==null&&(displayData=" ");a("#"+a(this).attr("id")+c+" .percentage").text(displayData)}});a(this).bind("uploadifyComplete",{action:settings.onComplete},function(b,c,d,g,f){if(b.data.action(b,c,d,unescape(g),f)!==false){a("#"+a(this).attr("id")+c+" .percentage").text(" - Completed");a("#"+a(this).attr("id")+c).fadeOut(250,function(){a(this).remove()})}});
"function"==typeof settings.onAllComplete&&a(this).bind("uploadifyAllComplete",{action:settings.onAllComplete},function(a,b){a.data.action(a,b)!==false&&(u=[])})})},uploadifySettings:function(c,d,b){var f=!1;a(this).each(function(){if("scriptData"==c&&null!=d){var n=b?d:a.extend(settings.scriptData,d),g="",j;for(j in n)g+="&"+j+"="+escape(n[j]);d=g.substr(1)}f=document.getElementById(a(this).attr("id")+"Uploader").updateSettings(c,d)});if(null==d){if("scriptData"==c){for(var n=unescape(f).split("&"),
u={},j=0;j<n.length;j++){var C=n[j].split("=");u[C[0]]=C[1]}f=u}return f}},uploadifyUpload:function(c){a(this).each(function(){document.getElementById(a(this).attr("id")+"Uploader").startFileUpload(c,!1)})},uploadifyCancel:function(c){a(this).each(function(){document.getElementById(a(this).attr("id")+"Uploader").cancelFileUpload(c,!0,!1)})},uploadifyClearQueue:function(){a(this).each(function(){document.getElementById(a(this).attr("id")+"Uploader").clearFileUploadQueue(!1)})}})}(jQuery);
var swfobject=function(){function a(){if(!y){try{var h=i.getElementsByTagName("body")[0].appendChild(i.createElement("span"));h.parentNode.removeChild(h)}catch(a){return}y=!0;for(var h=E.length,k=0;k<h;k++)E[k]()}}function c(h){y?h():E[E.length]=h}function d(h){if(typeof p.addEventListener!=l)p.addEventListener("load",h,!1);else if(typeof i.addEventListener!=l)i.addEventListener("load",h,!1);else if(typeof p.attachEvent!=l)R(p,"onload",h);else if("function"==typeof p.onload){var a=p.onload;p.onload=
function(){a();h()}}else p.onload=h}function b(){var h=i.getElementsByTagName("body")[0],a=i.createElement(v);a.setAttribute("type",F);var k=h.appendChild(a);if(k){var b=0;(function(){if(typeof k.GetVariable!=l){var c=k.GetVariable("$version");c&&(c=c.split(" ")[1].split(","),e.pv=[parseInt(c[0],10),parseInt(c[1],10),parseInt(c[2],10)])}else if(10>b){b++;setTimeout(arguments.callee,10);return}h.removeChild(a);k=null;f()})()}else f()}function f(){var h=s.length;if(0<h)for(var a=0;a<h;a++){var k=s[a].id,
b=s[a].callbackFn,c={success:!1,id:k};if(0<e.pv[0]){var d=o(k);if(d)if(D(s[a].swfVersion)&&!(e.wk&&312>e.wk))x(k,!0),b&&(c.success=!0,c.ref=n(k),b(c));else if(s[a].expressInstall&&u()){c={};c.data=s[a].expressInstall;c.width=d.getAttribute("width")||"0";c.height=d.getAttribute("height")||"0";d.getAttribute("class")&&(c.styleclass=d.getAttribute("class"));d.getAttribute("align")&&(c.align=d.getAttribute("align"));for(var i={},d=d.getElementsByTagName("param"),g=d.length,f=0;f<g;f++)"movie"!=d[f].getAttribute("name").toLowerCase()&&
(i[d[f].getAttribute("name")]=d[f].getAttribute("value"));j(c,i,k,b)}else C(d),b&&b(c)}else if(x(k,!0),b){if((k=n(k))&&typeof k.SetVariable!=l)c.success=!0,c.ref=k;b(c)}}}function n(h){var a=null;if((h=o(h))&&"OBJECT"==h.nodeName)typeof h.SetVariable!=l?a=h:(h=h.getElementsByTagName(v)[0])&&(a=h);return a}function u(){return!G&&D("6.0.65")&&(e.win||e.mac)&&!(e.wk&&312>e.wk)}function j(h,a,k,c){G=!0;J=c||null;M={success:!1,id:k};var b=o(k);if(b){"OBJECT"==b.nodeName?(B=w(b),H=null):(B=b,H=k);h.id=
N;if(typeof h.width==l||!/%$/.test(h.width)&&310>parseInt(h.width,10))h.width="310";if(typeof h.height==l||!/%$/.test(h.height)&&137>parseInt(h.height,10))h.height="137";i.title=i.title.slice(0,47)+" - Flash Player Installation";c=e.ie&&e.win?"ActiveX":"PlugIn";c="MMredirectURL="+p.location.toString().replace(/&/g,"%26")+"&MMplayerType="+c+"&MMdoctitle="+i.title;a.flashvars=typeof a.flashvars!=l?a.flashvars+("&"+c):c;e.ie&&e.win&&4!=b.readyState&&(c=i.createElement("div"),k+="SWFObjectNew",c.setAttribute("id",
k),b.parentNode.insertBefore(c,b),b.style.display="none",function(){b.readyState==4?b.parentNode.removeChild(b):setTimeout(arguments.callee,10)}());g(h,a,k)}}function C(h){if(e.ie&&e.win&&4!=h.readyState){var a=i.createElement("div");h.parentNode.insertBefore(a,h);a.parentNode.replaceChild(w(h),a);h.style.display="none";(function(){4==h.readyState?h.parentNode.removeChild(h):setTimeout(arguments.callee,10)})()}else h.parentNode.replaceChild(w(h),h)}function w(a){var b=i.createElement("div");if(e.win&&
e.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName(v)[0])if(a=a.childNodes)for(var c=a.length,d=0;d<c;d++)!(1==a[d].nodeType&&"PARAM"==a[d].nodeName)&&8!=a[d].nodeType&&b.appendChild(a[d].cloneNode(!0));return b}function g(a,b,c){var d,g=o(c);if(e.wk&&312>e.wk)return d;if(g)if(typeof a.id==l&&(a.id=c),e.ie&&e.win){var f="",m;for(m in a)a[m]!=Object.prototype[m]&&("data"==m.toLowerCase()?b.movie=a[m]:"styleclass"==m.toLowerCase()?f+=' class="'+a[m]+'"':"classid"!=m.toLowerCase()&&(f+=" "+
m+'="'+a[m]+'"'));m="";for(var q in b)b[q]!=Object.prototype[q]&&(m+='<param name="'+q+'" value="'+b[q]+'" />');g.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+f+">"+m+"</object>";I[I.length]=a.id;d=o(a.id)}else{q=i.createElement(v);q.setAttribute("type",F);for(var j in a)a[j]!=Object.prototype[j]&&("styleclass"==j.toLowerCase()?q.setAttribute("class",a[j]):"classid"!=j.toLowerCase()&&q.setAttribute(j,a[j]));for(f in b)b[f]!=Object.prototype[f]&&"movie"!=f.toLowerCase()&&
(a=q,m=f,j=b[f],c=i.createElement("param"),c.setAttribute("name",m),c.setAttribute("value",j),a.appendChild(c));g.parentNode.replaceChild(q,g);d=q}return d}function z(a){var b=o(a);b&&"OBJECT"==b.nodeName&&(e.ie&&e.win?(b.style.display="none",function(){if(4==b.readyState){var c=o(a);if(c){for(var d in c)"function"==typeof c[d]&&(c[d]=null);c.parentNode.removeChild(c)}}else setTimeout(arguments.callee,10)}()):b.parentNode.removeChild(b))}function o(a){var b=null;try{b=i.getElementById(a)}catch(c){}return b}
function R(a,b,c){a.attachEvent(b,c);A[A.length]=[a,b,c]}function D(a){var b=e.pv,a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&b[1]==a[1]&&b[2]>=a[2]?!0:!1}function L(a,b,c,d){if(!e.ie||!e.mac){var g=i.getElementsByTagName("head")[0];if(g){c=c&&"string"==typeof c?c:"screen";d&&(K=r=null);if(!r||K!=c)d=i.createElement("style"),d.setAttribute("type","text/css"),d.setAttribute("media",c),r=g.appendChild(d),
e.ie&&e.win&&typeof i.styleSheets!=l&&0<i.styleSheets.length&&(r=i.styleSheets[i.styleSheets.length-1]),K=c;e.ie&&e.win?r&&typeof r.addRule==v&&r.addRule(a,b):r&&typeof i.createTextNode!=l&&r.appendChild(i.createTextNode(a+" {"+b+"}"))}}}function x(a,b){if(O){var c=b?"visible":"hidden";y&&o(a)?o(a).style.visibility=c:L("#"+a,"visibility:"+c)}}function P(a){return null!=/[\\\"<>\.;]/.exec(a)&&typeof encodeURIComponent!=l?encodeURIComponent(a):a}var l="undefined",v="object",F="application/x-shockwave-flash",
N="SWFObjectExprInst",p=window,i=document,t=navigator,Q=!1,E=[function(){Q?b():f()}],s=[],I=[],A=[],B,H,J,M,y=!1,G=!1,r,K,O=!0,e=function(){var a=typeof i.getElementById!=l&&typeof i.getElementsByTagName!=l&&typeof i.createElement!=l,b=t.userAgent.toLowerCase(),c=t.platform.toLowerCase(),d=c?/win/.test(c):/win/.test(b),c=c?/mac/.test(c):/mac/.test(b),b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,e=!+"\v1",g=[0,0,0],f=null;if(typeof t.plugins!=l&&typeof t.plugins["Shockwave Flash"]==
v){if((f=t.plugins["Shockwave Flash"].description)&&!(typeof t.mimeTypes!=l&&t.mimeTypes[F]&&!t.mimeTypes[F].enabledPlugin))Q=!0,e=!1,f=f.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),g[0]=parseInt(f.replace(/^(.*)\..*$/,"$1"),10),g[1]=parseInt(f.replace(/^.*\.(.*)\s.*$/,"$1"),10),g[2]=/[a-zA-Z]/.test(f)?parseInt(f.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if(typeof p.ActiveXObject!=l)try{var j=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(j&&(f=j.GetVariable("$version")))e=!0,f=f.split(" ")[1].split(","),
g=[parseInt(f[0],10),parseInt(f[1],10),parseInt(f[2],10)]}catch(n){}return{w3:a,pv:g,wk:b,ie:e,win:d,mac:c}}();(function(){e.w3&&((typeof i.readyState!=l&&"complete"==i.readyState||typeof i.readyState==l&&(i.getElementsByTagName("body")[0]||i.body))&&a(),y||(typeof i.addEventListener!=l&&i.addEventListener("DOMContentLoaded",a,!1),e.ie&&e.win&&(i.attachEvent("onreadystatechange",function(){"complete"==i.readyState&&(i.detachEvent("onreadystatechange",arguments.callee),a())}),p==top&&function(){if(!y){try{i.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,
0);return}a()}}()),e.wk&&function(){y||(/loaded|complete/.test(i.readyState)?a():setTimeout(arguments.callee,0))}(),d(a)))})();(function(){e.ie&&e.win&&window.attachEvent("onunload",function(){for(var a=A.length,b=0;b<a;b++)A[b][0].detachEvent(A[b][1],A[b][2]);a=I.length;for(b=0;b<a;b++)z(I[b]);for(var c in e)e[c]=null;e=null;for(var d in swfobject)swfobject[d]=null;swfobject=null})})();return{registerObject:function(a,b,c,d){if(e.w3&&a&&b){var f={};f.id=a;f.swfVersion=b;f.expressInstall=c;f.callbackFn=
d;s[s.length]=f;x(a,!1)}else d&&d({success:!1,id:a})},getObjectById:function(a){if(e.w3)return n(a)},embedSWF:function(a,b,d,f,i,n,m,q,o,p){var r={success:!1,id:b};e.w3&&!(e.wk&&312>e.wk)&&a&&b&&d&&f&&i?(x(b,!1),c(function(){d+="";f+="";var c={};if(o&&typeof o===v)for(var e in o)c[e]=o[e];c.data=a;c.width=d;c.height=f;e={};if(q&&typeof q===v)for(var s in q)e[s]=q[s];if(m&&typeof m===v)for(var t in m)e.flashvars=typeof e.flashvars!=l?e.flashvars+("&"+t+"="+m[t]):t+"="+m[t];if(D(i))s=g(c,e,b),c.id==
b&&x(b,!0),r.success=!0,r.ref=s;else{if(n&&u()){c.data=n;j(c,e,b,p);return}x(b,!0)}p&&p(r)})):p&&p(r)},switchOffAutoHideShow:function(){O=!1},ua:e,getFlashPlayerVersion:function(){return{major:e.pv[0],minor:e.pv[1],release:e.pv[2]}},hasFlashPlayerVersion:D,createSWF:function(a,b,c){if(e.w3)return g(a,b,c)},showExpressInstall:function(a,b,c,d){e.w3&&u()&&j(a,b,c,d)},removeSWF:function(a){e.w3&&z(a)},createCSS:function(a,b,c,d){e.w3&&L(a,b,c,d)},addDomLoadEvent:c,addLoadEvent:d,getQueryParamValue:function(a){var b=
i.location.search||i.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(null==a)return P(b);for(var b=b.split("&"),c=0;c<b.length;c++)if(b[c].substring(0,b[c].indexOf("="))==a)return P(b[c].substring(b[c].indexOf("=")+1))}return""},expressInstallCallback:function(){if(G){var a=o(N);a&&B&&(a.parentNode.replaceChild(B,a),H&&(x(H,!0),e.ie&&e.win&&(B.style.display="block")),J&&J(M));G=!1}}}}();
$(document).ready(function(){pe.browse_button_height=30;pe.next_step_button=$(".next_step_btn");pe.next_step_url=pe.next_step_button.attr("href").toString();var a=window.uploadify_options;a.onAllComplete=pe.all_uploads_completed;a.onClearQueue=pe.update_upload_button;a.onComplete=pe.upload_completed;a.onError=pe.error_happened;a.onOpen=pe.uploadify_opened;a.onProgress=pe.show_upload_progress;a.onSelect=pe.file_selected;a.onQueueFull=pe.upload_queue_size_exceeded;pe.file_input=$("#FileInput");pe.file_input.uploadify(a);
pe.update_next_step_button();pe.upload_button=$(".UploadButton");pe.update_upload_button();$(".Delete").live("click",function(){pe.delete_photo_button_clicked(this)});pe.init_page_framework()});$(window).load(function(){0===$(".PhotoCell.Empty").length&&($("#FileInput object").load(function(){$(this).uploadifySettings("height",0)}),$("#FileInputUploader").addClass("disabled"))});
pe.all_uploads_completed=function(){pe.file_input.uploadifySettings("queueSizeLimit",window.queueSizeLimit-$(".Photo").length);pe.update_next_step_button();pe.update_upload_button()};pe.cell_html=function(){return'<div class="PhotoCell Empty photo_item"><span class="CellNumber photo_number"></span></div>'};
pe.delete_photo_button_clicked=function(a){new pe.ConfirmationDialog("Are you sure you want to delete this photo?",function(){$.ajax({url:$(a).attr("data-delete-url"),type:"post",dataType:"script",data:{_method:"delete"},complete:function(){pe.delete_photo_success(a)}})})};
pe.delete_photo_success=function(a){$(".Photo:last").after(pe.cell_html());$(a).closest(".Photo").remove();pe.enumerate_cells();pe.file_input.uploadifySettings("queueSizeLimit",window.queueSizeLimit-$(".Photo").length);pe.update_browse_button();pe.update_next_step_button();pe.update_upload_button()};pe.enumerate_cells=function(){var a=$(".PhotoCell .CellNumber"),c=12-a.length;a.each(function(a){$(this).html(c+a+1)})};
pe.error_happened=function(a,c,d,b){if("File Size"===b.type)return alert('File size should be < 5 MB. File named "'+d.name+'" removed from the queue.'),pe.upload_cancelled(c),!1};pe.file_selected=function(a,c,d){var a=$(".PhotoCell.Empty:first"),b=pe.format_file_size(d.size),d=pe.photo_html(d.name,b);a.removeClass("Empty").addClass(c+" Processing");a.append(d);a.find(".CancelUpload").click(pe.bind(pe.upload_cancelled,c));pe.update_browse_button();pe.update_upload_button()};
pe.format_file_size=function(a){return 1048576<a?(a/1048576).toFixed(2)+" MB":(a/1024).toFixed(2)+" KB"};pe.photo_html=function(a,c){return'<span class="file_name">'+a+'</span><span class="file_size">('+c+')</span><div class="progress"><div class="Completed progress_bar"></div></div><div class="CancelUpload delete_icon"></div><div class="ui-overlay" style="display: none;"><div class="loading_notice">Please wait.</div><div class="ui-widget-overlay"></div></div><div class="RollingImage loading_image" style="display: none;"></div>'};
pe.show_upload_progress=function(a,c,d,b){a=$("."+c);a.find(".ui-overlay:hidden").show();a.find(".RollingImage:visible").hide();a.find(".Completed").width(b.percentage)};pe.update_browse_button=function(){0===$(".PhotoCell.Empty").length?(pe.file_input.uploadifySettings("height",0),$("#FileInputUploader").addClass("disabled")):(pe.file_input.uploadifySettings("height",pe.browse_button_height),$("#FileInputUploader").removeClass("disabled"))};
pe.update_next_step_button=function(){0===$(".Photo").length?(pe.next_step_button.removeAttr("href"),pe.next_step_button.addClass("disabled")):(pe.next_step_button.attr("href",pe.next_step_url),pe.next_step_button.removeClass("disabled"))};pe.update_upload_button=function(){pe.upload_button.unbind("click");0===$(".Processing").length?pe.upload_button.addClass("disabled"):(pe.upload_button.click(function(){pe.file_input.uploadifyUpload()}),pe.upload_button.removeClass("disabled"))};
pe.upload_cancelled=function(a){var c=$("."+a);pe.file_input.uploadifyCancel(a);$(".UploadedPhotos").append(pe.cell_html());c.remove();pe.enumerate_cells();pe.update_browse_button();pe.update_upload_button()};pe.upload_completed=function(a,c,d,b){a=$("."+c);a.after(b);a.next().addClass(c);a.remove();pe.update_upload_button()};pe.upload_queue_size_exceeded=function(a,c){alert("You can upload only "+c+" images");return!1};pe.uploadify_opened=function(){$(".RollingImage").show()};
