(function(a){a.cookie=function(c,b,d){if(1<arguments.length&&(!/Object/.test(Object.prototype.toString.call(b))||null===b||void 0===b)){d=a.extend({},d);if(null===b||void 0===b)d.expires=-1;if("number"===typeof d.expires){var g=d.expires,f=d.expires=new Date;f.setDate(f.getDate()+g)}b=String(b);return document.cookie=[encodeURIComponent(c),"=",d.raw?b:encodeURIComponent(b),d.expires?"; expires="+d.expires.toUTCString():"",d.path?"; path="+d.path:"",d.domain?"; domain="+d.domain:"",d.secure?"; secure":
""].join("")}d=b||{};for(var g=d.raw?function(a){return a}:decodeURIComponent,f=document.cookie.split("; "),e=0,h;h=f[e]&&f[e].split("=");e++)if(g(h[0])===c)return g(h[1]||"");return null}})(jQuery);
pe.CloseButton=function(a,c){pe.init_widget(this,a);this.close_button=a.find(".CloseButton");if("function"===typeof c)this.close_button.click(c);else switch(c){case pe.CloseButton.close_methods.REMOVE:this.close_button.click(this.callback(this.remove_container));break;case pe.CloseButton.close_methods.HIDE:this.close_button.click(this.callback(this.hide_container));break;default:alert("unknown value for 'close_method' parameter.")}};pe.CloseButton.close_methods={REMOVE:"REMOVE",HIDE:"HIDE"};
pe.CloseButton.events={CLOSED:"CloseButton_CLOSED"};pe.CloseButton.prototype.remove_container=function(){this.container.detach();this.fire_event(pe.CloseButton.events.CLOSED);this.container.remove();return!1};pe.CloseButton.prototype.hide_container=function(){this.fire_event(pe.CloseButton.events.CLOSED);this.container.hide();return!1};
pe.SingleSelectionAutocompleteField=function(a,c,b,d){pe.init_widget(this,a);this.close_button_callback=this.on_item_selected=null;this.autocomplete_data_or_url=c;this.input_field_name=b;this.container.html(this.html());this.dummy_input_field=this.container.find(".DummyInputField");this.messaging_area=this.container.find(".Messaging");this.autocomplete_input_field=this.container.find(".AutocompleteField");this.autocomplete_handler();this.selected_data_container=this.container.find(".SelectedValue");
d&&this.set_field_value(d)};pe.SingleSelectionAutocompleteField.events={SELECTED:"SingleSelectionAutocompleteField_SELECTED"};pe.SingleSelectionAutocompleteField.prototype.set_autocomplete_url=function(a){a&&(this.autocomplete_data_or_url=a,this.autocomplete_handler())};pe.SingleSelectionAutocompleteField.prototype.set_field_value=function(a){a&&0!==a.length&&(this.remove_dummy_row(),this.autocomplete_data_selected(a),this.enforce_limit())};
pe.SingleSelectionAutocompleteField.prototype.add_dummy_row=function(){this.dummy_input_field||(this.dummy_input_field=$('<input class="DummyInputField"        type="hidden" name="'+this.input_field_name+'"       value="x_mock_single_value_x">'),this.autocomplete_input_field.after(this.dummy_input_field))};
pe.SingleSelectionAutocompleteField.prototype.autocomplete_data_selected=function(a){this.selected_data=a;this.remove_dummy_row();this.selected_data_container.append(this.selected_data_html(a.label,a.id,a.category));(new pe.CloseButton(this.selected_data_container.find(".SelectedInputData").last(),pe.CloseButton.close_methods.REMOVE)).bind_event(pe.CloseButton.events.CLOSED,this.callback(this.close_button_clicked));this.enforce_limit();if(this.on_item_selected)this.on_item_selected(a)};
pe.SingleSelectionAutocompleteField.prototype.item_selected=function(a){this.on_item_selected=a};
pe.SingleSelectionAutocompleteField.prototype.autocomplete_handler=function(){this.autocomplete_input_field.autocomplete({source:this.autocomplete_data_or_url,minLength:1,focus:function(){return!1},close:this.callback(function(){this.autocomplete_input_field.val("")}),select:this.callback(function(a,c){var b=c.item;this.autocomplete_data_selected(b);this.fire_event(pe.SingleSelectionAutocompleteField.events.SELECTED,b.id)})}).data("autocomplete")._renderItem=function(a,c){c.display_label=c.category?
pe.templatize("{{label}} ({{category}})",c):c.label;return $("<li></li>").data("item.autocomplete",c).append(pe.templatize("<a>{{display_label}}</a>",c)).appendTo(a)}};pe.SingleSelectionAutocompleteField.prototype.clear_selected_data=function(){this.selected_data_container.html("");this.add_dummy_row()};
pe.SingleSelectionAutocompleteField.prototype.close_button_clicked=function(){0===this.selected_data_container.find(".SelectedInputData").length&&this.add_dummy_row();this.enforce_limit();this.close_button_callback&&this.close_button_callback();this.autocomplete_input_field.show();this.autocomplete_input_field.focus()};pe.SingleSelectionAutocompleteField.prototype.display_close_button=function(){this.selected_data_container.find(".CloseButton").show()};
pe.SingleSelectionAutocompleteField.prototype.enforce_limit=function(){0<this.selected_data_container.find(".SelectedInputData").length?this.autocomplete_input_field.autocomplete("disable"):this.autocomplete_input_field.autocomplete("enable")};pe.SingleSelectionAutocompleteField.prototype.hide_close_button=function(){this.selected_data_container.find(".CloseButton").hide()};
pe.SingleSelectionAutocompleteField.prototype.html=function(){return'<input class="AutocompleteField" type="text"><input class="DummyInputField" type="hidden" name="'+this.input_field_name+'" value="x_mock_single_value_x"><div class="SelectedValue"></div>'};pe.SingleSelectionAutocompleteField.prototype.remove_dummy_row=function(){this.dummy_input_field&&(this.dummy_input_field.remove(),this.dummy_input_field=null)};
pe.SingleSelectionAutocompleteField.prototype.replace_data_in_list=function(a){this.clear_selected_data();this.set_field_value(a)};pe.SingleSelectionAutocompleteField.prototype.selected_data_html=function(a,c,b){return'<div class="SelectedInputData selected_data"><img style="margin-right:20px; width: 15px; height: 15px;" src="/assets/events/close.png"class="CloseButton float_left">  <div>'+(b?a+"("+b+")":a)+'</div>  <input type="hidden" value="'+c+'" name="'+this.input_field_name+'"></div>'};
pe.SingleSelectionAutocompleteField.prototype.val=function(){return this.dummy_input_field?"":this.container.find('input[name="'+this.input_field_name+'"]').val()};
(function(){var a=function(a,b){return function(){return a.apply(b,arguments)}},c=pe,b=function(d,b,c){var e=this;this.container=d;this.url=b;this.field_name=c;this.on_write_review_button_clicked=a(this.on_write_review_button_clicked,this);this.on_item_selected=a(this.on_item_selected,this);this.item=null;this.autocomplete=new pe.SingleSelectionAutocompleteField(this.container.find(".Autocomplete"),this.url,this.field_name);this.write_review_button=this.container.find(".WriteReviewButton");this.write_review_button.click(this.on_write_review_button_clicked);
this.write_review_button.click(function(){return e.item?!0:!1});this.autocomplete.item_selected(this.on_item_selected);this.autocomplete.close_button_callback=function(){e.item=null;return e.write_review_button.addClass("disabled")}};b.prototype.on_item_selected=function(a){this.write_review_button.toggleClass("disabled",a);if(this.item=a)return this.write_review_button.attr("href",""+a.value+"#WriteComment")};b.prototype.on_write_review_button_clicked=function(){var a;a=JSON.stringify({notice:this.write_review_button.data("message")});
$.cookie("flash",a,{path:"/"});return!0};c.PerformerJumper=b}).call(this);
