(function(b){b.fn.editable=function(c,e){if("disable"==c)b(this).data("disabled.editable",!0);else if("enable"==c)b(this).data("disabled.editable",!1);else if("destroy"==c)b(this).unbind(b(this).data("event.editable")).removeData("disabled.editable").removeData("event.editable");else{var a=b.extend({},b.fn.editable.defaults,{target:c},e),h=b.editable.types[a.type].plugin||function(){},j=b.editable.types[a.type].submit||function(){},r=b.editable.types[a.type].buttons||b.editable.types.defaults.buttons,
p=b.editable.types[a.type].content||b.editable.types.defaults.content,s=b.editable.types[a.type].element||b.editable.types.defaults.element,n=b.editable.types[a.type].reset||b.editable.types.defaults.reset,q=a.callback||function(){},t=a.onedit||function(){},u=a.onsubmit||function(){},v=a.onreset||function(){},w=a.onerror||n;a.tooltip&&b(this).attr("title",a.tooltip);a.autowidth="auto"==a.width;a.autoheight="auto"==a.height;return this.each(function(){var d=this,c=b(d).width(),e=b(d).height();b(this).data("event.editable",
a.event);b.trim(b(this).html())||b(this).html(a.placeholder);b(this).bind(a.event,function(k){if(!0!==b(this).data("disabled.editable")&&!d.editing&&!1!==t.apply(this,[a,d])){k.preventDefault();k.stopPropagation();a.tooltip&&b(d).removeAttr("title");0==b(d).width()?(a.width=c,a.height=e):("none"!=a.width&&(a.width=a.autowidth?b(d).width():a.width),"none"!=a.height&&(a.height=a.autoheight?b(d).height():a.height));b(this).html().toLowerCase().replace(/(;|")/g,"")==a.placeholder.toLowerCase().replace(/(;|")/g,
"")&&b(this).html("");d.editing=!0;d.revert=b(d).html();b(d).html("");var f=b("<form />");a.cssclass&&("inherit"==a.cssclass?f.attr("class",b(d).attr("class")):f.attr("class",a.cssclass));a.style&&("inherit"==a.style?(f.attr("style",b(d).attr("style")),f.css("display",b(d).css("display"))):f.attr("style",a.style));var g=s.apply(f,[a,d]),l;if(a.loadurl){var m=setTimeout(function(){g.disabled=!0;p.apply(f,[a.loadtext,a,d])},100);k={};k[a.id]=d.id;b.isFunction(a.loaddata)?b.extend(k,a.loaddata.apply(d,
[d.revert,a])):b.extend(k,a.loaddata);b.ajax({type:a.loadtype,url:a.loadurl,data:k,async:!1,success:function(a){window.clearTimeout(m);l=a;g.disabled=!1}})}else a.data?(l=a.data,b.isFunction(a.data)&&(l=a.data.apply(d,[d.revert,a]))):l=d.revert;p.apply(f,[l,a,d]);g.attr("name",a.name);r.apply(f,[a,d]);b(d).append(f);h.apply(f,[a,d]);b(":input:visible:enabled:first",f).focus();a.select&&g.select();g.keydown(function(b){27==b.keyCode&&(b.preventDefault(),n.apply(f,[a,d]))});"cancel"==a.onblur?g.blur(function(){m=
setTimeout(function(){n.apply(f,[a,d])},500)}):"submit"==a.onblur?g.blur(function(){m=setTimeout(function(){f.submit()},200)}):b.isFunction(a.onblur)?g.blur(function(){a.onblur.apply(d,[g.val(),a])}):g.blur(function(){});f.submit(function(c){m&&clearTimeout(m);c.preventDefault();if(!1!==u.apply(f,[a,d])&&!1!==j.apply(f,[a,d]))if(b.isFunction(a.target))c=a.target.apply(d,[g.val(),a]),b(d).html(c),d.editing=!1,q.apply(d,[d.innerHTML,a]),b.trim(b(d).html())||b(d).html(a.placeholder);else{c={};c[a.name]=
g.val();c[a.id]=d.id;b.isFunction(a.submitdata)?b.extend(c,a.submitdata.apply(d,[d.revert,a])):b.extend(c,a.submitdata);"PUT"==a.method&&(c._method="put");b(d).html(a.indicator);var e={type:"POST",data:c,dataType:"html",url:a.target,success:function(c){"html"==e.dataType&&b(d).html(c);d.editing=!1;q.apply(d,[c,a]);b.trim(b(d).html())||b(d).html(a.placeholder)},error:function(b){w.apply(f,[a,d,b])}};b.extend(e,a.ajaxoptions);b.ajax(e)}b(d).attr("title",a.tooltip);return!1})}});this.reset=function(c){this.editing&&
!1!==v.apply(c,[a,d])&&(b(d).html(d.revert),d.editing=!1,b.trim(b(d).html())||b(d).html(a.placeholder),a.tooltip&&b(d).attr("title",a.tooltip))}})}};b.editable={types:{defaults:{element:function(){var c=b('<input type="hidden"></input>');b(this).append(c);return c},content:function(c){b(":input:first",this).val(c)},reset:function(b,e){e.reset(this)},buttons:function(c,e){var a=this;if(c.submit){if(c.submit.match(/>$/))var h=b(c.submit).click(function(){"submit"!=h.attr("type")&&a.submit()});else h=
b('<button type="submit" />'),h.html(c.submit);b(this).append(h)}if(c.cancel){if(c.cancel.match(/>$/))var j=b(c.cancel);else j=b('<button type="cancel" />'),j.html(c.cancel);b(this).append(j);b(j).click(function(){(b.isFunction(b.editable.types[c.type].reset)?b.editable.types[c.type].reset:b.editable.types.defaults.reset).apply(a,[c,e]);return!1})}}},text:{element:function(c){var e=b("<input />");"none"!=c.width&&e.width(c.width);"none"!=c.height&&e.height(c.height);e.attr("autocomplete","off");b(this).append(e);
return e}},textarea:{element:function(c){var e=b("<textarea />");c.rows?e.attr("rows",c.rows):"none"!=c.height&&e.height(c.height);c.cols?e.attr("cols",c.cols):"none"!=c.width&&e.width(c.width);b(this).append(e);return e}},select:{element:function(){var c=b("<select />");b(this).append(c);return c},content:function(c,e,a){if(String==c.constructor)eval("var json = "+c);else var h=c;for(var j in h)h.hasOwnProperty(j)&&"selected"!=j&&(c=b("<option />").val(j).append(h[j]),b("select",this).append(c));
b("select",this).children().each(function(){(b(this).val()==h.selected||b(this).text()==b.trim(a.revert))&&b(this).attr("selected","selected")})}}},addInputType:function(c,e){b.editable.types[c]=e}};b.fn.editable.defaults={name:"value",id:"id",type:"text",width:"auto",height:"auto",event:"click.editable",onblur:"cancel",loadtype:"GET",loadtext:"Loading...",placeholder:"Click to edit",loaddata:{},submitdata:{},ajaxoptions:{}}})(jQuery);
(function(){var b=function(a,b){return function(){return a.apply(b,arguments)}};pe.users||(pe.users={});var c=pe.users,e=function(a){var c=this;this.container=a;this.on_summary_keyup=b(this.on_summary_keyup,this);this.on_submit_summary=b(this.on_submit_summary,this);this.summary_container=this.container.find(".EditableSummary");this.counter=this.container.find(".SummaryCounter");this.counter_container=this.container.find(".CounterContainer");this.counter_container.hide();this.counter.html(200-this.summary_container.html().length);
this.summary_container.editable(this.on_submit_summary,{placeholder:"Please write something about yourself",type:"textarea",cssclass:"textarea_editable",onblur:"submit",rows:2,select:!1,data:function(a){return a.replace(/<br[\s\/]?>/gi,"\n")}});this.summary_container.click(function(){c.counter_container.show();c.on_summary_keyup();return c.summary_container.find("textarea").bind("propertychange input textInput",c.on_summary_keyup)})};e.prototype.on_submit_summary=function(a){this.counter_container.hide();
pe.routes.Request.from_current_location("api_user",{user:{summary:a},_method:"put"}).post();return a.replace(/\n/g,"<br>")};e.prototype.on_summary_keyup=function(){var a,b,c;c=this.summary_container.find("textarea");b=c.val();a=200-b.length;0>=a&&(a=0,c.val(b.slice(0,200)));return this.counter.html(a)};c.SummaryEditor=e}).call(this);
