pe.HelpModule=function(a,b,c){pe.init_widget(this,a);this.help_module_open=!1;this.help_id=b;this.container.append(this.html(c));this.container.click(this.callback(this.help_button_clicked));this.help_button_div=this.container.find(".HelpButton");(this.admin_link=this.container.find(".AdminLink"))&&this.admin_link.click(this.callback(this.admin_link_clicked))};
pe.HelpModule.prototype.html=function(a){var b="";0===this.container.contents().length&&(b+='<div class="fake_link help_btn HelpButton"></div>');a&&(b+='<div><a class="AdminLink admin_edit" target="_blank" href="/admin/pages/'+this.help_id+'/edit">Edit Tip</a></div>');return b};pe.HelpModule.prototype.admin_link_clicked=function(a){a.stopPropagation()};
pe.HelpModule.prototype.help_button_clicked=function(a){this.help_module_open?a.stopPropagation():pe.ajax_loader.help_page.load({page_id:this.help_id,timestamp:pe.pages_timestamp()},this.callback(function(a){this.help_button_div.append(this.dialog_box_html(a));a=this.container.find(".DialogBox");this.help_module_open=!0;new pe.CloseButton(a,this.callback(this.close_dialog,a))}))};
pe.HelpModule.prototype.dialog_box_html=function(a){return pe.templatize('<div id="tool_tip"><table class="DialogBox" cellpadding="0" cellspacing="0"><tbody><tr class="tip_header_row"><td class="tip_left_corner tooltip_sprite"></td><td class="tip_mid_section tooltip_sprite"></td><td class="tip_right_corner tooltip_sprite"></td></tr><tr class="tip_content_container"><td class="tip_left_side tooltip_sprite" width="10"><div class="tooltip_arrow tooltip_sprite"></div></td><td width="220"><div class="tip_content"><div class="CloseButton tip_close_btn tooltip_sprite" title="Close"></div><h1 class="tooltip_title">{{title}}</h1>{{content}}</div></td><td class="tip_right_side tooltip_sprite" width="17"></td></tr><tr class="tip_footer_row"><td class="tip_left_corner tooltip_sprite"></td><td class="tip_mid_section tooltip_sprite"></td><td class="tip_right_corner tooltip_sprite"></td></tr></tbody></table></div>',a)};
pe.HelpModule.prototype.close_dialog=function(a,b){this.help_module_open=!1;a.remove();b.stopPropagation()};
pe.Input=function(a,b){pe.init_widget(this,a);this.options=b;this.options.label||(this.options.label="");this.container.html(this.html(this.options));this.carrier=this.options.carrier||null;this.state=b.initial_state?b.initial_state:pe.Input.states.UNCHECKED;this.update_ui();this.type=b.type;this.click_state=pe.Input.click_states.NOT_PRESSED;this.disabled=!1;this.container.addClass(b.type);this.container.click(this.callback(this.clicked));this.container.mousedown(this.callback(this.mouse_down));this.container.mouseup(this.callback(this.mouse_up))};
pe.Input.events={CHANGED:"Input_CHANGED"};pe.Input.states={CHECKED:"CHECKED",UNCHECKED:"UNCHECKED"};pe.Input.click_states={PRESSED:"PRESSED",NOT_PRESSED:"NOT PRESSED"};pe.Input.types={CHECKBOX:"Checkbox",RADIO_BUTTON:"RadioButton"};pe.Input.prototype.clicked=function(a){this.toggle_checked_status();this.update_ui();a&&a.stopPropagation();this.fire_event(pe.Input.events.CHANGED,this)};pe.Input.prototype.check=function(){this.set_checked(!0)};pe.Input.prototype.disable=function(){this.disabled=!0;this.update_ui()};
pe.Input.prototype.enable=function(){this.disabled=!1;this.update_ui()};pe.Input.prototype.is_checked=function(){return this.state===pe.Input.states.CHECKED};pe.Input.prototype.html=function(a){return pe.templatize('<div class="Input input_selection"></div>{{label}}',a)};pe.Input.prototype.mouse_down=function(){this.click_state=pe.Input.click_states.PRESSED;this.update_ui()};pe.Input.prototype.mouse_up=function(){this.click_state=pe.Input.click_states.NOT_PRESSED;this.update_ui()};
pe.Input.prototype.set_checked=function(a){this.state=a?pe.Input.states.CHECKED:pe.Input.states.UNCHECKED;this.carrier&&this.carrier.attr("checked",a);this.update_ui()};pe.Input.prototype.toggle_checked_status=function(){this.set_checked(!this.is_checked())};pe.Input.prototype.uncheck=function(){this.set_checked(!1)};
pe.Input.prototype.update_ui=function(){this.container.removeClass("checked unchecked checked_pressed unchecked_pressed checked_disabled unchecked_disabled");var a=this.state===pe.Input.states.UNCHECKED?"unchecked":"checked",b=this.disabled?"_disabled":"",c=this.click_state===pe.Input.click_states.PRESSED?"_pressed":"";b&&(c="");this.container.addClass(a+b+c)};
pe.CharacterOverlay=function(a){pe.init_widget(this,$(this.html()));a.append(this.container);this.checkbox_lucas=new pe.Input(this.container.find(".Characters .Lucas .Input"),{type:pe.Input.types.CHECKBOX,label:"Lucas",initial_state:pe.Input.states.CHECKED});this.checkbox_lucas.bind_event(pe.Input.events.CHANGED,this.callback(this.selection_changed));this.container.find(".Characters .Lucas .Image").click(this.callback(function(){this.checkbox_lucas.clicked()}));this.checkbox_adriana=new pe.Input(this.container.find(".Characters .Adriana .Input"),
{type:pe.Input.types.CHECKBOX,label:"Adriana",initial_state:pe.Input.states.CHECKED});this.checkbox_adriana.bind_event(pe.Input.events.CHANGED,this.callback(this.selection_changed));this.container.find(".Characters .Adriana .Image").click(this.callback(function(){this.checkbox_adriana.clicked()}));this.checkbox_jonah=new pe.Input(this.container.find(".Characters .Jonah .Input"),{type:pe.Input.types.CHECKBOX,label:"Jonah",initial_state:pe.Input.states.CHECKED});this.checkbox_jonah.bind_event(pe.Input.events.CHANGED,
this.callback(this.selection_changed));this.container.find(".Characters .Jonah .Image").click(this.callback(function(){this.checkbox_jonah.clicked()}));this.checkbox_emma=new pe.Input(this.container.find(".Characters .Emma .Input"),{type:pe.Input.types.CHECKBOX,label:"Emma",initial_state:pe.Input.states.CHECKED});this.checkbox_emma.bind_event(pe.Input.events.CHANGED,this.callback(this.selection_changed));this.container.find(".Characters .Emma .Image").click(this.callback(function(){this.checkbox_emma.clicked()}));
new pe.CloseButton(this.container,pe.CloseButton.close_methods.HIDE);new pe.HelpModule($(".CharacterHelpButton"),"what-are-these-ratings",!1)};pe.CharacterOverlay.events={CHANGED:"CityMap_CharacterSelect_CHANGED"};pe.CharacterOverlay.prototype.add_search_configuration=function(a){a.add_filter("characters",this.get_selected_characters())};
pe.CharacterOverlay.prototype.get_selected_characters=function(){var a=[];this.checkbox_lucas.is_checked()&&a.push("lucas");this.checkbox_adriana.is_checked()&&a.push("adriana");this.checkbox_jonah.is_checked()&&a.push("jonah");this.checkbox_emma.is_checked()&&a.push("emma");return a};pe.CharacterOverlay.prototype.html=function(){return'<div class="overlay"><div class="headline">Select a Personality</div><ul class="characters Characters"><li id="lucas_select" class="Lucas character_select float_left" data="2"><div class="Image figures selected"></div> <div class="Input"></div></li><li id="adriana_select" class="Adriana character_select float_left" data="3"><div class="Image figures selected"></div> <div class="Input"></div></li><li id="jonah_select" class="Jonah character_select float_left" data="4"><div class="Image figures selected"></div> <div class="Input"></div></li><li id="emma_select" class="Emma character_select float_left" data="5"><div class="Image figures selected"></div> <div class="Input"></div></li></ul><div class="fake_link CloseButton"></div><div class="CharacterHelpButton"></div> <div id="character_arrow" class="overlay_arrow"></div> </div>'};
pe.CharacterOverlay.prototype.read_search_configuration=function(a){a=a.get_filter("characters");$(this.checkbox_lucas.set_checked(-1<a.indexOf("lucas")));$(this.checkbox_adriana.set_checked(-1<a.indexOf("adriana")));$(this.checkbox_jonah.set_checked(-1<a.indexOf("jonah")));$(this.checkbox_emma.set_checked(-1<a.indexOf("emma")))};
pe.CharacterOverlay.prototype.selection_changed=function(){this.container.find(".Characters .figures").removeClass("selected");var a=this.get_selected_characters();$.each(a,this.callback(function(a,c){this.container.find(".Characters ."+pe.capitalise_first_letter(c)).find(".figures").addClass("selected")}));this.fire_event(pe.CharacterOverlay.events.CHANGED)};
