pe.Accordion=function(a,b){pe.init_widget(this,a);this.expand_collapse_link=this.container.find(".ExpandCollapseLink");this.expand_collapse_link.click(this.callback(this.on_expand_collapse_link_click));this.accordion_label_div=this.container.find(".AccordionLabel");this.accordion_collapsed=!1;this.content_div=this.container.find(".AccordionContent");this.content_div_height=0;b?this.expand_accordion():this.collapse_accordion()};pe.Accordion.events={COLLAPSED:"Accordion_COLLAPSED",EXPANDED:"Accordion_EXPANDED"};
pe.Accordion.prototype.animate=function(a,b){this.content_div.animate({height:a},300,"cubicEaseInOut",function(){b&&b()})};pe.Accordion.prototype.collapse_accordion=function(){this.expand_collapse_link.removeClass("collapse_bar_wrapper").addClass("expand_bar_wrapper");this.accordion_label_div.html("Expand");this.accordion_collapsed=!0;this.animate(0);this.fire_event(pe.Accordion.events.COLLAPSED)};
pe.Accordion.prototype.expand_accordion=function(a){this.expand_collapse_link.removeClass("expand_bar_wrapper").addClass("collapse_bar_wrapper");this.accordion_label_div.html("Collapse");this.accordion_collapsed=!1;this.content_div_height=parseInt(this.content_div.css("height","auto").height(),10);this.content_div.css("height",0);this.fire_event(pe.Accordion.events.EXPANDED);this.animate(this.content_div_height,a)};
pe.Accordion.prototype.on_expand_collapse_link_click=function(){this.accordion_collapsed?this.expand_accordion():this.collapse_accordion()};
pe.ReadMore=function(a,b,c){0<a.length&&(pe.init_widget(this,a),this.read_more_control=this.container.find(".ReadMoreControl"),this.read_less_control=this.container.find(".ReadLessControl"),this.read_more_link=this.container.find(".ReadMoreLink"),this.read_more_link.click(this.callback(this.on_read_more_link_clicked)),this.read_less_link=this.container.find(".ReadLessLink"),this.read_less_link.click(this.callback(this.on_read_less_link_clicked)),this.long_description=this.container.find(".LongDescription"),
this.thumbs=this.container.find(".thumbnails"),this.photos=this.container.find(".photo"),this.read_more_handler=b,this.read_less_handler=c)};pe.ReadMore.events={LONG_DESC_OPENED:"ReadMore_LONG_DESC_OPENED"};
pe.ReadMore.prototype.on_read_more_link_clicked=function(){this.long_description.removeClass("clipped");this.read_less_control.show();this.read_more_control.hide();this.thumbs.addClass("hidden");this.photos.removeClass("hidden");pe.fire_global_event(pe.ReadMore.events.LONG_DESC_OPENED);"function"===typeof this.read_more_handler&&this.read_more_handler()};
pe.ReadMore.prototype.on_read_less_link_clicked=function(){this.read_less_control.hide();this.read_more_control.show();this.thumbs.removeClass("hidden");this.photos.addClass("hidden");this.long_description.addClass("clipped");"function"===typeof this.read_less_handler&&this.read_less_handler()};pe.ReadMore.instantiate=function(){return $.map($(".ReadMore"),function(a){return new pe.ReadMore($(a))})};
pe.ScheduleRenderer=function(a,b){pe.init_widget(this,a);this.schedule_link_target=b;var c=this.container.find(".ReadMoreSchedule");0<c.length&&(this.read_more_section=new pe.ReadMore(c),this.read_more_section.read_less_link.click(this.callback(this.read_less_link_clicked)));c=$(".CustomAccordion");if(0<c.length){var e,d;$.each(c,this.callback(function(a,b){d=$(b);e=new pe.Accordion(d,d.attr("data-expand"));this.read_more_section&&e.bind_event(pe.Accordion.events.EXPANDED,this.callback(this.accordion_expanded))}))}};
pe.ScheduleRenderer.prototype.accordion_expanded=function(){this.read_more_section.read_more_link.click()};pe.ScheduleRenderer.prototype.read_less_link_clicked=function(){pe.animated_scrolling(this.schedule_link_target,1);return!1};
