(function(){if(!window.CKEDITOR||!window.CKEDITOR.dom){window.CKEDITOR||(window.CKEDITOR=function(){var b={timestamp:"C3HA5RM",version:"3.6.3",revision:"7474",rnd:Math.floor(900*Math.random())+100,_:{},status:"unloaded",basePath:function(){var a=window.CKEDITOR_BASEPATH||"";if(!a)for(var b=document.getElementsByTagName("script"),c=0;c<b.length;c++){var f=b[c].src.match(/(^|.*[\\\/])ckeditor(?:_basic)?(?:_source)?.js(?:\?.*)?$/i);if(f){a=f[1];break}}-1==a.indexOf(":/")&&(a=0===a.indexOf("/")?location.href.match(/^.*?:\/\/[^\/]*/)[0]+
a:location.href.match(/^[^\?]*\/(?:)/)[0]+a);if(!a)throw'The CKEditor installation path could not be automatically detected. Please set the global variable "CKEDITOR_BASEPATH" before creating editor instances.';return a}(),getUrl:function(a){-1==a.indexOf(":/")&&0!==a.indexOf("/")&&(a=this.basePath+a);this.timestamp&&"/"!=a.charAt(a.length-1)&&!/[&?]t=/.test(a)&&(a+=(0<=a.indexOf("?")?"&":"?")+"t="+this.timestamp);return a}},c=window.CKEDITOR_GETURL;if(c){var a=b.getUrl;b.getUrl=function(d){return c.call(b,
d)||a.call(b,d)}}return b}());var b=CKEDITOR;b.event||(b.event=function(){},b.event.implementOn=function(f){var c=b.event.prototype,a;for(a in c)f[a]==void 0&&(f[a]=c[a])},b.event.prototype=function(){var b=function(a){a=a.getPrivate&&a.getPrivate()||a._||(a._={});return a.events||(a.events={})},c=function(a){this.name=a;this.listeners=[]};c.prototype={getListenerIndex:function(a){for(var b=0,c=this.listeners;b<c.length;b++)if(c[b].fn==a)return b;return-1}};return{on:function(a,d,e,j,i){var g=b(this),
g=g[a]||(g[a]=new c(a));if(g.getListenerIndex(d)<0){g=g.listeners;e||(e=this);isNaN(i)&&(i=10);var l=this,h=function(b,c,f,g){b={name:a,sender:this,editor:b,data:c,listenerData:j,stop:f,cancel:g,removeListener:function(){l.removeListener(a,d)}};d.call(e,b);return b.data};h.fn=d;h.priority=i;for(var k=g.length-1;k>=0;k--)if(g[k].priority<=i){g.splice(k+1,0,h);return}g.unshift(h)}},fire:function(){var a=false,c=function(){a=true},e=false,j=function(){e=true};return function(i,g,l){var h=b(this)[i],
i=a,k=e;a=e=false;if(h){h=h.listeners;if(h.length)for(var h=h.slice(0),m=0;m<h.length;m++){var n=h[m].call(this,l,g,c,j);typeof n!="undefined"&&(g=n);if(a||e)break}}g=e||(typeof g=="undefined"?false:g);a=i;e=k;return g}}(),fireOnce:function(a,c,e){c=this.fire(a,c,e);delete b(this)[a];return c},removeListener:function(a,c){var e=b(this)[a];if(e){var j=e.getListenerIndex(c);j>=0&&e.listeners.splice(j,1)}},hasListeners:function(a){return(a=b(this)[a])&&a.listeners.length>0}}}());b.editor||(b.ELEMENT_MODE_NONE=
0,b.ELEMENT_MODE_REPLACE=1,b.ELEMENT_MODE_APPENDTO=2,b.editor=function(f,c,a,d){this._={instanceConfig:f,element:c,data:d};this.elementMode=a||0;b.event.call(this);this._init()},b.editor.replace=function(f,c){var a=f;if(typeof a!="object"){(a=document.getElementById(f))&&a.tagName.toLowerCase()in{style:1,script:1,base:1,link:1,meta:1,title:1}&&(a=null);if(!a)for(var d=0,e=document.getElementsByName(f);(a=e[d++])&&a.tagName.toLowerCase()!="textarea";);if(!a)throw'[CKEDITOR.editor.replace] The element with id or name "'+
f+'" was not found.';}a.style.visibility="hidden";return new b.editor(c,a,1)},b.editor.appendTo=function(f,c,a){var d=f;if(typeof d!="object"){d=document.getElementById(f);if(!d)throw'[CKEDITOR.editor.appendTo] The element with id "'+f+'" was not found.';}return new b.editor(c,d,2,a)},b.editor.prototype={_init:function(){(b.editor._pending||(b.editor._pending=[])).push(this)},fire:function(f,c){return b.event.prototype.fire.call(this,f,c,this)},fireOnce:function(f,c){return b.event.prototype.fireOnce.call(this,
f,c,this)}},b.event.implementOn(b.editor.prototype,!0));b.env||(b.env=function(){var b=navigator.userAgent.toLowerCase(),c=window.opera,a={ie:false,opera:!!c&&c.version,webkit:b.indexOf(" applewebkit/")>-1,air:b.indexOf(" adobeair/")>-1,mac:b.indexOf("macintosh")>-1,quirks:document.compatMode=="BackCompat",mobile:b.indexOf("mobile")>-1,iOS:/(ipad|iphone|ipod)/.test(b),isCustomDomain:function(){if(!this.ie)return false;var a=document.domain,b=window.location.hostname;return a!=b&&a!="["+b+"]"},secure:location.protocol==
"https:"};a.gecko=navigator.product=="Gecko"&&!a.webkit&&!a.opera;var d=0;if(a.ie){d=parseFloat(b.match(/msie (\d+)/)[1]);a.ie8=!!document.documentMode;a.ie8Compat=document.documentMode==8;a.ie9Compat=document.documentMode==9;a.ie7Compat=d==7&&!document.documentMode||document.documentMode==7;a.ie6Compat=d<7||a.quirks}if(a.gecko){var e=b.match(/rv:([\d\.]+)/);if(e){e=e[1].split(".");d=e[0]*1E4+(e[1]||0)*100+ +(e[2]||0)}}a.opera&&(d=parseFloat(c.version()));a.air&&(d=parseFloat(b.match(/ adobeair\/(\d+)/)[1]));
a.webkit&&(d=parseFloat(b.match(/ applewebkit\/(\d+)/)[1]));a.version=d;a.isCompatible=a.iOS&&d>=534||!a.mobile&&(a.ie&&d>=6||a.gecko&&d>=10801||a.opera&&d>=9.5||a.air&&d>=1||a.webkit&&d>=522||false);a.cssClass="cke_browser_"+(a.ie?"ie":a.gecko?"gecko":a.opera?"opera":a.webkit?"webkit":"unknown");if(a.quirks)a.cssClass=a.cssClass+" cke_browser_quirks";if(a.ie){a.cssClass=a.cssClass+(" cke_browser_ie"+(a.version<7?"6":a.version>=8?document.documentMode:"7"));if(a.quirks)a.cssClass=a.cssClass+" cke_browser_iequirks"}if(a.gecko&&
d<10900)a.cssClass=a.cssClass+" cke_browser_gecko18";if(a.air)a.cssClass=a.cssClass+" cke_browser_air";return a}());var o=b.env;"unloaded"==b.status&&function(){b.event.implementOn(b);b.loadFullCore=function(){if(b.status!="basic_ready")b.loadFullCore._load=1;else{delete b.loadFullCore;var c=document.createElement("script");c.type="text/javascript";c.src=b.basePath+"ckeditor.js";document.getElementsByTagName("head")[0].appendChild(c)}};b.loadFullCoreTimeout=0;b.replaceClass="ckeditor";b.replaceByClassEnabled=
1;var f=function(c,a,d,e){if(o.isCompatible){b.loadFullCore&&b.loadFullCore();c=d(c,a,e);b.add(c);return c}return null};b.replace=function(c,a){return f(c,a,b.editor.replace)};b.appendTo=function(c,a,d){return f(c,a,b.editor.appendTo,d)};b.add=function(b){(this._.pending||(this._.pending=[])).push(b)};b.replaceAll=function(){for(var b=document.getElementsByTagName("textarea"),a=0;a<b.length;a++){var d=null,e=b[a];if(e.name||e.id){if(typeof arguments[0]=="string"){if(!RegExp("(?:^|\\s)"+arguments[0]+
"(?:$|\\s)").test(e.className))continue}else if(typeof arguments[0]=="function"){d={};if(arguments[0](e,d)===false)continue}this.replace(e,d)}}};(function(){var c=function(){var a=b.loadFullCore,c=b.loadFullCoreTimeout;b.replaceByClassEnabled&&b.replaceAll(b.replaceClass);b.status="basic_ready";a&&a._load?a():c&&setTimeout(function(){b.loadFullCore&&b.loadFullCore()},c*1E3)};window.addEventListener?window.addEventListener("load",c,false):window.attachEvent&&window.attachEvent("onload",c)})();b.status=
"basic_loaded"}()}})();
