pe.NeighborhoodVenueTemplate=function(a,b){pe.init_widget(this,null);this.container=$(this.html(b));a.append(this.container);new pe.SearchResultCharacterRatingModule(this.container.find(".CharacterRating"),b)};
pe.NeighborhoodVenueTemplate.prototype.html=function(a){a.types_text=$.map(a.venue_types_with_categories,function(b){return pe.templatize('<a class="SearchPageLink"data-category="{{category}}"data-sort_by="rating"data-what="{{type_url_param}}"data-filters_section_visible="true"data-message="Search results for <b>{{type}}</b> in {{city}}">{{type}}</a>',{type:b[0],category:b[1]||"all_results",type_url_param:b[2],city:"{{city}}",city_name:a.city_name})}).join(" / ").replace(/\s\/\s$/,"");a.link_title_types_text=
a.venue_types.join(" | ");a.day_spot_text=a.day_spot?'<span class="day_spot_small icon_types""></span>':"";a.night_spot_text=a.night_spot?'<span class="night_spot_small icon_types"></span>':"";a.primary_photo=pe.https(pe.assign_photo_size(a.thumbnail,"155","155x105"));a.link_title=pe.templatize("Check out the review, photos, map and events schedule of {{name}} - {{link_title_types_text}} in {{city_name}}.",a);var b=new Date;a.hotspot_today_img=void 0!==a.hotspot_days?pe.VenueSearcher.venue_is_hotspot_in_date_range(a,
b,b)?'<span class="hot_spot_small icon_types"></span>':"":"";return pe.templatize('<li class="venue_pod"><div class="venue_image float_left"><a href="{{url}}" class="ConvertToRoundedCorners" target="_blank" title="{{link_title}}"><img src="{{primary_photo}}" alt="{{name}}"></a></div><h3 class="venue_name headline sub_headline"><a href="{{url}}" target="_blank">{{name}}</a></h3><p class="types float_left"><span class="type text float_left">{{types_text}}</span>{{hotspot_today_img}}{{day_spot_text}}{{night_spot_text}}</p><div class="CharacterRating ratings_small_wrapper float_left"></div><div class="desc float_left">{{description}}<div class="read_more_arrow"><a href="{{url}}" class="float_right"></a> </div> </div><div class="clear"></div></li>',
a)};
pe.Paginator=function(a,b,c,d){pe.init_widget(this,a);this.objects=null;this.max_page_number=this.current_page_number=0;this.page_size=d;this.search_configuration=null;this.container&&(this.result_entry_constructor=c,this.container.html(this.dom()),this.objects_list=pe.load(this.container.find(".ObjectsList")),this.objects_counter=b,this.prev_button=pe.load(this.container.find(".PrevButton")),this.prev_button.click(this.callback(this.venue_prev_clicked)),this.next_button=pe.load(this.container.find(".NextButton")),this.next_button.click(this.callback(this.venue_next_clicked)),
this.current_page_number_display=pe.load(this.container.find(".CurrentPageNumber")))};pe.Paginator.events={PAGE_CHANGED:"Paginator_PAGE_CHANGED"};pe.Paginator.prototype.calculate_max_page_number=function(a){a=Math.ceil(a/this.page_size);return 0===a?1:a};pe.Paginator.prototype.dom=function(){return'<ul class="ObjectsList"></ul><div class="pod_footer"><div class="prev_next"><span class="PrevButton prev_btn float_left fake_link"></span><span class="NextButton next_btn float_right fake_link"></span><span class="CurrentPageNumber page_count float_right"></span> </div><span class="see_more float_right"></span><div>'};
pe.Paginator.prototype.preload=function(a,b,c){this.objects=a;this.max_page_number=this.calculate_max_page_number(b);this.search_configuration=c;this.show_page(0)};pe.Paginator.prototype.set_objects=function(a,b){null!==a&&(this.objects=$.grep(a,function(a){return!a.disabled}),this.search_configuration=b,this.max_page_number=this.calculate_max_page_number(this.objects.length),this.container&&(this.objects_counter&&this.objects_counter.html(this.objects.length),this.show_page(0)))};
pe.Paginator.prototype.show_page=function(a){this.current_page_number=a;this.current_page_number_display.html(a+1+"/"+this.max_page_number);this.objects_list.html("");for(var a=this.current_page_number*this.page_size,b=0;b<this.page_size;){var c=this.objects[a];if(!c)break;new this.result_entry_constructor(this.objects_list,c,this.search_configuration);b++;a++}0===this.current_page_number?(this.prev_button.addClass("disabled"),0===this.max_page_number-1?this.next_button.addClass("disabled"):this.next_button.removeClass("disabled")):
this.current_page_number>=this.max_page_number-1?(this.prev_button.removeClass("disabled"),this.next_button.addClass("disabled")):(this.prev_button.removeClass("disabled"),this.next_button.removeClass("disabled"));this.fire_event(pe.Paginator.events.PAGE_CHANGED);pe.convert_to_rounded_corners(this.objects_list.find(".ConvertToRoundedCorners"))};
pe.Paginator.prototype.venue_next_clicked=function(a){this.current_page_number>=this.max_page_number-1?a.stopPropagation():this.show_page(this.current_page_number+1)};pe.Paginator.prototype.venue_prev_clicked=function(a){0===this.current_page_number?a.stopPropagation():this.show_page(this.current_page_number-1)};
pe.NeighborhoodVenuesList=function(a,b,c){pe.init_widget(this,a);this.container.html(this.html());this.paginator=new pe.Paginator(a.find(".VenueList"),null,pe.NeighborhoodVenueTemplate,5);this.paginator.preload(b,c)};pe.NeighborhoodVenuesList.prototype.html=function(){return'<div class="venue_list"><h2 class="header">Neighborhood Venues</h2><div class="VenueList"></div></div><div class="show_venues"></div>'};pe.NeighborhoodVenuesList.prototype.set_venues=function(a){this.paginator.set_objects(a)};
