(function(a){var b={topSpacing:0,bottomSpacing:0,className:"is-sticky",wrapperClassName:"sticky-wrapper",center:!1,getWidthFrom:""},c=a(window),d=a(document),e=[],f=c.height(),h=function(){for(var b=c.scrollTop(),h=d.height(),l=h-f,l=b>l?l-b:0,k=0;k<e.length;k++){var g=e[k],j=g.stickyWrapper.offset().top-g.topSpacing-l;b<=j?null!==g.currentTop&&(g.stickyElement.css("position","").css("top",""),g.stickyElement.parent().removeClass(g.className),g.currentTop=null):(j=h-g.stickyElement.outerHeight()-
g.topSpacing-g.bottomSpacing-b-l,j=0>j?j+g.topSpacing:g.topSpacing,g.currentTop!=j&&(g.stickyElement.css("position","fixed").css("top",j),"undefined"!==typeof g.getWidthFrom&&g.stickyElement.css("width",a(g.getWidthFrom).width()),g.stickyElement.parent().addClass(g.className),g.currentTop=j))}},k=function(){f=c.height()},j={init:function(c){var d=a.extend(b,c);return this.each(function(){var b=a(this);stickyId=b.attr("id");wrapper=a("<div></div>").attr("id",stickyId+"-sticky-wrapper").addClass(d.wrapperClassName);
b.wrapAll(wrapper);d.center&&b.parent().css({width:b.outerWidth(),marginLeft:"auto",marginRight:"auto"});"right"==b.css("float")&&b.css({"float":"none"}).parent().css({"float":"right"});var c=b.parent();c.css("height",b.outerHeight());e.push({topSpacing:d.topSpacing,bottomSpacing:d.bottomSpacing,stickyElement:b,currentTop:null,stickyWrapper:c,className:d.className,getWidthFrom:d.getWidthFrom})})},update:h};window.addEventListener?(window.addEventListener("scroll",h,!1),window.addEventListener("resize",
k,!1)):window.attachEvent&&(window.attachEvent("onscroll",h),window.attachEvent("onresize",k));a.fn.sticky=function(b){if(j[b])return j[b].apply(this,Array.prototype.slice.call(arguments,1));if("object"===typeof b||!b)return j.init.apply(this,arguments);a.error("Method "+b+" does not exist on jQuery.sticky")};a(function(){setTimeout(h,0)})})(jQuery);
pe.accentMap={"&":"and","\u00e0":"a","\u00e1":"a","\u00e2":"a","\u00e3":"a","\u00e4":"a","\u00e5":"a","\u00e7":"c","\u00c0":"a","\u00c1":"a","\u00e8":"e","\u00e9":"e","\u00ea":"e","\u00eb":"e","\u00c8":"e","\u00c9":"e","\u00ec":"i","\u00f1":"n","\u00ed":"i","\u00ee":"i","\u00ef":"i","\u00f2":"o","\u00f3":"o","\u00f4":"o","\u00f5":"o","\u00f6":"o","\u00f9":"u","\u00fa":"u","\u00fb":"u","\u00fc":"u","!":"i",$:"s","-":""," ":"","'":"","\u2019":"",".":""};pe.ajax_error=function(){alert("The request failed. Please try again later.")};
pe.ajax_send=function(a,b){var c=$("meta[name='csrf-token']").attr("content");b.setRequestHeader("X-CSRF-Token",c)};pe.alert=function(a){alert(a)};pe.animated_scrolling=function(a,b){if(0!==a.length){var c=a.offset().top-(b||25);$("html,body").stop().animate({scrollTop:c+"px"},800,"cubicEaseInOut",function(){return!1})}};pe.scrolling=function(a,b){if(0!==a.length){var c=a.offset().top-(b||25);$("html,body").scrollTop(c)}};pe.days_of_week="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" ");
pe.array_contains=function(a,b){return _.isArray(b)?0===_.difference(b,a).length:-1<_.indexOf(a,b)};pe.arrays_equal=function(a,b){if(!a&&!b||!a&&0===b.length||0===a.length&&!b)return!0;if(a.length!=b.length)return!1;for(var c=a.sort(),d=b.sort(),e=0,f=a.length;e<f;e++)if(c[e]!==d[e])return!1;return!0};pe.array_match=function(a,b){var c=!1;$.each(a,function(a,e){if(-1<b.indexOf(e))return c=!0,!1});return c};pe.array_merge=function(a,b){var c=a.concat(b);c.sort();return c};
pe.array_remove=function(a,b){return!a?a:pe.is_array(b)?$.grep(a,function(a){return-1===b.indexOf(a)}):$.grep(a,function(a){return a!==b})};pe.assign_photo_size=function(a,b,c){return!a?"/assets/no_image_"+c+".png":"original"===b?a.replace("xxx.jpg",b+".jpg"):a.replace("xxx.jpg","s"+b+".jpg")};pe.remove_timestamp_from_asset_url=function(a){return a.split("?")[0]};pe.browser_is_ie8=function(){return $.browser.msie&&"8.0"===$.browser.version};
pe.build_dob_field_name=function(a,b,c){return[a||"user","[",b?b+"_":"","dob(",c,"i)]"].join("")};pe.capitalise_first_letter=function(a){return null===a?"":a.charAt(0).toUpperCase()+a.slice(1)};pe.classes_starting_with=function(a,b){return $.map(a.attr("class").split(/\s+/),function(a){if(pe.string_starts_with(a,b))return a})};pe.compare=function(a,b){return pe.is_array(a)&&pe.is_array(b)?pe.arrays_equal(a,b):a===b};
pe.convert_to_rounded_corners=function(a){a=a||$(".ConvertToRoundedCorners");a.each(function(a,c){var d=$(c);d.removeClass("ConvertToRoundedCorners");d.addClass("rounded_corner_wrapper");$('<div class="rounded_corner top_left"></div>').appendTo(d);$('<div class="rounded_corner top_right"></div>').appendTo(d);$('<div class="rounded_corner bottom_left"></div>').appendTo(d);$('<div class="rounded_corner bottom_right"></div>').appendTo(d)});return a};
pe.convert_to_tabbed_pod=function(a,b){return $.map(a,function(a){a=$(a);if(!a.hasClass("ConvertToTabbedPod"))return alert("format_tabbed_pod: element to convert must have class ConvertToTabbedPod. It only has "+a[0].className);var d=a.children("ul");d.addClass("tab");d.children("li").each(function(a,b){b=$(b);var c=b.html();b.html(pe.templatize('<div class="left_end pod_sprite float_left"></div>{{content}}<div class="right_end pod_sprite float_left"></div>',{content:c}))});var e=d.html();d.remove();
var d=a.html(),f=pe.classes_starting_with(a,"width");if(0===f.length)return alert("no width class found");if(1<f.length)return alert("more than 1 width class found");var h=f[0].substr(5);a.addClass("tabs");a.removeClass("ConvertToTabs");a.removeClass(f[0]);a.html(pe.templatize('<div><table class="width{{width}}" cellpadding="0" cellspacing="0"><tbody><tr><td class="header" colspan="4"><div class="header_row"><ul class="tab">{{headers}}</ul><div class="mid_section"></div><div class="right_corner pod_sprite"></div></div></td></tr><tr class="content_container"><td class="left_side pod_sides"></td><td class="content">{{content}}</td><td class="right_side pod_sides"></td></tr><tr class="footer_row"><td class="left_corner pod_sprite"></td><td class="mid_section"></td><td class="right_corner pod_sprite"></td></tr></tbody></table></div>',
{width:h,headers:e,content:d}));var e=a.children().tabs(b),k=["first","second","third","fourth"];a.find("ul.tab li").each(function(a,b){$(b).addClass(k[a])});return e})};
pe.new_convert_to_tabbed_pod=function(a,b){return $.map(a,function(a){a=$(a);if(!a.hasClass("ConvertToTabbedPod"))return alert("format_tabbed_pod: element to convert must have class ConvertToTabbedPod. It only has "+a[0].className);var d=a.children("ul"),e=d.html();d.remove();var d=a.html(),f=pe.classes_starting_with(a,"width");if(0===f.length)return alert("no width class found");if(1<f.length)return alert("more than 1 width class found");var h=f[0].substr(5);a.addClass("tabs");a.removeClass("ConvertToTabs");
a.removeClass(f[0]);a.html(pe.templatize('<div class="width{{width}}"><ul class="tab">{{headers}}</ul>{{content}}</div>',{width:h,headers:e,content:d}));var e=a.children().tabs(b),k=["first","second","third","fourth"];a.find("ul.tab li").each(function(a,b){$(b).addClass(k[a])});return e})};pe.date_string=function(a){return"string"===typeof a?a:a.getMonth()+1+"/"+a.getDate()+"/"+a.getFullYear()};
pe.days_between_dates=function(a,b){var c="string"===typeof a?Date.parse(a):a,d="string"===typeof b?Date.parse(b):b;return Math.abs(Math.floor((c-d)/864E5))};pe.empty=function(){};pe.event_search_text=function(a){var b=[a.name,a.description,a.location_name,a.category,a.neighborhood_name,a.neighborhood_id];a.tags&&$.each(a.tags,function(a,d){b.push(d)});a.performer_names&&$.each(a.performer_names,function(a,d){b.push(d)});return b.join(" ")};pe.fetch_photo_id_from_url=function(a){return a.split("/photos/")[1]};
pe.fix_ie7_rendering_bug=function(){$(".ConvertToTabbedPod").addClass("IeSucks")};pe.format_date=function(a){return a.getMonth()+1+"/"+a.getDate()+"/"+a.getFullYear()};pe.format_price=function(a){var b=Math.floor(a/100).toString();a=(a%100).toString();2>a.length&&(a="0"+a);return"$"+b+"."+a};pe.format_duration=function(a,b){if(!a)return"0:00";var c=Math.floor(a%60);return pe.string_padding_left(Math.floor(a/60).toString(),b||1,"0")+":"+pe.string_padding_left(c.toString(),2,"0")};pe.get_city_id=function(){return window.city_id};
pe.get_url_parameter=function(a,b){var c=RegExp("[\\?&]"+b+"=([^&]+)","i").exec(a);return c?c[1]:null};pe.hash_length=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};pe.hashes_equal=function(a,b){if(a===b)return!0;if(pe.hash_length(a)!=pe.hash_length(b))return!1;for(var c in a){var d=a[c],e=b[c];if(pe.is_array(d)){if(!pe.arrays_equal(d,e))return!1}else if(d!==e)return!1}return!0};
pe.hashes_match=function(a,b){for(var c in a){var d=a[c],e=b[c];if(pe.is_array(d)){if(!pe.array_contains(e,d))return!1}else if(d!==e)return!1}return!0};pe.https=function(a){return-1===window.location.href.indexOf("https://")?a:a.replace("http://","https://")};pe.inject=function(a,b,c){var d=b;$.each(a,function(a,b){d=c(d,b)});return d};
pe.init_widget=function(a,b){"string"!==typeof b&&(null!==b&&!b.length?alert("No container given."):(a.container=b,a.callback=function(a){for(var b=[a,this],e=1;e<arguments.length;e++)b.push(arguments[e]);return pe.bind_this.apply(this,b)},a.check_bind=function(a){if("undefined"===typeof this.container)throw"Incorrect scope binding"+a?" in: "+a:".";},a.bind_event=function(a,b){pe.assert(a,"bind_event: parameter 'event_type' is empty");this.container.bind(a,b)},a.fire_event=function(a,b){"undefined"===
typeof a&&alert("Must provide the event type to fire.");"undefined"===typeof b&&(b={});this.container.trigger(a,b)},a.show=function(){this.container.show()},a.hide=function(){this.container.hide()},a.toggle=function(a){this.container.toggle(a)},a.is_visible=function(){return this.container.is(":visible")}))};pe.install_easing=function(){jQuery.easing.cubicEaseInOut||(jQuery.easing.cubicEaseInOut=function(a,b,c,d){b=c+d;return 1>(a/=0.5)?b/2*a*a*a+c:b/2*((a-=2)*a*a+2)+c})};
pe.is_array=function(a){return!(!a||!("object"===typeof a&&"number"===typeof a.length&&"function"===typeof a.splice&&!a.propertyIsEnumerable("length")))};pe.is_valid_credit_card_number=function(a){return!!a.match(/^\d{4}(\s*|\s*\-\s*)?\d{4}(\s*|\s*\-\s*)?\d{4}(\s*|\s*\-\s*)?\d{4}$/)};pe.is_valid_date=function(a){return!a.match(/^(\d{1,2})(\/|-)(\d{1,2})(\/|-)(\d{4})$/)?!1:a!==$.datepicker.formatDate("m/d/yy",new Date(a))?a===$.datepicker.formatDate("mm/dd/yy",new Date(a)):!0};
pe.is_valid_zip_code=function(a){return!!a.match(/^\d{5}(\s*\-\s*\d{4})?$/)};pe.load=function(a){pe.assert(a,"error loading data");return a};pe.link_title_for_city=function(a){return"See the latest hotspots and events happening in "+a+"."};pe.link_title_for_city_party_climate=function(a){return"Check out the overview and photos of "+a+"."};
pe.link_title_for_event=function(a,b){return b?"Check out event details, photos and videos of "+a+" at "+b+".":"Check out event details, photos and videos of "+a+"."};pe.link_title_for_neighborhood=function(a,b){return"Check out "+a+" description, photos, and venues in "+b+"."};pe.link_title_for_performer=function(a){return"See the latest "+a+" schedule, photos, videos and news."};
pe.link_title_for_reviewer=function(a){switch(a){case "Lucas":return"Meet Lucas, the quintessential fun- loving, pub-crawling \u201cguy\u2019s guy\u201d. Learn about his personality and ratings.";case "Adriana":return"Meet Adriana, the epitome of a cosmopolitan girl. Learn about her personality and ratings.";case "Jonah":return"Meet Jonah, an affable, non-mainstream guy with natural curiosity about people and cultures. Learn about his personality and ratings.";case "Emma":return"Meet Emma, a lively, witty, and sociable \u201cgirl next door\u201d. Learn about her personality and ratings.";
case "All":return"Meet Lucas, Adriana, Jonah and Emma. Learn how their personalities can help you maximize your social experiences in your city and your travels."}};pe.link_title_for_venue=function(a,b,c){return c?"Check out the review, photos, videos, map and events schedule of "+a+" - "+c+" in "+b+".":"Check out the review, photos, videos, map and events schedule of "+a+" in "+b+"."};
pe.normalize=function(a){for(var b="",c=0,d=a.length;c<d;c++)var e=a.charAt(c),f=pe.accentMap[e],b=b+("undefined"===typeof f?e:f);return b};pe.object_hash_from_array=function(a){var b={};$.each(a,function(a,d){b[d.id]=d});return b};pe.object_length=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};pe.parse_price=function(a){return Math.ceil(100*parseFloat(a.substring(1)))};
pe.prepare_autocomplete_data=function(a){var b=[];$.each(a,function(a,d){$.each(d,function(d,f){f.category=a;b.push(f)})});return b};pe.remove_anchor_from_url=function(a){return a?a.split("#")[0]:""};pe.remove_query_string_from_url=function(a){return a?a.split("?")[0]:""};
pe.set_autocomplete_source=function(a,b,c){var d=pe.normalize(b.term).toLowerCase(),e=RegExp($.ui.autocomplete.escapeRegex(d),"i");a=$.grep(pe.prepare_autocomplete_data(a),function(a){a=a.label||a.value||a;return e.test(a)||e.test(pe.normalize(a))});a=_.sortBy(a,function(a){var b=a.label||a.value||a,b=pe.normalize(b).toLowerCase();return[a.category,b!=d,a.label]});c(a)};pe.shuffle_array=function(a){if(!a)return[];for(var b,c,d=a.length;d;)b=parseInt(Math.random()*d,10),c=a[--d],a[d]=a[b],a[b]=c;return a};
pe.string_padding_left=function(a,b,c){for(;a.length<b;)a=c+a;return a};pe.string_starts_with=function(a,b){return a.substr(0,b.length)===b};pe.string_ends_with=function(a,b){return a.substr(a.length-b.length)===b};pe.structured_tags_as_flat_array=function(a){var b=[];$.each(a,function(a,d){$.merge(b,d)});return b};pe.text_contains_query=function(a,b){var c=b.split(" "),d=!0;$.each(c,function(b,c){if(-1===a.indexOf(c))return d=!1,!0});return d};pe.today_date_string=function(){return pe.date_string(new Date)};
pe.truncate_by_words=function(a,b,c){if(!a||!b)return alert("Sorry, but an error happened. We are already warned about that.");c=c||"...";if(a.length<b)return a;a=a.slice(0,b-1);" "!==_.last(a)&&(b=a.lastIndexOf(" "),a=a.slice(0,b));return $.trim(a)+c};pe.value_from_cookie=function(a){return(a=document.cookie.match(RegExp("(^| )"+a+"=([^ ;]+)")))?a[2]:null};
pe.venue_search_text=function(a){var b=[a.name,a.description,a.address,a.hotspot_text,a.neighborhood_name];a.types&&$.each(a.types,function(a,d){b.push(d)});a.tags&&$.each(a.tags,function(a,d){b.push(d)});return b.join(" ")};pe.xor=function(a,b){return!!(a?!b:b)};$(document).ready(function(){$(document).ajaxSend(pe.ajax_send)});
pe.GigyaShare.initialize_share_bar=function(a,b){var c=$('meta[property="og:title"]').attr("content"),d=a.data("twitter-message"),e=pe.remove_anchor_from_url(window.location.href),f=new gigya.socialize.UserAction;f.setTitle(c);f.setLinkBack(e);f.setDescription($('meta[property="og:description"]').attr("content"));var h=$('meta[property="og:image"]').attr("content");h&&"http://www.partyearth.com/assets/facebook_50.jpg"!==h&&f.addMediaItem({type:"image",src:h.replace("s100.jpg","s660.jpg"),href:e});
h=new gigya.services.socialize.UserAction;h.setTitle(d);d=$.extend({userAction:f,twitterUserAction:h,shareButtons:[{provider:"facebook"},{provider:"facebook-like",font:"arial"},{provider:"twitter-tweet",defaultText:d,related:"PartyEarth"},{provider:"google-plusone"},{provider:"share",iconImgUp:"http://cdn.partyearth.com/images/social/gigya_share_icon.gif",iconImgOver:"http://cdn.partyearth.com/images/social/gigya_share_icon_hover.gif"}],shortURLs:"never",containerID:a.attr("id"),cid:"",dontSendEmail:!0,
onSendDone:function(a){pe.GigyaShare.share_gigya_email(a,c,e)}},b||{});gigya.socialize.showShareBarUI(d)};pe.GigyaShare.share_gigya_email=function(a,b,c){var d=$.map(a.recipients,function(a){return a.email}).join(", ");$.post("/api/share_link_by_email.json",{sender:a.sender,recipients:d,subject:b.split("|")[0],link:c,message:a.userMessage})};
pe.GigyaShare.initialize_simple_share=function(){var a=$("#SuperDiv");a.removeClass("hidden");pe.sdialog?pe.sdialog.dialog("open"):(pe.sdialog=a,a.dialog({modal:!0,resizable:!0,title:"Share",open:function(){}}));return!0};pe.init_mini_share_bars=function(){$(".DefaultShareBarView").live("mouseover",pe.default_share_view_hovered)};
pe.default_share_view_hovered=function(a){var b=$(a.target).closest(".ShareBarContainer");a=b.find(".ShareBarButtons");0<a.length&&!1===a.data("initialized")&&pe.initialize_share_bar_instance(a);b.find(".DefaultShareBarView").hide("slow",function(){b.find(".ActualShareBarView").show("slow")})};pe.initialize_share_bar_instance=function(){return!0};
pe.ChangeImageOnHover=function(a,b){pe.init_widget(this,a);this.image_container=this.container.find(".ImageContainer");this.link_parent_class=b||null;this.include_caption=this.container.data("include-caption")||!1;this.object_links=this.container.find(".HoverLinkToChange");this.object_links.mouseover(this.callback(this.object_link_hovered));var c=b?this.container.find("."+b):[];this.link_wrappers=0<c.length?c:this.object_links.parent()};
pe.ChangeImageOnHover.prototype.image_html=function(a){var b='<a href="{{object_url}}" title="{{link_title}}" class="thumbnail_link"><img src="{{image_url}}" alt="{{alt_tag}}"></a>';this.include_caption&&(b+='<p class="name"><span class="date">{{link_prefix}}</span><a href="{{object_url}}">{{image_caption}}</a></p>');a={object_url:a.attr("href"),image_url:a.data("image-url"),link_title:a.data("title")||"",alt_tag:a.data("image-alt-tag")||"",link_prefix:a.data("link-prefix")||"",image_caption:a.html()};
return pe.templatize(b,a)};pe.ChangeImageOnHover.instantiate_all=function(a){return $.map($(".ChangeImageOnHoverContainer"),function(b){return new pe.ChangeImageOnHover($(b),a)})};pe.ChangeImageOnHover.prototype.object_link_hovered=function(a){a=$(a.target);this.object_links.removeClass("selected");this.link_wrappers.removeClass("selected");a.addClass("selected");this.link_wrapper(a).addClass("selected");this.image_container.html(this.image_html(a));pe.convert_to_rounded_corners()};
pe.ChangeImageOnHover.prototype.link_wrapper=function(a){return this.link_parent_class?a.closest("."+this.link_parent_class):a.parent()};pe.PrefetcherModule=function(a){pe.init_widget(this,a);this.elements_with_prefetch_urls=this.container.find("[data-prefetch-url]");this.prefetch_data()};pe.PrefetcherModule.instantiate=function(){return new pe.PrefetcherModule($("body"))};pe.PrefetcherModule.prototype.is_image_url=function(a){return/\.(jpe?g|gif|png)(\?.*)?$/i.test(a)};
pe.PrefetcherModule.prototype.prefetch_ajax_request=function(a){$.getScript(a)};pe.PrefetcherModule.prototype.prefetch_data=function(){$.each(this.elements_with_prefetch_urls,this.callback(function(a,b){b=$(b);var c=b.data("prefetch-url");this.is_image_url(c)?this.prefetch_image(c):this.prefetch_ajax_request(c);b.removeAttr("data-prefetch-url")}))};pe.PrefetcherModule.prototype.prefetch_image=function(a){this.container.append(pe.templatize('<div style="display:none;"><img src="{{url}}"></div>',{url:a}))};
pe.ArticlesScenePage=function(a){pe.init_widget(this,a);this.per_page=this.container.data("per-page")||10;this.total_pages_loaded=1;this.has_more_pages_to_load=!0;this.loading=!1;this.local_toggler=$(this.container.data("local-toggler"));this.filter_selector=$(this.container.data("filter-selector"));this.filter=this.filter_selector.val();this.local_filters=this.container.data("local-filters");this.filters=this.container.data("filters");this.show_more_button=$(this.container.data("show-more-button"));
this.local_toggler.change(this.callback(this.reload));this.local_toggler.change(this.callback(this.reload_filters));this.show_more_button.click(this.callback(this.show_more));this.filter_selector.change(this.callback(this.on_filter_selected));this.reload_filters();$(window).scroll(this.callback(this.on_scroll));this.on_scroll()};pe.ArticlesScenePage.prototype.toggle_filters=function(a){this.filter_selector.html(a)};
pe.ArticlesScenePage.prototype.on_filter_selected=function(){this.filter=this.filter_selector.val();this.reload()};pe.ArticlesScenePage.prototype.reload_filters=function(){var a=this.local_toggler.is(":checked")?this.local_filters:this.filters;$(a).filter("[value="+this.filter_selector.val()+"]")||(this.filter_selector.val("date"),this.filter=this.filter_selector.val());this.toggle_filters(a);this.filter_selector.val(this.filter)};
pe.ArticlesScenePage.prototype.reload=function(){this.total_pages_loaded=1;this.has_more_pages_to_load=!0;this.reload_articles();this.on_scroll();pe.animated_scrolling(this.container,142)};pe.ArticlesScenePage.prototype.load_articles=function(a,b){var c=_.extend({per_page:this.per_page,page:this.total_pages_loaded,local_only:this.local_toggler.is(":checked"),filter:this.filter},b);this.loading=!0;$.get("/articles/lists.ehtml",c,this.callback(function(b){this.loading=!1;a(b)}))};
pe.ArticlesScenePage.prototype.reload_articles=function(){this.load_articles(this.callback(function(a){a=a.replace(/^\s+|\s+$/g,"");this.container.html(a);this.has_more_pages_to_load=$(a).filter(".article_item").length>=this.per_page;this.reinitialize_show_more_button()}))};
pe.ArticlesScenePage.prototype.show_more=function(){this.has_more_pages_to_load&&this.load_articles(this.callback(function(a){a=a.replace(/^\s+|\s+$/g,"");this.container.append(a);this.total_pages_loaded+=1;this.has_more_pages_to_load=$(a).filter(".article_item").length>=this.per_page;this.reinitialize_show_more_button()}),{page:this.total_pages_loaded+1})};pe.ArticlesScenePage.prototype.reinitialize_show_more_button=function(){this.show_more_button.toggleClass("hidden",!this.has_more_pages_to_load)};
pe.ArticlesScenePage.prototype.on_scroll=function(){this.loading||50>this.show_more_button.offset().top-$(window).scrollTop()-$(window).height()&&this.show_more()};
$(document).ready(function(){pe.install_easing();pe.scene=new pe.ArticlesScenePage($(".ArticlesContainer"));pe.ChangeImageOnHover.instantiate_all("LinkWrapper");pe.init_mini_share_bars();setTimeout(function(){pe.init_page_framework(function(){setTimeout(function(){$(".StickyBar").sticky({topSpacing:10,bottomSpacing:$("#footer").outerHeight()});pe.PrefetcherModule.instantiate()},10)})},10)});
