pe.json_expander={};pe.json_expander.CLOUD_FRONT_HOST="http://cdn.partyearth.com/";
pe.json_expander.expand_autocomplete_data=function(a){var b={};a.pe_reviewers&&(b["pe-reviewers"]=pe.json_expander.expand_autocomplete_records(a.pe_reviewers));a.cities&&(b.cities=pe.json_expander.expand_autocomplete_records(a.cities));a.events&&(b.events=pe.json_expander.expand_autocomplete_records(a.events));a.neighborhoods&&(b.neighborhoods=pe.json_expander.expand_autocomplete_records(a.neighborhoods));a.performers&&(b.performers=pe.json_expander.expand_autocomplete_records(a.performers));a.tags&&
(b.tags=pe.json_expander.expand_autocomplete_records(a.tags));a.venue_types&&(b.venue_types=pe.json_expander.expand_autocomplete_records(a.venue_types));a.venues&&(b.venues=pe.json_expander.expand_autocomplete_records(a.venues));a.pages&&(b.pages=pe.json_expander.expand_autocomplete_records(a.pages));a.crowds&&(b.crowds=pe.json_expander.expand_autocomplete_records(a.crowds));a.dresses&&(b.dresses=pe.json_expander.expand_autocomplete_records(a.dresses));a.entertainments&&(b.entertainments=pe.json_expander.expand_autocomplete_records(a.entertainments));
a.food_drinks&&(b.food_drinks=pe.json_expander.expand_autocomplete_records(a.food_drinks));a["layout_d\u00e9cors"]&&(b["layout_d\u00e9cors"]=pe.json_expander.expand_autocomplete_records(a["layout_d\u00e9cors"]));a.musics&&(b.musics=pe.json_expander.expand_autocomplete_records(a.musics));a.performers&&(b.performers=pe.json_expander.expand_autocomplete_records(a.performers));a.prices&&(b.prices=pe.json_expander.expand_autocomplete_records(a.prices));a.seasonals&&(b.seasonals=pe.json_expander.expand_autocomplete_records(a.seasonals));
a.vibes&&(b.vibes=pe.json_expander.expand_autocomplete_records(a.vibes));return b};pe.json_expander.expand_autocomplete_records=function(a){return $.map(a,function(a){return{value:a.v,label:a.l}})};pe.json_expander.expand_billboard_photos=function(a){return $.map(a,function(a){return{src:pe.json_expander.CLOUD_FRONT_HOST+a.s,title:a.t,url:a.u}})};pe.json_expander.expand_cities=function(a){return $.map(a,function(a){return pe.json_expander.expand_city(a)})};
pe.json_expander.expand_city=function(a){return{id:a.i,name:a.n,description:a.d,latitude:a.lt,longitude:a.lg,default_zoom_level:a.z}};
pe.json_expander.expand_event=function(a){return{category:a.ct,city_id:a.c,city_name:a.cn,description:a.d,id:a.i,is_parent_event:a.u,is_recurring_event:a.r,locations:$.map(a.l,function(a){var c={name:a.n,url:a.u,id:a.i,address:a.a};a.lt&&(c.latitude=a.lt);a.lg&&(c.longitude=a.lg);a.p&&(c.photo=pe.json_expander.CLOUD_FRONT_HOST+a.p);return c}),name:a.n,neighborhood_id:a.h,neighborhood_name:a.hn,performer_label:a.pl,performers:$.map(a.ps,function(a){return{name:a.n,id:a.i}}),start_date:a.dt,start_time:a.ti,
thumbnail:a.p?pe.json_expander.CLOUD_FRONT_HOST+a.p:null,tags:a.t}};pe.json_expander.expand_events=function(a){return $.map(a,function(a){return pe.json_expander.expand_event(a)})};pe.json_expander.expand_landmarks=function(a){return $.map(a,function(a){return{city_id:a.c,default_zoom_level:a.z,description:a.d,id:a.i,latitude:a.lt,longitude:a.lg,name:a.n,thumbnail:a.p?pe.json_expander.CLOUD_FRONT_HOST+a.p:null,time:a.t,type:a.k}})};
pe.json_expander.expand_neighborhoods=function(a){return $.map(a,function(a){return{id:a.i,name:a.n,city_id:a.c,latitude:a.lt,longitude:a.lg,is_visible:a.v,default_zoom_level:a.z}})};
pe.json_expander.expand_performer=function(a){var b={id:a.i,name:a.n,performer_type:1==a.pt?"Performer":"Team",has_events:a.he,description:a.d,city_id:a.c,city_name:a.cn,neighborhood_id:a.h,neighborhood_name:a.hn,thumbnail:a.p?pe.json_expander.CLOUD_FRONT_HOST+a.p:null,tags:a.t,category:a.ct};a.l&&(b.locations=$.map(a.l,function(a){var b={name:a.n,id:a.i,address:a.a};a.lt&&(b.latitude=a.lt);a.lg&&(b.longitude=a.lg);a.p&&(b.photo=pe.json_expander.CLOUD_FRONT_HOST+a.p);return b}));return b};
pe.json_expander.expand_venue=function(a){a={id:a.i,name:a.n,description:a.d,latitude:a.lt,longitude:a.lg,neighborhood_id:a.h,neighborhood_name:a.hn,neighborhood_is_visible:a.hv,address:a.a,city_id:a.c,city_name:a.cn,primary_endpoint:a.pe,rating_lucas:a.rL,rating_adriana:a.rA,rating_jonah:a.rJ,rating_emma:a.rE,venue_types:a.vT,venue_types_with_categories:a.vTC,all_venue_types:a.pT,tags:a.t,hotspot_days:a.hs,hotspot_text:pe.json_expander.format_days_text(a.hs),day_spot:a.ds,night_spot:a.ns,default_zoom_level:a.z,
thumbnail:a.p?pe.json_expander.CLOUD_FRONT_HOST+a.p:null,phone:a.pN,is_visible:a.iv};a.url="/"+a.city_id+"/"+a.primary_endpoint+"/"+a.id+"-2/";a.map_icon="VENUE";a.all_venue_types=pe.array_merge(a.all_venue_types||[],a.venue_types);return a};pe.json_expander.expand_venues=function(a){return $.map(a,function(a){return pe.json_expander.expand_venue(a)})};
pe.json_expander.format_days_text=function(a){if(void 0===a)return"";0===a[0]&&(a.shift(),a.push(0));a=$.map(a,function(a){return pe.days_of_week[a]});switch(a.length){case 0:return"";case 1:return a[0];case 2:return a[0]+" and "+a[1];default:return a.slice(0,a.length-1).join(", ")+", and "+a[a.length-1]}};
