pe.Validator=function(a){this.message=a.message||"Invalid value.";this.callback=a.callback;this.unless_callback=a.unless||function(){return!1};this.options=a;this.value=a.value?a.value:function(b){return a.callback(b)}};pe.Validator.prototype.passed=function(a){return!!this.callback($(a))};pe.Validator.prototype.failed=function(a){return!this.passed(a)};pe.Validator.prototype.unless=function(){return this.unless_callback()};
pe.validation.not_blank_validator=new pe.Validator({callback:function(a){return"checkbox"==a.attr("type")?$(a).is(":checked"):!_.isEmpty($.trim(a.val()))},message:"Required."});
(function(){pe.validation.dob_validator=new pe.Validator({message:"Please enter valid date.",callback:function(a){var b,c,d,f,e;b=_.map($(a).find("select"),function(a){return $(a).val()});e=b[2];a=b[0];d=b[1];if(!e||!a||!d)return!1;c=new Date(""+a+"/"+d+"/"+e);f=c.getMonth()+1+"";b=c.getDate()+"";c=c.getFullYear()+"";return f===a&&b===d&&c===e}})}).call(this);(function(){pe.validation.check_group_validator=new pe.Validator({message:"Please select something.",callback:function(a){return 0<a.find("input:checked").length}})}).call(this);
pe.ValidatableForm=function(a,b,c,d){pe.init_widget(this,a);this.bindings=c||{};this.chained_fields=[];this.errors={};this.rules=b||{};_.each(a.find(".input[data-required=true], select[data-required=true], input[data-required=true], textarea[data-required=true]"),this.callback(function(a){a=$(a);var b="#"+a.attr("id"),c=a.data("validator");this.rules[b]=c?eval(c):pe.validation.not_blank_validator;(c=a.data("binding"))?this.bindings[b]=c:"text"==a.attr("type")||"textarea"==a.attr("tagName")?this.bindings[b]=
"blur":this.rules[b]==pe.validation.dob_validator?a.find("select").each(this.callback(function(a,c){$(c).change(this.callback(function(){this.validate_field(b)}))})):this.bindings[b]="change"}));this.save_button=this.container.find(".SaveButton");this.submit_button=this.container.find(".SubmitButton");this.after_submit=d;this.init_bindings();this.validate();this.toggle_submit();this.submit_button.click(this.callback(this.on_submit))};
pe.ValidatableForm.prototype.init_bindings=function(){this.container.find("input, textarea, select").change(this.callback(function(){this.save_button.removeClass("disabled").removeAttr("disabled")}));_.each(this.bindings,function(a,b){"string"===typeof a?$(b).bind(a,this.callback(function(){this.validate_field(b)})):"function"===typeof a&&this.callback(a)();this.rules[b].value($(b))&&this.validate_field(b)},this)};
pe.ValidatableForm.prototype.on_submit=function(){var a=this.validate();this.highlight_first_failed();a&&this.after_submit&&this.after_submit();return a};pe.ValidatableForm.prototype.delete_error=function(a){delete this.errors[a];_.each(this.chained_fields,function(b){_.include(b,a)&&_.each(b,function(a){this.errors[a]&&this.delete_error(a)},this)},this)};
pe.ValidatableForm.prototype.focus_on_failed=function(){if(!this.valid())return pe.install_easing(),pe.animated_scrolling($(".inline-errors:first").parents("li"),2),!1};pe.ValidatableForm.prototype.highlight_first_failed=function(){if(!this.validate()){if(!this.validation_shown()){var a=_.keys(this.errors)[0];this.render_field_error(a)}this.focus_on_failed()}};pe.ValidatableForm.prototype.render_errors=function(){_.each(this.errors,function(a,b){this.render_field_error(b)},this)};
pe.ValidatableForm.prototype.render_field_error=function(a){var b=$(a).parents("li.input:first");0===b.length&&(b=$(a));b.find(".inline-errors").remove();b.append('<span class="inline-errors">'+this.errors[a]+"</span>");b.find(".inline-success").remove()};pe.ValidatableForm.prototype.render_field_success=function(a){var b=$(a).parents("li.input:first");0===b.length&&(b=$(a));b.find(".inline-success").remove();b.append('<img class="inline-success" src="/assets/users/check.png" />');b.find(".inline-errors").remove()};
pe.ValidatableForm.prototype.render_success=function(){_.each(this.valid_fields(),function(a){this.render_field_success(a)},this)};pe.ValidatableForm.prototype.toggle_submit=function(){this.valid()?this.submit_button.removeClass("disabled").removeAttr("disabled"):this.submit_button.addClass("disabled")};pe.ValidatableForm.prototype.valid_fields=function(){return _.difference(_.keys(this.rules),_.keys(this.errors))};
pe.ValidatableForm.prototype.validate_field=function(a){var b=this.rules[a],c=b.passed(a);b.unless()?this.delete_error(a):c?(this.delete_error(a),this.render_field_success(a)):(this.errors[a]=$(a).data("message")||b.message,this.render_field_error(a));this.toggle_submit();return c};pe.ValidatableForm.prototype.valid=function(){return _.isEmpty(this.errors)};
pe.ValidatableForm.prototype.validate=function(){_.each(this.rules,function(a,b){a.failed(b)?this.errors[b]=$(b).data("message")||a.message:delete this.errors[b]},this);return this.valid()};pe.ValidatableForm.prototype.validate_together=function(){this.chained_fields.push(arguments)};pe.ValidatableForm.prototype.validation_shown=function(){return 0<this.container.find(".inline-errors").length};
(function(){$(function(){pe.form_container=$("form.PayInfo");$(".PaymentSelector").change(pe.payment_type_changed);pe.initialize_active_form_validation();return pe.init_page_framework()});pe.initialize_active_form_validation=function(){var a,b,c;a=$(".PaymentType[data-type='"+$(".PaymentSelector:checked").val()+"']");a.show();c={};b={};_.each(a.find(".RequiredInput"),function(a){a=$(a);c["#"+a.attr("id")]=pe.validation.not_blank_validator;return b["#"+a.attr("id")]=a.data("validate")});return window.x=
new pe.ValidatableForm(pe.form_container,c,b)};pe.payment_type_changed=function(){$(".PaymentType").hide();pe.form_container.find(".inline-errors").remove();pe.form_container.find(".SubmitButton").removeClass("disabled").unbind("click");return pe.initialize_active_form_validation()}}).call(this);
