pe.Floater=function(c,d,a){pe.init_widget(this,c);this.bottom_margin=a||0;this.start_point_div=c.find(".FloatingAreaStart");this.end_point_div=d||null;this.stop_at=this.start_from=0;this.sticked=this.is_floating=!1;this.floater=this.container.find(".Floater");this.offset=0;this.disabled=!1;this.top=parseInt(this.floater.css("margin-top"),10)||0;$(window).scroll(this.callback(this.scrolling));this.set_floating_area();pe.Floater.register_floater(this)};
pe.Floater.events={TOP_REACHED:"Floater_TOP_REACHED",FLOATING:"Floater_FLOATING",BOTTOM_REACHED:"Floater_BOTTOM_REACHED"};pe.Floater.prototype.set_floating_area=function(){this.start_from=this.start_point_div.offset().top;this.end_point_div&&(this.stop_at=this.end_point_div.offset().top)};
pe.Floater.prototype.scrolling=function(){if(!this.disabled){this.set_floating_area();var c=$(window).scrollTop(),d=c+this.offset+this.bottom_margin<=this.start_from,a=c+this.offset+this.bottom_margin>this.start_from,b=this.floater.position().top+this.floater.outerHeight(!0)>this.stop_at;!this.is_floating&&a&&!b&&!this.sticked?(this.start_floating(),this.fire_event(pe.Floater.events.FLOATING,this),pe.fire_global_event(pe.Floater.events.FLOATING,this)):this.is_floating&&d?(this.stop_scrolling(),this.fire_event(pe.Floater.events.TOP_REACHED,
this)):this.end_point_div&&(!this.sticked&&b?(this.stick(),this.fire_event(pe.Floater.events.BOTTOM_REACHED,this)):this.sticked&&c+this.floater.outerHeight(!0)<=this.stop_at&&this.unstick())}};pe.Floater.prototype.start_floating=function(){this.floater.addClass("fixed");this.floater.removeClass("bottom");this.is_floating=!0;this.sticked=!1;this.set_offset()};
pe.Floater.prototype.stick=function(){this.floater.css("top",this.end_point_div.position().top-this.floater.outerHeight(!0)+"px");this.floater.removeClass("fixed");this.floater.css("position","absolute");this.is_floating=!1;this.sticked=!0};pe.Floater.prototype.disable=function(){this.floater.css("top",this.floater.position().top-140+"px");this.floater.removeClass("fixed");this.floater.css("position","absolute");this.is_floating=!1;this.disabled=this.sticked=!0};
pe.Floater.prototype.enable=function(){this.disabled=!1};pe.Floater.prototype.unstick=function(){this.floater.css("margin-top","");this.floater.css("top","");this.floater.css("position","");this.start_floating();this.fire_event(pe.Floater.events.FLOATING,this)};pe.Floater.prototype.stop_scrolling=function(){this.floater.css("margin-top","");this.floater.removeClass("fixed");this.floater.removeClass("bottom");this.sticked=this.is_floating=!1;this.set_offset()};
pe.Floater.prototype.set_offset=function(c){c&&(this.offset=c);0!==this.offset&&this.is_floating?this.floater.css("margin-top",this.top+this.offset+"px"):this.floater.css("margin-top","")};pe.Floater.registered_floaters=[];pe.Floater.register_floater=function(c){pe.Floater.registered_floaters.push(c);pe.Floater.update_positions()};
pe.Floater.update_positions=function(){pe.Floater.registered_floaters=_.sortBy(pe.Floater.registered_floaters,function(a){return a.container.offset().top},null);if(pe.Floater.registered_floaters[0]&&(pe.Floater.registered_floaters[0].offset=0,1<pe.Floater.registered_floaters.length))for(var c=1;c<pe.Floater.registered_floaters.length;c++){var d=pe.Floater.registered_floaters[c-1].offset+pe.Floater.registered_floaters[c-1].floater.outerHeight();pe.Floater.registered_floaters[c].offset=d;pe.Floater.registered_floaters[c].is_floating&&
pe.Floater.registered_floaters[c].start_floating();pe.Floater.registered_floaters[c].set_floating_area()}};
(function(c){var d;c.rails=d={linkClickSelector:"a[data-confirm], a[data-method], a[data-remote]",formSubmitSelector:"form",formInputClickSelector:"form input[type=submit], form input[type=image], form button[type=submit], form button:not([type])",disableSelector:"input[data-disable-with], button[data-disable-with], textarea[data-disable-with]",enableSelector:"input[data-disable-with]:disabled, button[data-disable-with]:disabled, textarea[data-disable-with]:disabled",requiredInputSelector:"input[name][required],textarea[name][required]",
fileInputSelector:"input:file",CSRFProtection:function(a){var b=c('meta[name="csrf-token"]').attr("content");b&&a.setRequestHeader("X-CSRF-Token",b)},fire:function(a,b,d){b=c.Event(b);a.trigger(b,d);return!1!==b.result},confirm:function(a){return confirm(a)},ajax:function(a){return c.ajax(a)},handleRemote:function(a){var b,g,e,f=a.data("type")||c.ajaxSettings&&c.ajaxSettings.dataType;if(d.fire(a,"ajax:before")){if(a.is("form")){b=a.attr("method");g=a.attr("action");e=a.serializeArray();var h=a.data("ujs:submit-button");
h&&(e.push(h),a.data("ujs:submit-button",null))}else b=a.data("method"),g=a.attr("href"),e=null;d.ajax({url:g,type:b||"GET",data:e,dataType:f,beforeSend:function(b,c){void 0===c.dataType&&b.setRequestHeader("accept","*/*;q=0.5, "+c.accepts.script);return d.fire(a,"ajax:beforeSend",[b,c])},success:function(b,c,d){a.trigger("ajax:success",[b,c,d])},complete:function(b,c){a.trigger("ajax:complete",[b,c])},error:function(b,c,d){a.trigger("ajax:error",[b,c,d])}})}},handleMethod:function(a){var b=a.attr("href"),
d=a.data("method"),a=c("meta[name=csrf-token]").attr("content"),e=c("meta[name=csrf-param]").attr("content"),b=c('<form method="post" action="'+b+'"></form>'),d='<input name="_method" value="'+d+'" type="hidden" />';void 0!==e&&void 0!==a&&(d+='<input name="'+e+'" value="'+a+'" type="hidden" />');b.hide().append(d).appendTo("body");b.submit()},disableFormElements:function(a){a.find(d.disableSelector).each(function(){var b=c(this),a=b.is("button")?"html":"val";b.data("ujs:enable-with",b[a]());b[a](b.data("disable-with"));
b.attr("disabled","disabled")})},enableFormElements:function(a){a.find(d.enableSelector).each(function(){var b=c(this),a=b.is("button")?"html":"val";if(b.data("ujs:enable-with"))b[a](b.data("ujs:enable-with"));b.removeAttr("disabled")})},allowAction:function(a){var b=a.data("confirm"),c=!1,e;if(!b)return!0;d.fire(a,"confirm")&&(c=d.confirm(b),e=d.fire(a,"confirm:complete",[c]));return c&&e},blankInputs:function(a,b,d){var e=c(),f;a.find(b||"input,textarea").each(function(){f=c(this);if(d?f.val():
!f.val())e=e.add(f)});return e.length?e:!1},nonBlankInputs:function(a,b){return d.blankInputs(a,b,!0)},stopEverything:function(a){a.stopImmediatePropagation();return!1},callFormSubmitBindings:function(a){var a=a.data("events"),b=!0;void 0!==a&&void 0!==a.submit&&c.each(a.submit,function(a,c){if("function"===typeof c.handler)return b=c.handler(c.data)});return b}};"ajaxPrefilter"in c?c.ajaxPrefilter(function(a,b,c){d.CSRFProtection(c)}):c(document).ajaxSend(function(a,b){d.CSRFProtection(b)});c(d.linkClickSelector).live("click.rails",
function(a){var b=c(this);if(!d.allowAction(b))return d.stopEverything(a);if(void 0!==b.data("remote"))return d.handleRemote(b),!1;if(b.data("method"))return d.handleMethod(b),!1});c(d.formSubmitSelector).live("submit.rails",function(a){var b=c(this),g=void 0!==b.data("remote"),e=d.blankInputs(b,d.requiredInputSelector),f=d.nonBlankInputs(b,d.fileInputSelector);if(!d.allowAction(b))return d.stopEverything(a);if(e&&d.fire(b,"ajax:aborted:required",[e]))return!g;if(g){if(f)return d.fire(b,"ajax:aborted:file",
[f]);if(!c.support.submitBubbles&&!1===d.callFormSubmitBindings(b))return d.stopEverything(a);d.handleRemote(b);return!1}setTimeout(function(){d.disableFormElements(b)},13)});c(d.formInputClickSelector).live("click.rails",function(a){var b=c(this);if(!d.allowAction(b))return d.stopEverything(a);a=(a=b.attr("name"))?{name:a,value:b.val()}:null;b.closest("form").data("ujs:submit-button",a)});c(d.formSubmitSelector).live("ajax:beforeSend.rails",function(a){this==a.target&&d.disableFormElements(c(this))});
c(d.formSubmitSelector).live("ajax:complete.rails",function(a){this==a.target&&d.enableFormElements(c(this))})})(jQuery);
