pe.accentMap={"&":"and","\u00e0":"a","\u00e1":"a","\u00e2":"a","\u00e3":"a","\u00e4":"a","\u00e5":"a","\u00e7":"c","\u00c0":"a","\u00c1":"a","\u00e8":"e","\u00e9":"e","\u00ea":"e","\u00eb":"e","\u00c8":"e","\u00c9":"e","\u00ec":"i","\u00f1":"n","\u00ed":"i","\u00ee":"i","\u00ef":"i","\u00f2":"o","\u00f3":"o","\u00f4":"o","\u00f5":"o","\u00f6":"o","\u00f9":"u","\u00fa":"u","\u00fb":"u","\u00fc":"u","!":"i",$:"s","-":""," ":"","'":"","\u2019":"",".":""};pe.ajax_error=function(){alert("The request failed. Please try again later.")};
pe.ajax_send=function(a,b){var c=$("meta[name='csrf-token']").attr("content");b.setRequestHeader("X-CSRF-Token",c)};pe.alert=function(a){alert(a)};pe.animated_scrolling=function(a,b){if(0!==a.length){var c=a.offset().top-(b||25);$("html,body").stop().animate({scrollTop:c+"px"},800,"cubicEaseInOut",function(){return!1})}};pe.scrolling=function(a,b){if(0!==a.length){var c=a.offset().top-(b||25);$("html,body").scrollTop(c)}};pe.days_of_week="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" ");
pe.array_contains=function(a,b){return _.isArray(b)?0===_.difference(b,a).length:-1<_.indexOf(a,b)};pe.arrays_equal=function(a,b){if(!a&&!b||!a&&0===b.length||0===a.length&&!b)return!0;if(a.length!=b.length)return!1;for(var c=a.sort(),d=b.sort(),e=0,f=a.length;e<f;e++)if(c[e]!==d[e])return!1;return!0};pe.array_match=function(a,b){var c=!1;$.each(a,function(a,e){if(-1<b.indexOf(e))return c=!0,!1});return c};pe.array_merge=function(a,b){var c=a.concat(b);c.sort();return c};
pe.array_remove=function(a,b){return!a?a:pe.is_array(b)?$.grep(a,function(a){return-1===b.indexOf(a)}):$.grep(a,function(a){return a!==b})};pe.assign_photo_size=function(a,b,c){return!a?"/assets/no_image_"+c+".png":"original"===b?a.replace("xxx.jpg",b+".jpg"):a.replace("xxx.jpg","s"+b+".jpg")};pe.remove_timestamp_from_asset_url=function(a){return a.split("?")[0]};pe.browser_is_ie8=function(){return $.browser.msie&&"8.0"===$.browser.version};
pe.build_dob_field_name=function(a,b,c){return[a||"user","[",b?b+"_":"","dob(",c,"i)]"].join("")};pe.capitalise_first_letter=function(a){return null===a?"":a.charAt(0).toUpperCase()+a.slice(1)};pe.classes_starting_with=function(a,b){return $.map(a.attr("class").split(/\s+/),function(a){if(pe.string_starts_with(a,b))return a})};pe.compare=function(a,b){return pe.is_array(a)&&pe.is_array(b)?pe.arrays_equal(a,b):a===b};
pe.convert_to_rounded_corners=function(a){a=a||$(".ConvertToRoundedCorners");a.each(function(a,c){var d=$(c);d.removeClass("ConvertToRoundedCorners");d.addClass("rounded_corner_wrapper");$('<div class="rounded_corner top_left"></div>').appendTo(d);$('<div class="rounded_corner top_right"></div>').appendTo(d);$('<div class="rounded_corner bottom_left"></div>').appendTo(d);$('<div class="rounded_corner bottom_right"></div>').appendTo(d)});return a};
pe.convert_to_tabbed_pod=function(a,b){return $.map(a,function(a){a=$(a);if(!a.hasClass("ConvertToTabbedPod"))return alert("format_tabbed_pod: element to convert must have class ConvertToTabbedPod. It only has "+a[0].className);var d=a.children("ul");d.addClass("tab");d.children("li").each(function(a,b){b=$(b);var c=b.html();b.html(pe.templatize('<div class="left_end pod_sprite float_left"></div>{{content}}<div class="right_end pod_sprite float_left"></div>',{content:c}))});var e=d.html();d.remove();
var d=a.html(),f=pe.classes_starting_with(a,"width");if(0===f.length)return alert("no width class found");if(1<f.length)return alert("more than 1 width class found");var g=f[0].substr(5);a.addClass("tabs");a.removeClass("ConvertToTabs");a.removeClass(f[0]);a.html(pe.templatize('<div><table class="width{{width}}" cellpadding="0" cellspacing="0"><tbody><tr><td class="header" colspan="4"><div class="header_row"><ul class="tab">{{headers}}</ul><div class="mid_section"></div><div class="right_corner pod_sprite"></div></div></td></tr><tr class="content_container"><td class="left_side pod_sides"></td><td class="content">{{content}}</td><td class="right_side pod_sides"></td></tr><tr class="footer_row"><td class="left_corner pod_sprite"></td><td class="mid_section"></td><td class="right_corner pod_sprite"></td></tr></tbody></table></div>',
{width:g,headers:e,content:d}));var e=a.children().tabs(b),h=["first","second","third","fourth"];a.find("ul.tab li").each(function(a,b){$(b).addClass(h[a])});return e})};
pe.new_convert_to_tabbed_pod=function(a,b){return $.map(a,function(a){a=$(a);if(!a.hasClass("ConvertToTabbedPod"))return alert("format_tabbed_pod: element to convert must have class ConvertToTabbedPod. It only has "+a[0].className);var d=a.children("ul"),e=d.html();d.remove();var d=a.html(),f=pe.classes_starting_with(a,"width");if(0===f.length)return alert("no width class found");if(1<f.length)return alert("more than 1 width class found");var g=f[0].substr(5);a.addClass("tabs");a.removeClass("ConvertToTabs");
a.removeClass(f[0]);a.html(pe.templatize('<div class="width{{width}}"><ul class="tab">{{headers}}</ul>{{content}}</div>',{width:g,headers:e,content:d}));var e=a.children().tabs(b),h=["first","second","third","fourth"];a.find("ul.tab li").each(function(a,b){$(b).addClass(h[a])});return e})};pe.date_string=function(a){return"string"===typeof a?a:a.getMonth()+1+"/"+a.getDate()+"/"+a.getFullYear()};
pe.days_between_dates=function(a,b){var c="string"===typeof a?Date.parse(a):a,d="string"===typeof b?Date.parse(b):b;return Math.abs(Math.floor((c-d)/864E5))};pe.empty=function(){};pe.event_search_text=function(a){var b=[a.name,a.description,a.location_name,a.category,a.neighborhood_name,a.neighborhood_id];a.tags&&$.each(a.tags,function(a,d){b.push(d)});a.performer_names&&$.each(a.performer_names,function(a,d){b.push(d)});return b.join(" ")};pe.fetch_photo_id_from_url=function(a){return a.split("/photos/")[1]};
pe.fix_ie7_rendering_bug=function(){$(".ConvertToTabbedPod").addClass("IeSucks")};pe.format_date=function(a){return a.getMonth()+1+"/"+a.getDate()+"/"+a.getFullYear()};pe.format_price=function(a){var b=Math.floor(a/100).toString();a=(a%100).toString();2>a.length&&(a="0"+a);return"$"+b+"."+a};pe.format_duration=function(a,b){if(!a)return"0:00";var c=Math.floor(a%60);return pe.string_padding_left(Math.floor(a/60).toString(),b||1,"0")+":"+pe.string_padding_left(c.toString(),2,"0")};pe.get_city_id=function(){return window.city_id};
pe.get_url_parameter=function(a,b){var c=RegExp("[\\?&]"+b+"=([^&]+)","i").exec(a);return c?c[1]:null};pe.hash_length=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};pe.hashes_equal=function(a,b){if(a===b)return!0;if(pe.hash_length(a)!=pe.hash_length(b))return!1;for(var c in a){var d=a[c],e=b[c];if(pe.is_array(d)){if(!pe.arrays_equal(d,e))return!1}else if(d!==e)return!1}return!0};
pe.hashes_match=function(a,b){for(var c in a){var d=a[c],e=b[c];if(pe.is_array(d)){if(!pe.array_contains(e,d))return!1}else if(d!==e)return!1}return!0};pe.https=function(a){return-1===window.location.href.indexOf("https://")?a:a.replace("http://","https://")};pe.inject=function(a,b,c){var d=b;$.each(a,function(a,b){d=c(d,b)});return d};
pe.init_widget=function(a,b){"string"!==typeof b&&(null!==b&&!b.length?alert("No container given."):(a.container=b,a.callback=function(a){for(var b=[a,this],e=1;e<arguments.length;e++)b.push(arguments[e]);return pe.bind_this.apply(this,b)},a.check_bind=function(a){if("undefined"===typeof this.container)throw"Incorrect scope binding"+a?" in: "+a:".";},a.bind_event=function(a,b){pe.assert(a,"bind_event: parameter 'event_type' is empty");this.container.bind(a,b)},a.fire_event=function(a,b){"undefined"===
typeof a&&alert("Must provide the event type to fire.");"undefined"===typeof b&&(b={});this.container.trigger(a,b)},a.show=function(){this.container.show()},a.hide=function(){this.container.hide()},a.toggle=function(a){this.container.toggle(a)},a.is_visible=function(){return this.container.is(":visible")}))};pe.install_easing=function(){jQuery.easing.cubicEaseInOut||(jQuery.easing.cubicEaseInOut=function(a,b,c,d){b=c+d;return 1>(a/=0.5)?b/2*a*a*a+c:b/2*((a-=2)*a*a+2)+c})};
pe.is_array=function(a){return!(!a||!("object"===typeof a&&"number"===typeof a.length&&"function"===typeof a.splice&&!a.propertyIsEnumerable("length")))};pe.is_valid_credit_card_number=function(a){return!!a.match(/^\d{4}(\s*|\s*\-\s*)?\d{4}(\s*|\s*\-\s*)?\d{4}(\s*|\s*\-\s*)?\d{4}$/)};pe.is_valid_date=function(a){return!a.match(/^(\d{1,2})(\/|-)(\d{1,2})(\/|-)(\d{4})$/)?!1:a!==$.datepicker.formatDate("m/d/yy",new Date(a))?a===$.datepicker.formatDate("mm/dd/yy",new Date(a)):!0};
pe.is_valid_zip_code=function(a){return!!a.match(/^\d{5}(\s*\-\s*\d{4})?$/)};pe.load=function(a){pe.assert(a,"error loading data");return a};pe.link_title_for_city=function(a){return"See the latest hotspots and events happening in "+a+"."};pe.link_title_for_city_party_climate=function(a){return"Check out the overview and photos of "+a+"."};
pe.link_title_for_event=function(a,b){return b?"Check out event details, photos and videos of "+a+" at "+b+".":"Check out event details, photos and videos of "+a+"."};pe.link_title_for_neighborhood=function(a,b){return"Check out "+a+" description, photos, and venues in "+b+"."};pe.link_title_for_performer=function(a){return"See the latest "+a+" schedule, photos, videos and news."};
pe.link_title_for_reviewer=function(a){switch(a){case "Lucas":return"Meet Lucas, the quintessential fun- loving, pub-crawling \u201cguy\u2019s guy\u201d. Learn about his personality and ratings.";case "Adriana":return"Meet Adriana, the epitome of a cosmopolitan girl. Learn about her personality and ratings.";case "Jonah":return"Meet Jonah, an affable, non-mainstream guy with natural curiosity about people and cultures. Learn about his personality and ratings.";case "Emma":return"Meet Emma, a lively, witty, and sociable \u201cgirl next door\u201d. Learn about her personality and ratings.";
case "All":return"Meet Lucas, Adriana, Jonah and Emma. Learn how their personalities can help you maximize your social experiences in your city and your travels."}};pe.link_title_for_venue=function(a,b,c){return c?"Check out the review, photos, videos, map and events schedule of "+a+" - "+c+" in "+b+".":"Check out the review, photos, videos, map and events schedule of "+a+" in "+b+"."};
pe.normalize=function(a){for(var b="",c=0,d=a.length;c<d;c++)var e=a.charAt(c),f=pe.accentMap[e],b=b+("undefined"===typeof f?e:f);return b};pe.object_hash_from_array=function(a){var b={};$.each(a,function(a,d){b[d.id]=d});return b};pe.object_length=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};pe.parse_price=function(a){return Math.ceil(100*parseFloat(a.substring(1)))};
pe.prepare_autocomplete_data=function(a){var b=[];$.each(a,function(a,d){$.each(d,function(d,f){f.category=a;b.push(f)})});return b};pe.remove_anchor_from_url=function(a){return a?a.split("#")[0]:""};pe.remove_query_string_from_url=function(a){return a?a.split("?")[0]:""};
pe.set_autocomplete_source=function(a,b,c){var d=pe.normalize(b.term).toLowerCase(),e=RegExp($.ui.autocomplete.escapeRegex(d),"i");a=$.grep(pe.prepare_autocomplete_data(a),function(a){a=a.label||a.value||a;return e.test(a)||e.test(pe.normalize(a))});a=_.sortBy(a,function(a){var b=a.label||a.value||a,b=pe.normalize(b).toLowerCase();return[a.category,b!=d,a.label]});c(a)};pe.shuffle_array=function(a){if(!a)return[];for(var b,c,d=a.length;d;)b=parseInt(Math.random()*d,10),c=a[--d],a[d]=a[b],a[b]=c;return a};
pe.string_padding_left=function(a,b,c){for(;a.length<b;)a=c+a;return a};pe.string_starts_with=function(a,b){return a.substr(0,b.length)===b};pe.string_ends_with=function(a,b){return a.substr(a.length-b.length)===b};pe.structured_tags_as_flat_array=function(a){var b=[];$.each(a,function(a,d){$.merge(b,d)});return b};pe.text_contains_query=function(a,b){var c=b.split(" "),d=!0;$.each(c,function(b,c){if(-1===a.indexOf(c))return d=!1,!0});return d};pe.today_date_string=function(){return pe.date_string(new Date)};
pe.truncate_by_words=function(a,b,c){if(!a||!b)return alert("Sorry, but an error happened. We are already warned about that.");c=c||"...";if(a.length<b)return a;a=a.slice(0,b-1);" "!==_.last(a)&&(b=a.lastIndexOf(" "),a=a.slice(0,b));return $.trim(a)+c};pe.value_from_cookie=function(a){return(a=document.cookie.match(RegExp("(^| )"+a+"=([^ ;]+)")))?a[2]:null};
pe.venue_search_text=function(a){var b=[a.name,a.description,a.address,a.hotspot_text,a.neighborhood_name];a.types&&$.each(a.types,function(a,d){b.push(d)});a.tags&&$.each(a.tags,function(a,d){b.push(d)});return b.join(" ")};pe.xor=function(a,b){return!!(a?!b:b)};$(document).ready(function(){$(document).ajaxSend(pe.ajax_send)});
pe.DropdownModule=function(a,b,c,d,e,f){pe.init_widget(this,a);this.container.html(this.html(d,e));this.container.attr("tabindex",0);this.container.addClass("Dropdown");this.container.focusout(this.callback(this.container_focusout));this.container.click(this.callback(this.title_clicked));this.title_string_function=c;this.title_container_div=this.container.find(".TitleContainer");this.title_div=pe.load(this.container.find(".Title"));this.title_div.html(this.title_string_function(null));this.dropdown_input_field=
this.container.find(".DropdownInput");this.dropdown_div=pe.load(this.container.find(".Dropdown"));this.dropdown_div.hide();this.choices_div=pe.load(this.container.find(".Choices"));"function"===typeof b?this.dropdown_html_function=b:"string"===typeof b?this.set_choices_content(b):alert("Unknown dropdown_html type given.");f?(this.set_default_selection('div[data_result="'+f+'"]'),this.set_input_field_value(f)):this.current_selection=null;this.prevent_next_collapse_flag=!1;d&&(new pe.CloseButton(this.container,
pe.CloseButton.close_methods.REMOVE)).bind_event(pe.CloseButton.events.CLOSED,this.callback(this.close_button_clicked));this.auto_collapse=0;this.scroll_timeout=null};pe.DropdownModule.events={OPENED:"DropdownModule_OPENED",CHANGED:"DropdownModule_CHANGED",CLOSED:"DropdownModule_CLOSED",MINIMIZED:"DropdownModule_MINIMIZED"};
pe.DropdownModule.prototype.choice_clicked=function(a){this.current_selection=$(a.target).closest(".Choice");this.collapse_dropdown();this.dropdown_div.hide();this.fire_event(pe.DropdownModule.events.CHANGED,this.current_selection);return!1};pe.DropdownModule.prototype.close_button_clicked=function(){this.fire_event(pe.DropdownModule.events.CLOSED)};
pe.DropdownModule.prototype.collapse_dropdown=function(){this.dropdown_div.hide();this.title_div.html(this.title_string_function(this.current_selection));this.title_div.addClass(this.current_selection&&0<this.current_selection.length?"ClosedWithSelection":"Closed");this.title_container_div.addClass(this.current_selection&&0<this.current_selection.length?"ClosedWithSelection":"Closed");this.title_div.removeClass("Opened");this.title_container_div.removeClass("Opened");this.fire_event(pe.DropdownModule.events.MINIMIZED)};
pe.DropdownModule.prototype.container_focusout=function(){0>this.auto_collapse||setTimeout(this.callback(function(){0<=this.auto_collapse&&!this.prevent_next_collapse_flag&&this.collapse_dropdown();this.prevent_next_collapse_flag=!1}),200)};pe.DropdownModule.prototype.content_scrolling=function(){this.disable_auto_collapse(0);this.scroll_timeout&&clearTimeout(this.scroll_timeout);this.scroll_timeout=setTimeout(this.callback(function(){this.enable_auto_collapse();this.container.focus()}),300)};
pe.DropdownModule.prototype.disable_auto_collapse=function(a){this.auto_collapse-=1;a&&setTimeout(this.callback(function(){this.enable_auto_collapse()}),a)};pe.DropdownModule.prototype.enable_auto_collapse=function(){this.auto_collapse+=1;0<this.auto_collapse&&(this.auto_collapse=0)};
pe.DropdownModule.prototype.expand_dropdown=function(){this.dropdown_html_function&&this.set_choices_content(this.dropdown_html_function());this.dropdown_div.show();this.title_div.html(this.title_string_function("selecting"));this.title_div.removeClass("Closed ClosedWithSelection");this.title_container_div.removeClass("Closed ClosedWithSelection");this.title_div.addClass("Opened");this.title_container_div.addClass("Opened");this.fire_event(pe.DropdownModule.events.OPENED)};
pe.DropdownModule.prototype.html=function(a,b){return'<div class="TitleContainer Closed"><div class="Title select Closed"></div>'+(a?'<div class="CloseButton close_btn fake_link"></div>':"")+'<input type="hidden" class="DropdownInput" name="'+b+'" ></div><div class="Dropdown dropdown"><div class="choices_wrapper"><div class="Choices choices"></div></div><div class="footer_bottom"><div class="footer_right"></div></div></div>'};pe.DropdownModule.prototype.is_expanded=function(){return this.dropdown_div.is(":visible")};
pe.DropdownModule.prototype.prevent_next_collapse=function(){this.prevent_next_collapse_flag=!0};pe.DropdownModule.prototype.reset_dropdown=function(a){this.title_div.html(this.title_string_function(a));this.dropdown_input_field.val("")};pe.DropdownModule.prototype.set_choices_content=function(a){this.choices_div.html(a);this.choices_div.find(".Choice").click(this.callback(this.choice_clicked));this.choices_div.scroll(this.callback(this.content_scrolling))};
pe.DropdownModule.prototype.set_default_selection=function(a){this.current_selection=pe.load(this.dropdown_div.find(a));this.title_div.html(this.title_string_function(this.current_selection))};pe.DropdownModule.prototype.set_error_as_title=function(){this.title_div.html(this.title_string_function("error"))};pe.DropdownModule.prototype.set_input_field_value=function(a){this.dropdown_input_field.val(a)};
pe.DropdownModule.prototype.title_clicked=function(){this.is_expanded()?this.collapse_dropdown():(this.disable_auto_collapse(500),this.expand_dropdown())};pe.DropdownModule.prototype.val=function(a){if(a)this.current_selection="string"===typeof a?this.dropdown_div.find(a):a,this.title_div.html(this.title_string_function(this.current_selection));else return this.current_selection};
pe.CharacterDropdown=function(a,b){pe.init_widget(this,a);this.dropdown_widget=new pe.DropdownModule(a,this.dropdown_html(b),this.callback(this.title_html),!1);this.dropdown_widget.bind_event(pe.DropdownModule.events.CHANGED,this.callback(this.selected));this.dropdown_widget.bind_event(pe.DropdownModule.events.MINIMIZED,this.callback(this.dropdown_closed))};pe.CharacterDropdown.events={OPENED:"CharacterDropdown_OPENED",CHANGED:"CharacterDropdown_CHANGED",CLOSED:"CharacterDropdown_CLOSED"};
pe.CharacterDropdown.prototype.dropdown_closed=function(){this.fire_event(pe.CharacterDropdown.events.CLOSED)};pe.CharacterDropdown.prototype.dropdown_html=function(a){return""+(a?'<div class="Choice choice" data_result="" data_character_name="Anyone">Anyone</div>':"")+'<div class="Choice choice" data_result="lucas" data_character_name="Lucas">Lucas</div><div class="Choice choice" data_result="adriana" data_character_name="Adriana">Adriana</div><div class="Choice choice" data_result="jonah" data_character_name="Jonah">Jonah</div><div class="Choice choice" data_result="emma" data_character_name="Emma">Emma</div>'};
pe.CharacterDropdown.prototype.result_value=function(a){return a&&(a=a.attr("data_result"),"string"===typeof a)?a:""};pe.CharacterDropdown.prototype.selected=function(a,b){this.fire_event(pe.CharacterDropdown.events.CHANGED,this.result_value($(b)))};pe.CharacterDropdown.prototype.title_html=function(a){return a?"selecting"===a?(this.fire_event(pe.CharacterDropdown.events.OPENED,$(a)),'<span class="unselected">Select a Personality</span>'):a.attr("data_character_name"):'<span class="unselected">Select a Personality</span>'};
pe.CharacterDropdown.prototype.val=function(a){if(a)this.dropdown_widget.val(".Choice[data_result='"+a+"']");else return this.result_value(this.dropdown_widget.val())};
pe.CityDropDown=function(a,b){pe.init_widget(this,a);this.dropdown_widget=new pe.DropdownModule(a,this.dropdown_html(b),this.callback(this.title_html),!1,"city_url_param");this.dropdown_widget.bind_event(pe.DropdownModule.events.CHANGED,this.callback(this.dropdown_selected));this.dropdown_widget.bind_event(pe.DropdownModule.events.MINIMIZED,this.callback(this.dropdown_closed))};pe.CityDropDown.events={OPENED:"CityDropDown_OPENED",CHANGED:"CityDropDown_CHANGED",CLOSED:"CityDropDown_CLOSED"};
pe.CityDropDown.prototype.dropdown_closed=function(){this.fire_event(pe.CityDropDown.events.CLOSED)};pe.CityDropDown.prototype.dropdown_html=function(a){return $.map(a,function(a){return pe.templatize('<div class="Choice choice" data_result="{{id}}"><div class="choice_city_name">{{name}}</div></div>',a)}).join("\n")};pe.CityDropDown.prototype.dropdown_selected=function(a,b){var c=this.result_value($(b));this.dropdown_widget.set_input_field_value(c);this.fire_event(pe.CityDropDown.events.CHANGED,c)};
pe.CityDropDown.prototype.result_value=function(a){return a&&(a=a.attr("data_result"),"string"===typeof a)?a:""};pe.CityDropDown.prototype.show_error=function(){this.dropdown_widget.set_error_as_title()};pe.CityDropDown.prototype.title_html=function(a){return a?"selecting"===a?(this.fire_event(pe.CityDropDown.events.OPENED,a),'<span class="unselected">Select a City</span>'):"error"===a?'<span class="unselected error">Please select a city</span>':a.html():'<span class="unselected">Select a City</span>'};
pe.CityDropDown.prototype.val=function(a){if(a)this.dropdown_widget.val(".Choice[data_result='"+a+"']"),this.dropdown_widget.set_input_field_value(a);else return this.result_value(this.dropdown_widget.val())};
pe.MiniKevinModule=function(a,b,c){pe.init_widget(this,a);this.container.html(this.dom());this.city_dropdown=new pe.CityDropDown(this.container.find(".CityDropdown"),b);this.city_dropdown.bind_event(pe.CityDropDown.events.OPENED,this.callback(this.city_dropdown_opened));this.character_dropdown=new pe.CharacterDropdown(this.container.find(".CharacterDropdown"),!1);this.character_dropdown.bind_event(pe.CharacterDropdown.events.OPENED,this.callback(this.character_dropdown_opened));c&&this.character_dropdown.val(c);
this.go_button=this.container.find(".Go");this.go_button.click(this.callback(this.go_button_clicked))};pe.MiniKevinModule.prototype.dom=function(){return'<p>Show me recommendations by</p><div class="CharacterDropdown character_dropdown dropdown_wrapper text"></div><p>In city</p><div class="CityDropdown city_dropdown dropdown_wrapper text"></div><input class="Go go_btn btn_blue" type="button" value="GO!">'};
pe.MiniKevinModule.prototype.go_button_clicked=function(){var a=this.city_dropdown.val(),b=this.character_dropdown.val(),c="See all "+pe.capitalise_first_letter(b+"")+" recommendations in {{city}}";pe.city_configuration_widget.set_cookie_and_redirect({personality:b,city_id:a,filters_section_visible:!0,message:c})};pe.MiniKevinModule.prototype.city_dropdown_opened=function(){this.character_dropdown.dropdown_widget.collapse_dropdown()};pe.MiniKevinModule.prototype.character_dropdown_opened=function(){this.city_dropdown.dropdown_widget.collapse_dropdown()};
pe.SeeMoreButton=function(a,b){pe.init_widget(this,a);this.options={item_container_id:a.attr("rel"),initial_page_number:1,item_class:"Paginable",per_page:16,server_url:"index.ehtml",autoload:!0};$.extend(this.options,b);this.current_page_number=this.options.initial_page_number;this.item_container=$("#"+this.options.item_container_id);this.on_page_loaded=this.options.on_page_loaded;this.options.per_page=this.item_container.find("."+this.options.item_class).length||this.options.per_page;this.next_page_content=
"";this.container.click(this.callback(this.show_next_page));this.hide();this.options.autoload&&this.load_next_page()};pe.SeeMoreButton.prototype.load_next_page=function(a){var b=this.url()+"page="+(this.current_page_number+1)+"&per_page="+this.options.per_page;$.get(b,null,a?a:this.callback(this.set_next_page_content))};
pe.SeeMoreButton.prototype.set_next_page_content=function(a){this.next_page_content=a;this.refresh_photo_links();/\S/.test(a)?this.show():this.hide();if(this.on_page_loaded&&"function"===typeof this.on_page_loaded)this.on_page_loaded()};pe.SeeMoreButton.prototype.refresh_photo_links=function(){window.location.href.match(/events/)&&$(".Paginable a").each(function(){var a=pe.fetch_photo_id_from_url($(this).attr("href")+"");$(this).attr("href",window.location+"/"+a)})};
pe.SeeMoreButton.prototype.reset=function(){this.current_page_number=this.options.initial_page_number;this.container.show()};
pe.SeeMoreButton.prototype.show_next_page=function(){if("function"===typeof this.options.on_click)this.options.on_click();this.options.autoload?(this.item_container.append(this.next_page_content),this.current_page_number+=1,this.load_next_page()):this.load_next_page(this.callback(function(a){this.item_container.append(a);this.current_page_number+=1;this.container.toggle(!_.isEmpty(a));if(this.on_page_loaded&&"function"===typeof this.on_page_loaded)this.on_page_loaded()}));return!1};
pe.SeeMoreButton.prototype.url=function(){var a;a="function"===typeof this.options.server_url?this.options.server_url():this.options.server_url;return a+=/\?/.test(a)?"&":"?"};
pe.GigyaShare.initialize_share_bar=function(a,b){var c=$('meta[property="og:title"]').attr("content"),d=a.data("twitter-message"),e=pe.remove_anchor_from_url(window.location.href),f=new gigya.socialize.UserAction;f.setTitle(c);f.setLinkBack(e);f.setDescription($('meta[property="og:description"]').attr("content"));var g=$('meta[property="og:image"]').attr("content");g&&"http://www.partyearth.com/assets/facebook_50.jpg"!==g&&f.addMediaItem({type:"image",src:g.replace("s100.jpg","s660.jpg"),href:e});
g=new gigya.services.socialize.UserAction;g.setTitle(d);d=$.extend({userAction:f,twitterUserAction:g,shareButtons:[{provider:"facebook"},{provider:"facebook-like",font:"arial"},{provider:"twitter-tweet",defaultText:d,related:"PartyEarth"},{provider:"google-plusone"},{provider:"share",iconImgUp:"http://cdn.partyearth.com/images/social/gigya_share_icon.gif",iconImgOver:"http://cdn.partyearth.com/images/social/gigya_share_icon_hover.gif"}],shortURLs:"never",containerID:a.attr("id"),cid:"",dontSendEmail:!0,
onSendDone:function(a){pe.GigyaShare.share_gigya_email(a,c,e)}},b||{});gigya.socialize.showShareBarUI(d)};pe.GigyaShare.share_gigya_email=function(a,b,c){var d=$.map(a.recipients,function(a){return a.email}).join(", ");$.post("/api/share_link_by_email.json",{sender:a.sender,recipients:d,subject:b.split("|")[0],link:c,message:a.userMessage})};
pe.GigyaShare.initialize_simple_share=function(){var a=$("#SuperDiv");a.removeClass("hidden");pe.sdialog?pe.sdialog.dialog("open"):(pe.sdialog=a,a.dialog({modal:!0,resizable:!0,title:"Share",open:function(){}}));return!0};
pe.Floater=function(a,b,c){pe.init_widget(this,a);this.bottom_margin=c||0;this.start_point_div=a.find(".FloatingAreaStart");this.end_point_div=b||null;this.stop_at=this.start_from=0;this.sticked=this.is_floating=!1;this.floater=this.container.find(".Floater");this.offset=0;this.disabled=!1;this.top=parseInt(this.floater.css("margin-top"),10)||0;$(window).scroll(this.callback(this.scrolling));this.set_floating_area();pe.Floater.register_floater(this)};
pe.Floater.events={TOP_REACHED:"Floater_TOP_REACHED",FLOATING:"Floater_FLOATING",BOTTOM_REACHED:"Floater_BOTTOM_REACHED"};pe.Floater.prototype.set_floating_area=function(){this.start_from=this.start_point_div.offset().top;this.end_point_div&&(this.stop_at=this.end_point_div.offset().top)};
pe.Floater.prototype.scrolling=function(){if(!this.disabled){this.set_floating_area();var a=$(window).scrollTop(),b=a+this.offset+this.bottom_margin<=this.start_from,c=a+this.offset+this.bottom_margin>this.start_from,d=this.floater.position().top+this.floater.outerHeight(!0)>this.stop_at;!this.is_floating&&c&&!d&&!this.sticked?(this.start_floating(),this.fire_event(pe.Floater.events.FLOATING,this),pe.fire_global_event(pe.Floater.events.FLOATING,this)):this.is_floating&&b?(this.stop_scrolling(),this.fire_event(pe.Floater.events.TOP_REACHED,
this)):this.end_point_div&&(!this.sticked&&d?(this.stick(),this.fire_event(pe.Floater.events.BOTTOM_REACHED,this)):this.sticked&&a+this.floater.outerHeight(!0)<=this.stop_at&&this.unstick())}};pe.Floater.prototype.start_floating=function(){this.floater.addClass("fixed");this.floater.removeClass("bottom");this.is_floating=!0;this.sticked=!1;this.set_offset()};
pe.Floater.prototype.stick=function(){this.floater.css("top",this.end_point_div.position().top-this.floater.outerHeight(!0)+"px");this.floater.removeClass("fixed");this.floater.css("position","absolute");this.is_floating=!1;this.sticked=!0};pe.Floater.prototype.disable=function(){this.floater.css("top",this.floater.position().top-140+"px");this.floater.removeClass("fixed");this.floater.css("position","absolute");this.is_floating=!1;this.disabled=this.sticked=!0};
pe.Floater.prototype.enable=function(){this.disabled=!1};pe.Floater.prototype.unstick=function(){this.floater.css("margin-top","");this.floater.css("top","");this.floater.css("position","");this.start_floating();this.fire_event(pe.Floater.events.FLOATING,this)};pe.Floater.prototype.stop_scrolling=function(){this.floater.css("margin-top","");this.floater.removeClass("fixed");this.floater.removeClass("bottom");this.sticked=this.is_floating=!1;this.set_offset()};
pe.Floater.prototype.set_offset=function(a){a&&(this.offset=a);0!==this.offset&&this.is_floating?this.floater.css("margin-top",this.top+this.offset+"px"):this.floater.css("margin-top","")};pe.Floater.registered_floaters=[];pe.Floater.register_floater=function(a){pe.Floater.registered_floaters.push(a);pe.Floater.update_positions()};
pe.Floater.update_positions=function(){pe.Floater.registered_floaters=_.sortBy(pe.Floater.registered_floaters,function(a){return a.container.offset().top},null);if(pe.Floater.registered_floaters[0]&&(pe.Floater.registered_floaters[0].offset=0,1<pe.Floater.registered_floaters.length))for(var a=1;a<pe.Floater.registered_floaters.length;a++){var b=pe.Floater.registered_floaters[a-1].offset+pe.Floater.registered_floaters[a-1].floater.outerHeight();pe.Floater.registered_floaters[a].offset=b;pe.Floater.registered_floaters[a].is_floating&&
pe.Floater.registered_floaters[a].start_floating();pe.Floater.registered_floaters[a].set_floating_area()}};pe.DependencyManager=function(){pe.init_widget(this,null);this.flags=[];this.conditions=[]};pe.DependencyManager.prototype.call_when=function(a,b){_.isArray(a)||(a=[a]);this.conditions.push({flags:a,callback:b,fired:!1});this.fire_callbacks()};
pe.DependencyManager.prototype.condition_match=function(a){var b=!0;$.each(a,this.callback(function(a,d){if(-1===this.flags.indexOf(d))return b=!1}));return b};pe.DependencyManager.prototype.fire_callbacks=function(){$.each(this.conditions,this.callback(function(a,b){!b.fired&&this.condition_match(b.flags)&&(b.fired=!0,b.callback())}))};pe.DependencyManager.prototype.has_flag=function(a){return-1<this.flags.indexOf(a)};pe.DependencyManager.prototype.set_flag=function(a){this.flags.push(a);this.fire_callbacks()};
pe.TotalCountModule=function(a,b){pe.init_widget(this,a);pe.remove_anchor_from_url(b);this.depender=new pe.DependencyManager;this.google_plus_count=this.gigya_share_count=0};
pe.TotalCountModule.prototype.get_gigya_share_count=function(a){gigya.socialize.getProviderShareCounts({url:a,callback:this.callback(function(a){this.gigya_share_count=parseInt(a.shareCounts.facebook||0,10)+parseInt(a.shareCounts.twitter||0,10)+parseInt(a.shareCounts.digg||0,10)+parseInt(a.shareCounts.delicious||0,10)+parseInt(a.shareCounts.stumbleupon||0,10)+parseInt(a.shareCounts.linkedin||0,10)+parseInt(a.shareCounts.pinterest||0,10);this.depender.set_flag("gigya_counter")})})};
pe.TotalCountModule.prototype.get_google_plus_count=function(a){$.ajax({url:"/api/google/plus_count.json?url="+a,success:this.callback(function(a){this.google_plus_count=parseInt(a.count,10);this.depender.set_flag("google_plus_counter")})})};pe.TotalCountModule.prototype.set_total_count=function(){};
pe.SocialButtonsModule=function(a,b,c){pe.init_widget(this,a);this.left_animation_wrapper=this.container.find(".LeftAnimationWrapper");this.right_animation_wrapper=this.container.find(".RightAnimationWrapper");this.default_view=this.right_animation_wrapper.find(".DefaultView");this.default_view_hovered_over=!1;this.window=$(window);this.max_width=97;this.max_left=-137;this.window_resized();this.floater=new pe.Floater($(".FloaterContainer"),$(".FloaterLimiter"));this.floater.bind_event(pe.Floater.events.BOTTOM_REACHED,
this.callback(this.stopped_floating));this.floater.bind_event(pe.Floater.events.FLOATING,this.callback(this.started_floating));this.floater.bind_event(pe.Floater.events.TOP_REACHED,this.callback(this.stopped_floating));b&&new pe.TotalCountModule(this.default_view.find(".TotalCount"),c||window.location.href);this.default_view.mouseover(this.callback(this.default_view_hovered));this.window.resize(this.callback(this.window_resized))};
pe.SocialButtonsModule.events={FLOATING:"SocialButtonsModule_FLOATING",STOPPED_FLOATING:"SocialButtonsModule_STOPPED_FLOATING"};
pe.SocialButtonsModule.prototype.default_view_hovered=function(){this.default_view_hovered_over||(this.default_view_hovered_over=!0,this.left_animation_wrapper.animate({width:this.max_width,left:this.max_left},{duration:500,easing:"cubicEaseInOut"}),this.right_animation_wrapper.animate({right:157},{duration:500,easing:"cubicEaseInOut",complete:this.callback(function(){setTimeout(this.callback(function(){this.left_animation_wrapper.css("overflow","visible")},3E3))})}),this.default_view.animate({opacity:0},
{duration:500}))};pe.SocialButtonsModule.prototype.started_floating=function(){this.fire_event(pe.SocialButtonsModule.events.FLOATING,null)};pe.SocialButtonsModule.prototype.stopped_floating=function(){this.fire_event(pe.SocialButtonsModule.events.STOPPED_FLOATING,null)};
pe.SocialButtonsModule.prototype.window_resized=function(){1229>this.window.width()&&this.container.hasClass("outside")?(this.container.removeClass("outside").addClass("inside"),this.default_view_hovered_over&&(this.left_animation_wrapper.width("auto"),this.left_animation_wrapper.css("left",0))):1229<=this.window.width()&&this.container.hasClass("inside")&&(this.container.removeClass("inside").addClass("outside"),this.default_view_hovered_over&&(this.left_animation_wrapper.width(this.max_width),this.left_animation_wrapper.css("left",
this.max_left)))};setTimeout(function(){$(".st_sharethis_hcount .stBubble_hcount").waitUntilExists(function(){setTimeout(function(){var a=$(".st_sharethis_hcount .stBubble_hcount");"New"==a.html()&&a.html("0");a=$(".st_sharethis_hcount .stBubble_hcount").clone(!0);$(".TotalCount").html(a)},5E3)},!0)},100);
pe.ShareBar=function(a,b,c){pe.init_widget(this,a);c=c||{};c.onShareButtonClicked=this.callback(this.share_button_clicked);this.comments_wrapper=this.container.find(".FloaterComments");this.comments_count_div=this.comments_wrapper.find(".CommentsCount");this.floating_rail=new pe.SocialButtonsModule(this.container,b);this.floating_rail.bind_event(pe.SocialButtonsModule.events.FLOATING,this.callback(this.start_floating_dialog));this.floating_rail.bind_event(pe.SocialButtonsModule.events.STOPPED_FLOATING,
this.callback(this.stop_floating_dialog))};pe.ShareBar.prototype.share_button_clicked=function(a){"shareButtonClicked"===a.eventName&&this.container.hasClass("fixed")&&this.start_floating_dialog()};pe.ShareBar.prototype.start_floating_dialog=function(){var a=$(".gig-simpleShare");0<a.length&&!a.hasClass("fixed")&&a.addClass("fixed")};pe.ShareBar.prototype.stop_floating_dialog=function(){var a=$(".gig-simpleShare");0<a.length&&a.hasClass("fixed")&&a.removeClass("fixed")};
pe.ShareBar.prototype.update_comments_count=function(a){void 0!==a&&(a=parseInt(a,10),this.comments_count_div.html(a),this.comments_wrapper.toggleClass("single_comment",1===a))};
pe.ChangeImageOnHover=function(a,b){pe.init_widget(this,a);this.image_container=this.container.find(".ImageContainer");this.link_parent_class=b||null;this.include_caption=this.container.data("include-caption")||!1;this.object_links=this.container.find(".HoverLinkToChange");this.object_links.mouseover(this.callback(this.object_link_hovered));var c=b?this.container.find("."+b):[];this.link_wrappers=0<c.length?c:this.object_links.parent()};
pe.ChangeImageOnHover.prototype.image_html=function(a){var b='<a href="{{object_url}}" title="{{link_title}}" class="thumbnail_link"><img src="{{image_url}}" alt="{{alt_tag}}"></a>';this.include_caption&&(b+='<p class="name"><span class="date">{{link_prefix}}</span><a href="{{object_url}}">{{image_caption}}</a></p>');a={object_url:a.attr("href"),image_url:a.data("image-url"),link_title:a.data("title")||"",alt_tag:a.data("image-alt-tag")||"",link_prefix:a.data("link-prefix")||"",image_caption:a.html()};
return pe.templatize(b,a)};pe.ChangeImageOnHover.instantiate_all=function(a){return $.map($(".ChangeImageOnHoverContainer"),function(b){return new pe.ChangeImageOnHover($(b),a)})};pe.ChangeImageOnHover.prototype.object_link_hovered=function(a){a=$(a.target);this.object_links.removeClass("selected");this.link_wrappers.removeClass("selected");a.addClass("selected");this.link_wrapper(a).addClass("selected");this.image_container.html(this.image_html(a));pe.convert_to_rounded_corners()};
pe.ChangeImageOnHover.prototype.link_wrapper=function(a){return this.link_parent_class?a.closest("."+this.link_parent_class):a.parent()};pe.PrefetcherModule=function(a){pe.init_widget(this,a);this.elements_with_prefetch_urls=this.container.find("[data-prefetch-url]");this.prefetch_data()};pe.PrefetcherModule.instantiate=function(){return new pe.PrefetcherModule($("body"))};pe.PrefetcherModule.prototype.is_image_url=function(a){return/\.(jpe?g|gif|png)(\?.*)?$/i.test(a)};
pe.PrefetcherModule.prototype.prefetch_ajax_request=function(a){$.getScript(a)};pe.PrefetcherModule.prototype.prefetch_data=function(){$.each(this.elements_with_prefetch_urls,this.callback(function(a,b){b=$(b);var c=b.data("prefetch-url");this.is_image_url(c)?this.prefetch_image(c):this.prefetch_ajax_request(c);b.removeAttr("data-prefetch-url")}))};pe.PrefetcherModule.prototype.prefetch_image=function(a){this.container.append(pe.templatize('<div style="display:none;"><img src="{{url}}"></div>',{url:a}))};
$(document).ready(function(){pe.install_easing();pe.ChangeImageOnHover.instantiate_all("LinkWrapper");pe.PrefetcherModule.instantiate();pe.share_bar=new pe.ShareBar($(".SocialMediaRail"),!0,window.gallery.share_bar_params);pe.share_bar.comments_wrapper.click(pe.write_comment_clicked);pe.init_page_framework(function(){0<$(".MiniKevinModule").length&&pe.ajax_loader.cities.load(function(a){new pe.MiniKevinModule($(".MiniKevinModule"),a,window.gallery.url_param)})});0<$(".SeeMore").length&&new pe.SeeMoreButton($(".SeeMore"),
{server_url:document.location.pathname.replace(/\/$/,".ehtml")});window.search_page_link&&$("#wrapper").addClass("WithSearchLink");setTimeout(function(){pe.update_comment_count()},5);$(".WriteCommentLink").click(pe.write_comment_clicked)});pe.on_comments_loaded=function(){-1!==window.location.href.indexOf("#comments")&&pe.write_comment_clicked();if(-1!==window.location.href.indexOf("Comments_")){var a=window.location.href.split("#")[1];pe.animated_scrolling($("#"+a),10)}};
pe.write_comment_clicked=function(){pe.animated_scrolling($("#comments"),10);$("#Comments-commentTextarea").focus();return!1};pe.on_comment_submitted=function(a){var b=a.user.UID,c=a.commentText,d=a.user.nickname,e=a.comment.ID;a=a.comment.parentID;pe.update_comment_count();$.post("/services/galleries/"+window.gallery.id+"/comments",{comment:{gigya_id:b,gigya_comment_id:e,content:c,nickname:d},gigya_parent_id:a,authenticity_token:window.auth_token})};
pe.social_comments_params=function(){return _.extend(window.gallery.social_params,{userAction:pe.user_action(),replyUserAction:pe.user_action(),streamTitle:window.location.pathname,streamURL:window.location.href,containerID:"Comments",onLoad:pe.on_comments_loaded,onError:pe.gigya_notify_error,onCommentSubmitted:pe.on_comment_submitted,enabledShareProviders:"facebook,twitter,yahoo"})};
pe.update_comment_count=function(){var a=$(".gig-comments-comment").length;pe.share_bar.comments_count_div.html(a);pe.share_bar.comments_wrapper.find(".CommentLabel").html(1===a?"Comment":"Comments");pe.share_bar.comments_wrapper.toggleClass("single_comment",1===a)};
