pe.CloseButton=function(c,b){pe.init_widget(this,c);this.close_button=c.find(".CloseButton");if("function"===typeof b)this.close_button.click(b);else switch(b){case pe.CloseButton.close_methods.REMOVE:this.close_button.click(this.callback(this.remove_container));break;case pe.CloseButton.close_methods.HIDE:this.close_button.click(this.callback(this.hide_container));break;default:alert("unknown value for 'close_method' parameter.")}};pe.CloseButton.close_methods={REMOVE:"REMOVE",HIDE:"HIDE"};
pe.CloseButton.events={CLOSED:"CloseButton_CLOSED"};pe.CloseButton.prototype.remove_container=function(){this.container.detach();this.fire_event(pe.CloseButton.events.CLOSED);this.container.remove();return!1};pe.CloseButton.prototype.hide_container=function(){this.fire_event(pe.CloseButton.events.CLOSED);this.container.hide();return!1};
pe.GeneralAutocompleteInputModule=function(c,b,a,d){pe.init_widget(this,c);this.autocomplete_data_or_url=b;this.input_field_name=a;this.container.html(this.html());this.dummy_input_field=this.container.find(".DummyInputField");this.autocomplete_input_field=this.container.find(".AutocompleteField");this.autocomplete_handler();this.selected_data_list_div=this.container.find(".SelectedDataList");this.selected_data_list_div.sortable();d&&this.add_data_to_list(d)};
pe.GeneralAutocompleteInputModule.events={SELECTED:"GeneralAutocompleteInputModule_SELECTED",REMOVED:"GeneralAutocompleteInputModule_REMOVED",EMPTIED:"GeneralAutocompleteInputMOdule_EMPTIED"};pe.GeneralAutocompleteInputModule.prototype.add_data_to_list=function(c){this.remove_dummy_row();$.each(c,this.callback(function(b,a){-1===$.inArray(a.id.toString(),this.all_values())&&this.autocomplete_data_selected(a.label,a.id,a.category)}))};
pe.GeneralAutocompleteInputModule.prototype.add_dummy_row=function(){this.dummy_input_field||(this.dummy_input_field=$('<input class="DummyInputField"        type="hidden" name="'+this.input_field_name+'"       value="x_mock_single_value_x">'),this.autocomplete_input_field.after(this.dummy_input_field))};pe.GeneralAutocompleteInputModule.prototype.all_values=function(){return this.selected_data_list_div.find('[name="'+this.input_field_name+'"]').map(function(){return this.value}).toArray()};
pe.GeneralAutocompleteInputModule.prototype.autocomplete_data_selected=function(c,b,a){this.remove_dummy_row();this.selected_data_list_div.append(this.selected_data_html(c,b,a));(new pe.CloseButton(this.selected_data_list_div.find(".SelectedInputData").last(),pe.CloseButton.close_methods.REMOVE)).bind_event(pe.CloseButton.events.CLOSED,this.callback(this.close_button_clicked))};
pe.GeneralAutocompleteInputModule.prototype.autocomplete_handler=function(){this.autocomplete_input_field.autocomplete({source:"string"==typeof this.autocomplete_data_or_url?this.callback(function(c,b){$.getJSON(this.autocomplete_data_or_url,{term:this.autocomplete_input_field.val(),val:this.all_values().join(",")},b)}):this.autocomplete_data_or_url,minLength:1,close:this.callback(function(){this.autocomplete_input_field.val("")}),select:this.callback(function(c,b){var a=b.item;this.autocomplete_data_selected(a.label,
a.id,a.category);this.fire_event(pe.GeneralAutocompleteInputModule.events.SELECTED,a.id)})}).data("autocomplete")._renderItem=function(c,b){b.display_label=b.category?pe.templatize("{{label}} ({{category}})",b):b.label;return $("<li></li>").data("item.autocomplete",b).append(pe.templatize("<a>{{display_label}}</a>",b)).appendTo(c)}};pe.GeneralAutocompleteInputModule.prototype.clear_selected_data=function(){this.selected_data_list_div.html("");this.add_dummy_row()};
pe.GeneralAutocompleteInputModule.prototype.close_button_clicked=function(){this.is_empty()&&this.add_dummy_row();this.fire_event(pe.GeneralAutocompleteInputModule.events.REMOVED);this.is_empty()&&this.fire_event(pe.GeneralAutocompleteInputModule.events.EMPTIED)};pe.GeneralAutocompleteInputModule.prototype.display_close_button=function(){this.selected_data_list_div.find(".CloseButton").show()};pe.GeneralAutocompleteInputModule.prototype.hide_close_button=function(){this.selected_data_list_div.find(".CloseButton").hide()};
pe.GeneralAutocompleteInputModule.prototype.html=function(){return'<input class="AutocompleteField" type="text"><input class="DummyInputField" type="hidden" name="'+this.input_field_name+'" value="x_mock_single_value_x"><ul class="SelectedDataList" id="sortable"></ul>'};pe.GeneralAutocompleteInputModule.prototype.is_empty=function(){return 0===this.selected_data_list_div.find(".SelectedInputData").length};
pe.GeneralAutocompleteInputModule.prototype.remove_dummy_row=function(){this.dummy_input_field&&(this.dummy_input_field.remove(),this.dummy_input_field=null)};pe.GeneralAutocompleteInputModule.prototype.replace_data_in_list=function(c){c&&(this.clear_selected_data(),this.add_data_to_list(c))};
pe.GeneralAutocompleteInputModule.prototype.selected_data_html=function(c,b,a){return'<li class="SelectedInputData">  <img style="padding-right:20px; width: 15px; height: 15px;" src="/assets/events/close.png"\t\tclass="CloseButton float_left">  <p class="float_left">'+(a?c+"("+a+")":c)+'</p>  <input type="hidden" value="'+b+'" name="'+this.input_field_name+'">  <div class="clear"></div></li>'};
pe.ConfirmationDialog=function(c,b){pe.init_widget(this,null);this.success_callback=b;this.container=$(this.html(c));this.container.appendTo("body");this.container.dialog({title:"Please confirm action",modal:!0,resizable:!1,width:300,buttons:{Yes:this.callback(this.confirm_clicked),Cancel:function(){$(this).remove()}}})};pe.ConfirmationDialog.prototype.html=function(c){return"<div>"+c+"</div>"};pe.ConfirmationDialog.prototype.confirm_clicked=function(){this.success_callback();this.container.remove()};
pe.SortableAutocomplete=function(c,b,a,d,e){pe.init_widget(this,c);this.autocomplete_data_or_url=b;this.limit=d;this.input_field_name=a;this.container.html(this.html());this.dummy_input_field=this.container.find(".DummyInputField");this.messaging_area=this.container.find(".Messaging");this.autocomplete_input_field=this.container.find(".AutocompleteField");c=this.autocomplete_input_field.autocomplete({source:this.autocomplete_data_or_url,minLength:1,close:this.callback(this.autocomplete_closed),select:this.callback(this.autocomplete_entry_selected)}).data("autocomplete");
c._renderItem=pe.SortableAutocomplete.render_autocomplete_entry;c._renderMenu=pe.SortableAutocomplete.render_autocomplete_list;this.selected_data_list_div=this.container.find(".SelectedDataList");this.selected_data_list_div.sortable();this.selected_data_list_div.disableSelection();e&&this.add_data_to_list(e)};pe.SortableAutocomplete.events={SELECTED:"SortableAutocomplete_SELECTED"};
pe.SortableAutocomplete.prototype.add_data_to_list=function(c){0!==c.length&&(this.remove_dummy_row(),$.each(c,this.callback(function(b,a){this.add_selected_data(a.label,a.id,a.category)})),this.enforce_limit())};pe.SortableAutocomplete.prototype.add_dummy_row=function(){this.dummy_input_field||(this.dummy_input_field=$('<input class="DummyInputField" type="hidden" name="'+this.input_field_name+'" value="">'),this.autocomplete_input_field.after(this.dummy_input_field))};
pe.SortableAutocomplete.prototype.add_selected_data=function(c,b,a){this.remove_dummy_row();this.selected_data_list_div.append(this.selected_data_html(c,b,a));(new pe.CloseButton(this.selected_data_list_div.find(".SelectedInputData").last(),pe.CloseButton.close_methods.REMOVE)).bind_event(pe.CloseButton.events.CLOSED,this.callback(this.close_button_clicked));this.enforce_limit()};pe.SortableAutocomplete.prototype.autocomplete_closed=function(){this.autocomplete_input_field.val("")};
pe.SortableAutocomplete.prototype.autocomplete_entry_selected=function(c,b){var a=b.item;this.add_selected_data(a.label,a.id,a.category);this.fire_event(pe.SortableAutocomplete.events.SELECTED,a.id)};pe.SortableAutocomplete.prototype.close_button_clicked=function(){0===this.selected_data_list_div.find(".SelectedInputData").length&&this.add_dummy_row();this.enforce_limit()};
pe.SortableAutocomplete.prototype.enforce_limit=function(){this.selected_data_list_div.find(".SelectedInputData").length>=this.limit?(this.messaging_area.html("You have reached the selection limit. Please remove before adding."),this.autocomplete_input_field.autocomplete("disable")):(this.messaging_area.html(""),this.autocomplete_input_field.autocomplete("enable"))};
pe.SortableAutocomplete.prototype.html=function(){return'<input class="AutocompleteField" type="text"><div class="Messaging"></div><input class="DummyInputField" type="hidden" name="'+this.input_field_name+'" value=""><ul class="SelectedDataList" id="sortable"></ul>'};pe.SortableAutocomplete.prototype.remove_dummy_row=function(){this.dummy_input_field&&(this.dummy_input_field.remove(),this.dummy_input_field=null)};
pe.SortableAutocomplete.render_autocomplete_entry=function(c,b){b.display_label=b.category?pe.templatize("{{label}} ({{category}})",b):b.label;var a=$(pe.templatize("<li><a>{{display_label}}</a></li>",b));a.data("item.autocomplete",b);c.append(a);return a};pe.SortableAutocomplete.render_autocomplete_list=function(c,b){var a=this,d="";$.each(b,function(b,f){f.type!=d&&(c.append("<li class='ui-autocomplete-category  first_category'>"+f.type+"</li>"),d=f.type);a._renderItem(c,f)})};
pe.SortableAutocomplete.prototype.selected_data_html=function(c,b,a){return'<li class="SelectedInputData ui-state-default"><img style="margin-right:20px; width: 15px; height: 15px;" src="/assets/events/close.png"class="CloseButton float_left"><p class="float_left">'+(a?c+"("+a+")":c)+'</p><input type="hidden" value="'+b+'" name="'+this.input_field_name+'"><div class="clear"></div></li>'};
(function(c){var b;c.rails=b={linkClickSelector:"a[data-confirm], a[data-method], a[data-remote]",formSubmitSelector:"form",formInputClickSelector:"form input[type=submit], form input[type=image], form button[type=submit], form button:not([type])",disableSelector:"input[data-disable-with], button[data-disable-with], textarea[data-disable-with]",enableSelector:"input[data-disable-with]:disabled, button[data-disable-with]:disabled, textarea[data-disable-with]:disabled",requiredInputSelector:"input[name][required],textarea[name][required]",
fileInputSelector:"input:file",CSRFProtection:function(a){var b=c('meta[name="csrf-token"]').attr("content");b&&a.setRequestHeader("X-CSRF-Token",b)},fire:function(a,b,e){b=c.Event(b);a.trigger(b,e);return!1!==b.result},confirm:function(a){return confirm(a)},ajax:function(a){return c.ajax(a)},handleRemote:function(a){var d,e,f,g=a.data("type")||c.ajaxSettings&&c.ajaxSettings.dataType;if(b.fire(a,"ajax:before")){if(a.is("form")){d=a.attr("method");e=a.attr("action");f=a.serializeArray();var h=a.data("ujs:submit-button");
h&&(f.push(h),a.data("ujs:submit-button",null))}else d=a.data("method"),e=a.attr("href"),f=null;b.ajax({url:e,type:d||"GET",data:f,dataType:g,beforeSend:function(c,d){void 0===d.dataType&&c.setRequestHeader("accept","*/*;q=0.5, "+d.accepts.script);return b.fire(a,"ajax:beforeSend",[c,d])},success:function(b,c,d){a.trigger("ajax:success",[b,c,d])},complete:function(b,c){a.trigger("ajax:complete",[b,c])},error:function(b,c,d){a.trigger("ajax:error",[b,c,d])}})}},handleMethod:function(a){var b=a.attr("href"),
e=a.data("method"),a=c("meta[name=csrf-token]").attr("content"),f=c("meta[name=csrf-param]").attr("content"),b=c('<form method="post" action="'+b+'"></form>'),e='<input name="_method" value="'+e+'" type="hidden" />';void 0!==f&&void 0!==a&&(e+='<input name="'+f+'" value="'+a+'" type="hidden" />');b.hide().append(e).appendTo("body");b.submit()},disableFormElements:function(a){a.find(b.disableSelector).each(function(){var a=c(this),b=a.is("button")?"html":"val";a.data("ujs:enable-with",a[b]());a[b](a.data("disable-with"));
a.attr("disabled","disabled")})},enableFormElements:function(a){a.find(b.enableSelector).each(function(){var a=c(this),b=a.is("button")?"html":"val";if(a.data("ujs:enable-with"))a[b](a.data("ujs:enable-with"));a.removeAttr("disabled")})},allowAction:function(a){var c=a.data("confirm"),e=!1,f;if(!c)return!0;b.fire(a,"confirm")&&(e=b.confirm(c),f=b.fire(a,"confirm:complete",[e]));return e&&f},blankInputs:function(a,b,e){var f=c(),g;a.find(b||"input,textarea").each(function(){g=c(this);if(e?g.val():
!g.val())f=f.add(g)});return f.length?f:!1},nonBlankInputs:function(a,c){return b.blankInputs(a,c,!0)},stopEverything:function(a){a.stopImmediatePropagation();return!1},callFormSubmitBindings:function(a){var a=a.data("events"),b=!0;void 0!==a&&void 0!==a.submit&&c.each(a.submit,function(a,c){if("function"===typeof c.handler)return b=c.handler(c.data)});return b}};"ajaxPrefilter"in c?c.ajaxPrefilter(function(a,c,e){b.CSRFProtection(e)}):c(document).ajaxSend(function(a,c){b.CSRFProtection(c)});c(b.linkClickSelector).live("click.rails",
function(a){var d=c(this);if(!b.allowAction(d))return b.stopEverything(a);if(void 0!==d.data("remote"))return b.handleRemote(d),!1;if(d.data("method"))return b.handleMethod(d),!1});c(b.formSubmitSelector).live("submit.rails",function(a){var d=c(this),e=void 0!==d.data("remote"),f=b.blankInputs(d,b.requiredInputSelector),g=b.nonBlankInputs(d,b.fileInputSelector);if(!b.allowAction(d))return b.stopEverything(a);if(f&&b.fire(d,"ajax:aborted:required",[f]))return!e;if(e){if(g)return b.fire(d,"ajax:aborted:file",
[g]);if(!c.support.submitBubbles&&!1===b.callFormSubmitBindings(d))return b.stopEverything(a);b.handleRemote(d);return!1}setTimeout(function(){b.disableFormElements(d)},13)});c(b.formInputClickSelector).live("click.rails",function(a){var d=c(this);if(!b.allowAction(d))return b.stopEverything(a);a=(a=d.attr("name"))?{name:a,value:d.val()}:null;d.closest("form").data("ujs:submit-button",a)});c(b.formSubmitSelector).live("ajax:beforeSend.rails",function(a){this==a.target&&b.disableFormElements(c(this))});
c(b.formSubmitSelector).live("ajax:complete.rails",function(a){this==a.target&&b.enableFormElements(c(this))})})(jQuery);$(document).ready(function(){pe.ajax_loader.tags.load({timestamp:pe.tags_timestamp()},function(c){new pe.SortableAutocomplete($(".TagSelector"),c,"endpoint[ordered_tag_ids][]",1E4,window.existing_tags)});$(".CitiesTable").click(pe.cities_table_clicked);pe.init_page_framework()});
pe.cities_table_clicked=function(){if(!$(".PageTemplates input[type=radio]:checked").length)return alert("Please provide some page template!"),!1};
