pe.Floater=function(a,c,b){pe.init_widget(this,a);this.bottom_margin=b||0;this.start_point_div=a.find(".FloatingAreaStart");this.end_point_div=c||null;this.stop_at=this.start_from=0;this.sticked=this.is_floating=!1;this.floater=this.container.find(".Floater");this.offset=0;this.disabled=!1;this.top=parseInt(this.floater.css("margin-top"),10)||0;$(window).scroll(this.callback(this.scrolling));this.set_floating_area();pe.Floater.register_floater(this)};
pe.Floater.events={TOP_REACHED:"Floater_TOP_REACHED",FLOATING:"Floater_FLOATING",BOTTOM_REACHED:"Floater_BOTTOM_REACHED"};pe.Floater.prototype.set_floating_area=function(){this.start_from=this.start_point_div.offset().top;this.end_point_div&&(this.stop_at=this.end_point_div.offset().top)};
pe.Floater.prototype.scrolling=function(){if(!this.disabled){this.set_floating_area();var a=$(window).scrollTop(),c=a+this.offset+this.bottom_margin<=this.start_from,b=a+this.offset+this.bottom_margin>this.start_from,d=this.floater.position().top+this.floater.outerHeight(!0)>this.stop_at;!this.is_floating&&b&&!d&&!this.sticked?(this.start_floating(),this.fire_event(pe.Floater.events.FLOATING,this),pe.fire_global_event(pe.Floater.events.FLOATING,this)):this.is_floating&&c?(this.stop_scrolling(),this.fire_event(pe.Floater.events.TOP_REACHED,
this)):this.end_point_div&&(!this.sticked&&d?(this.stick(),this.fire_event(pe.Floater.events.BOTTOM_REACHED,this)):this.sticked&&a+this.floater.outerHeight(!0)<=this.stop_at&&this.unstick())}};pe.Floater.prototype.start_floating=function(){this.floater.addClass("fixed");this.floater.removeClass("bottom");this.is_floating=!0;this.sticked=!1;this.set_offset()};
pe.Floater.prototype.stick=function(){this.floater.css("top",this.end_point_div.position().top-this.floater.outerHeight(!0)+"px");this.floater.removeClass("fixed");this.floater.css("position","absolute");this.is_floating=!1;this.sticked=!0};pe.Floater.prototype.disable=function(){this.floater.css("top",this.floater.position().top-140+"px");this.floater.removeClass("fixed");this.floater.css("position","absolute");this.is_floating=!1;this.disabled=this.sticked=!0};
pe.Floater.prototype.enable=function(){this.disabled=!1};pe.Floater.prototype.unstick=function(){this.floater.css("margin-top","");this.floater.css("top","");this.floater.css("position","");this.start_floating();this.fire_event(pe.Floater.events.FLOATING,this)};pe.Floater.prototype.stop_scrolling=function(){this.floater.css("margin-top","");this.floater.removeClass("fixed");this.floater.removeClass("bottom");this.sticked=this.is_floating=!1;this.set_offset()};
pe.Floater.prototype.set_offset=function(a){a&&(this.offset=a);0!==this.offset&&this.is_floating?this.floater.css("margin-top",this.top+this.offset+"px"):this.floater.css("margin-top","")};pe.Floater.registered_floaters=[];pe.Floater.register_floater=function(a){pe.Floater.registered_floaters.push(a);pe.Floater.update_positions()};
pe.Floater.update_positions=function(){pe.Floater.registered_floaters=_.sortBy(pe.Floater.registered_floaters,function(b){return b.container.offset().top},null);if(pe.Floater.registered_floaters[0]&&(pe.Floater.registered_floaters[0].offset=0,1<pe.Floater.registered_floaters.length))for(var a=1;a<pe.Floater.registered_floaters.length;a++){var c=pe.Floater.registered_floaters[a-1].offset+pe.Floater.registered_floaters[a-1].floater.outerHeight();pe.Floater.registered_floaters[a].offset=c;pe.Floater.registered_floaters[a].is_floating&&
pe.Floater.registered_floaters[a].start_floating();pe.Floater.registered_floaters[a].set_floating_area()}};
pe.ChangeImageOnHover=function(a,c){pe.init_widget(this,a);this.image_container=this.container.find(".ImageContainer");this.link_parent_class=c||null;this.include_caption=this.container.data("include-caption")||!1;this.object_links=this.container.find(".HoverLinkToChange");this.object_links.mouseover(this.callback(this.object_link_hovered));var b=c?this.container.find("."+c):[];this.link_wrappers=0<b.length?b:this.object_links.parent()};
pe.ChangeImageOnHover.prototype.image_html=function(a){var c='<a href="{{object_url}}" title="{{link_title}}" class="object_photo ConvertToRoundedCorners"><img src="{{image_url}}" alt="{{alt_tag}}" class="thumbnail float_left"></a>';this.include_caption&&(c+='<p class="img_name">{{link_prefix}} <a href="{{object_url}}">{{image_caption}}</a></p>');a={object_url:a.attr("href"),image_url:a.data("image-url"),link_title:a.data("title")||"",alt_tag:a.data("image-alt-tag")||"",link_prefix:a.data("link-prefix")||
"",image_caption:a.html()};return pe.templatize(c,a)};pe.ChangeImageOnHover.instantiate_all=function(a){return $.map($(".ChangeImageOnHoverContainer"),function(c){return new pe.ChangeImageOnHover($(c),a)})};pe.ChangeImageOnHover.prototype.object_link_hovered=function(a){a=$(a.target);this.object_links.removeClass("hovered");this.link_wrappers.removeClass("hovered");a.addClass("hovered");this.link_wrapper(a).addClass("hovered");this.image_container.html(this.image_html(a));pe.convert_to_rounded_corners()};
pe.ChangeImageOnHover.prototype.link_wrapper=function(a){return this.link_parent_class?a.closest("."+this.link_parent_class):a.parent()};
(function(a){var c;a.rails=c={linkClickSelector:"a[data-confirm], a[data-method], a[data-remote]",formSubmitSelector:"form",formInputClickSelector:"form input[type=submit], form input[type=image], form button[type=submit], form button:not([type])",disableSelector:"input[data-disable-with], button[data-disable-with], textarea[data-disable-with]",enableSelector:"input[data-disable-with]:disabled, button[data-disable-with]:disabled, textarea[data-disable-with]:disabled",requiredInputSelector:"input[name][required],textarea[name][required]",
fileInputSelector:"input:file",CSRFProtection:function(b){var d=a('meta[name="csrf-token"]').attr("content");d&&b.setRequestHeader("X-CSRF-Token",d)},fire:function(b,d,c){d=a.Event(d);b.trigger(d,c);return!1!==d.result},confirm:function(b){return confirm(b)},ajax:function(b){return a.ajax(b)},handleRemote:function(b){var d,f,e,g=b.data("type")||a.ajaxSettings&&a.ajaxSettings.dataType;if(c.fire(b,"ajax:before")){if(b.is("form")){d=b.attr("method");f=b.attr("action");e=b.serializeArray();var h=b.data("ujs:submit-button");
h&&(e.push(h),b.data("ujs:submit-button",null))}else d=b.data("method"),f=b.attr("href"),e=null;c.ajax({url:f,type:d||"GET",data:e,dataType:g,beforeSend:function(a,d){void 0===d.dataType&&a.setRequestHeader("accept","*/*;q=0.5, "+d.accepts.script);return c.fire(b,"ajax:beforeSend",[a,d])},success:function(a,d,c){b.trigger("ajax:success",[a,d,c])},complete:function(a,d){b.trigger("ajax:complete",[a,d])},error:function(a,d,c){b.trigger("ajax:error",[a,d,c])}})}},handleMethod:function(b){var d=b.attr("href"),
c=b.data("method"),b=a("meta[name=csrf-token]").attr("content"),e=a("meta[name=csrf-param]").attr("content"),d=a('<form method="post" action="'+d+'"></form>'),c='<input name="_method" value="'+c+'" type="hidden" />';void 0!==e&&void 0!==b&&(c+='<input name="'+e+'" value="'+b+'" type="hidden" />');d.hide().append(c).appendTo("body");d.submit()},disableFormElements:function(b){b.find(c.disableSelector).each(function(){var d=a(this),b=d.is("button")?"html":"val";d.data("ujs:enable-with",d[b]());d[b](d.data("disable-with"));
d.attr("disabled","disabled")})},enableFormElements:function(b){b.find(c.enableSelector).each(function(){var b=a(this),c=b.is("button")?"html":"val";if(b.data("ujs:enable-with"))b[c](b.data("ujs:enable-with"));b.removeAttr("disabled")})},allowAction:function(b){var a=b.data("confirm"),f=!1,e;if(!a)return!0;c.fire(b,"confirm")&&(f=c.confirm(a),e=c.fire(b,"confirm:complete",[f]));return f&&e},blankInputs:function(b,c,f){var e=a(),g;b.find(c||"input,textarea").each(function(){g=a(this);if(f?g.val():
!g.val())e=e.add(g)});return e.length?e:!1},nonBlankInputs:function(a,d){return c.blankInputs(a,d,!0)},stopEverything:function(a){a.stopImmediatePropagation();return!1},callFormSubmitBindings:function(b){var b=b.data("events"),c=!0;void 0!==b&&void 0!==b.submit&&a.each(b.submit,function(a,b){if("function"===typeof b.handler)return c=b.handler(b.data)});return c}};"ajaxPrefilter"in a?a.ajaxPrefilter(function(a,d,f){c.CSRFProtection(f)}):a(document).ajaxSend(function(a,d){c.CSRFProtection(d)});a(c.linkClickSelector).live("click.rails",
function(b){var d=a(this);if(!c.allowAction(d))return c.stopEverything(b);if(void 0!==d.data("remote"))return c.handleRemote(d),!1;if(d.data("method"))return c.handleMethod(d),!1});a(c.formSubmitSelector).live("submit.rails",function(b){var d=a(this),f=void 0!==d.data("remote"),e=c.blankInputs(d,c.requiredInputSelector),g=c.nonBlankInputs(d,c.fileInputSelector);if(!c.allowAction(d))return c.stopEverything(b);if(e&&c.fire(d,"ajax:aborted:required",[e]))return!f;if(f){if(g)return c.fire(d,"ajax:aborted:file",
[g]);if(!a.support.submitBubbles&&!1===c.callFormSubmitBindings(d))return c.stopEverything(b);c.handleRemote(d);return!1}setTimeout(function(){c.disableFormElements(d)},13)});a(c.formInputClickSelector).live("click.rails",function(b){var d=a(this);if(!c.allowAction(d))return c.stopEverything(b);b=(b=d.attr("name"))?{name:b,value:d.val()}:null;d.closest("form").data("ujs:submit-button",b)});a(c.formSubmitSelector).live("ajax:beforeSend.rails",function(b){this==b.target&&c.disableFormElements(a(this))});
a(c.formSubmitSelector).live("ajax:complete.rails",function(b){this==b.target&&c.enableFormElements(a(this))})})(jQuery);$(document).ready(function(){new pe.Floater($(".FloaterContainer"));pe.init_page_framework()});
