(function(b){b.fn.editable=function(c,d){if("disable"==c)b(this).data("disabled.editable",!0);else if("enable"==c)b(this).data("disabled.editable",!1);else if("destroy"==c)b(this).unbind(b(this).data("event.editable")).removeData("disabled.editable").removeData("event.editable");else{var a=b.extend({},b.fn.editable.defaults,{target:c},d),e=b.editable.types[a.type].plugin||function(){},g=b.editable.types[a.type].submit||function(){},l=b.editable.types[a.type].buttons||b.editable.types.defaults.buttons,
p=b.editable.types[a.type].content||b.editable.types.defaults.content,j=b.editable.types[a.type].element||b.editable.types.defaults.element,q=b.editable.types[a.type].reset||b.editable.types.defaults.reset,r=a.callback||function(){},s=a.onedit||function(){},t=a.onsubmit||function(){},u=a.onreset||function(){},v=a.onerror||q;a.tooltip&&b(this).attr("title",a.tooltip);a.autowidth="auto"==a.width;a.autoheight="auto"==a.height;return this.each(function(){var c=this,d=b(c).width(),w=b(c).height();b(this).data("event.editable",
a.event);b.trim(b(this).html())||b(this).html(a.placeholder);b(this).bind(a.event,function(k){if(!0!==b(this).data("disabled.editable")&&!c.editing&&!1!==s.apply(this,[a,c])){k.preventDefault();k.stopPropagation();a.tooltip&&b(c).removeAttr("title");0==b(c).width()?(a.width=d,a.height=w):("none"!=a.width&&(a.width=a.autowidth?b(c).width():a.width),"none"!=a.height&&(a.height=a.autoheight?b(c).height():a.height));b(this).html().toLowerCase().replace(/(;|")/g,"")==a.placeholder.toLowerCase().replace(/(;|")/g,
"")&&b(this).html("");c.editing=!0;c.revert=b(c).html();b(c).html("");var f=b("<form />");a.cssclass&&("inherit"==a.cssclass?f.attr("class",b(c).attr("class")):f.attr("class",a.cssclass));a.style&&("inherit"==a.style?(f.attr("style",b(c).attr("style")),f.css("display",b(c).css("display"))):f.attr("style",a.style));var h=j.apply(f,[a,c]),m;if(a.loadurl){var n=setTimeout(function(){h.disabled=!0;p.apply(f,[a.loadtext,a,c])},100);k={};k[a.id]=c.id;b.isFunction(a.loaddata)?b.extend(k,a.loaddata.apply(c,
[c.revert,a])):b.extend(k,a.loaddata);b.ajax({type:a.loadtype,url:a.loadurl,data:k,async:!1,success:function(a){window.clearTimeout(n);m=a;h.disabled=!1}})}else a.data?(m=a.data,b.isFunction(a.data)&&(m=a.data.apply(c,[c.revert,a]))):m=c.revert;p.apply(f,[m,a,c]);h.attr("name",a.name);l.apply(f,[a,c]);b(c).append(f);e.apply(f,[a,c]);b(":input:visible:enabled:first",f).focus();a.select&&h.select();h.keydown(function(b){27==b.keyCode&&(b.preventDefault(),q.apply(f,[a,c]))});"cancel"==a.onblur?h.blur(function(){n=
setTimeout(function(){q.apply(f,[a,c])},500)}):"submit"==a.onblur?h.blur(function(){n=setTimeout(function(){f.submit()},200)}):b.isFunction(a.onblur)?h.blur(function(){a.onblur.apply(c,[h.val(),a])}):h.blur(function(){});f.submit(function(d){n&&clearTimeout(n);d.preventDefault();if(!1!==t.apply(f,[a,c])&&!1!==g.apply(f,[a,c]))if(b.isFunction(a.target))d=a.target.apply(c,[h.val(),a]),b(c).html(d),c.editing=!1,r.apply(c,[c.innerHTML,a]),b.trim(b(c).html())||b(c).html(a.placeholder);else{d={};d[a.name]=
h.val();d[a.id]=c.id;b.isFunction(a.submitdata)?b.extend(d,a.submitdata.apply(c,[c.revert,a])):b.extend(d,a.submitdata);"PUT"==a.method&&(d._method="put");b(c).html(a.indicator);var e={type:"POST",data:d,dataType:"html",url:a.target,success:function(d){"html"==e.dataType&&b(c).html(d);c.editing=!1;r.apply(c,[d,a]);b.trim(b(c).html())||b(c).html(a.placeholder)},error:function(b){v.apply(f,[a,c,b])}};b.extend(e,a.ajaxoptions);b.ajax(e)}b(c).attr("title",a.tooltip);return!1})}});this.reset=function(d){this.editing&&
!1!==u.apply(d,[a,c])&&(b(c).html(c.revert),c.editing=!1,b.trim(b(c).html())||b(c).html(a.placeholder),a.tooltip&&b(c).attr("title",a.tooltip))}})}};b.editable={types:{defaults:{element:function(){var c=b('<input type="hidden"></input>');b(this).append(c);return c},content:function(c){b(":input:first",this).val(c)},reset:function(c,b){b.reset(this)},buttons:function(c,d){var a=this;if(c.submit){if(c.submit.match(/>$/))var e=b(c.submit).click(function(){"submit"!=e.attr("type")&&a.submit()});else e=
b('<button type="submit" />'),e.html(c.submit);b(this).append(e)}if(c.cancel){if(c.cancel.match(/>$/))var g=b(c.cancel);else g=b('<button type="cancel" />'),g.html(c.cancel);b(this).append(g);b(g).click(function(){(b.isFunction(b.editable.types[c.type].reset)?b.editable.types[c.type].reset:b.editable.types.defaults.reset).apply(a,[c,d]);return!1})}}},text:{element:function(c){var d=b("<input />");"none"!=c.width&&d.width(c.width);"none"!=c.height&&d.height(c.height);d.attr("autocomplete","off");b(this).append(d);
return d}},textarea:{element:function(c){var d=b("<textarea />");c.rows?d.attr("rows",c.rows):"none"!=c.height&&d.height(c.height);c.cols?d.attr("cols",c.cols):"none"!=c.width&&d.width(c.width);b(this).append(d);return d}},select:{element:function(){var c=b("<select />");b(this).append(c);return c},content:function(c,d,a){if(String==c.constructor)eval("var json = "+c);else var e=c;for(var g in e)e.hasOwnProperty(g)&&"selected"!=g&&(c=b("<option />").val(g).append(e[g]),b("select",this).append(c));
b("select",this).children().each(function(){(b(this).val()==e.selected||b(this).text()==b.trim(a.revert))&&b(this).attr("selected","selected")})}}},addInputType:function(c,d){b.editable.types[c]=d}};b.fn.editable.defaults={name:"value",id:"id",type:"text",width:"auto",height:"auto",event:"click.editable",onblur:"cancel",loadtype:"GET",loadtext:"Loading...",placeholder:"Click to edit",loaddata:{},submitdata:{},ajaxoptions:{}}})(jQuery);
pe.routes={map:{search_autocomplete:"{{city_id}}/search/autocomplete.ehtml/",api_user_list:"/api/user_lists/{{id}}",api_reorder_user_list:"/api/user_lists/{{id}}/reorder",api_user_list_favorites:"/api/user_lists/{{id}}/favorites",api_favorite:"/api/favorites/{{id}}",holiday:"/{{city_id}}/holidays/{{id}}-7",holiday_comments:"/services/holidays/{{id}}/comments",holiday_reactions:"/holidays/{{id}}/reactions/all",new_holiday_reactions:"/holidays/{{id}}/reactions",holiday_calendar:"/{{city_id}}/holidays/{{id}}-7/calendar",
holiday_photos:"/api/{{city_id}}/holidays/{{id}}/photos",holiday_map_venues:"/api/maps/holidays/{{slug}}/venues",holiday_map_events:"/api/maps/holidays/{{slug}}/events",venue_map_popup:"/venues/{{venue_id}}/map_popup",map_venues:"/api/cities/{{city_id}}/maps/venues",map_events:"/api/cities/{{city_id}}/maps/events",map_neighborhood_venues:"/api/maps/neighborhoods/{{neighborhood_id}}/venues",map_neighborhood_events:"/api/maps/neighborhoods/{{neighborhood_id}}/events",map_neighborhood_endpoint_venues:"/api/maps/neighborhoods/{{neighborhood_id}}/endpoints/{{endpoint_id}}/venues",
map_neighborhood_endpoint_events:"/api/maps/neighborhoods/{{neighborhood_id}}/endpoints/{{endpoint_id}}/events",user_list_map_venues:"/api/maps/users/{{user_id}}/lists/{{id}}/venues",user_list_map_events:"/api/maps/users/{{user_id}}/lists/{{id}}/events",user_list:"/users/{{user_id}}/lists/{{id}}",list_comments:"/services/lists/{{id}}/comments",list_reactions:"/lists/{{id}}/reactions/all",new_list_reactions:"/lists/{{id}}/reactions",event:"/{{city_id}}/{{*endpoints}}/{{id}}-1"}};
pe.routes.build_path=function(b,c){var d=pe.routes.map[b],a=d.match(/\{\{\*(.+)\}\}/);_.each(a,function(a){c[a]&&(c[a]=c[a].join("/"))});d=d.replace(/\*/,"");return pe.routes.clean_url(pe.templatize(d,c))};pe.routes.clean_url=function(b){return("/"+b).replace(/#[^$\/]+/,"").replace(/(^[^?]+)([^:])\/\//,"$1$2/").replace(/\/\//g,"/")};pe.routes.current_url_params=function(){var b=pe.routes.recognize_path(window.location.pathname);return b?b.params:{}};
pe.routes.recognize_path=function(b){b=pe.routes.clean_url(b);var c,d,a=_.find(_.keys(pe.routes.map),function(a){c=pe.routes.map[a];d=RegExp(c.replace(/\//g,"\\/").replace(/\{\{[^\{\}]+\}\}/g,"(.+)"));return d.test(b)});if(a){for(var e=_.map(c.match(/\{\{[^\}]+\}\}/g),function(a){return a.replace(/\{|\}/g,"")}),g=b.match(d).slice(1,99),l={params:{}},p=function(a){return!_.isEmpty(a)},j=0;j<e.length;j++)"*"==e[j][0]&&(e[j]=e[j].replace(/\*/g,""),g[j]=_.select(g[j].replace(/\*/g,"").split("/"),p)),
l.params[e[j]]=g[j];l.path_info={name:a,template:c};return l}return!1};pe.routes.Request=function(b,c,d){pe.routes.map[b]?(this.path=b,"object"!==typeof c&&(c={id:c}),this.params=c,this.callback=d):alert("This path is not registered in the routes map.")};pe.routes.Request.factory=function(b,c,d){return new pe.routes.Request(b,c,d)};pe.routes.Request.from_current_location=function(b,c,d){c=c||{};var a=pe.routes.current_url_params();return new pe.routes.Request(b,_.extend(a,c),d)};
pe.routes.Request.prototype.ajax=function(b,c){var d="function"===typeof c?c:this.callback;$.ajax({url:this.build_path(),data:this.params,type:b,success:d})};pe.routes.Request.prototype.build_path=function(){return pe.routes.build_path(this.path,this.params)};pe.routes.Request.prototype.get=function(b){this.ajax("GET",b)};pe.routes.Request.prototype.post=function(b){this.ajax("POST",b)};
(function(){var b=function(a,b){return function(){return a.apply(b,arguments)}},c=pe,d=function(a,c){this.container=a;this.options=c;this.on_value_submitted=b(this.on_value_submitted,this);this.on_value_changed=b(this.on_value_changed,this);this.container.html(this.container.html().replace(/^\s+/g,""));this.container.html(this.container.html().replace(/\n/g,"<br>"));this.field=this.options.field;this.allow_empty_value=!!this.options.allow_empty_value;this.current_url_params=pe.routes.current_url_params();
this.container.click(this.on_container_clicked);this.container.editable(this.on_value_changed,this.options.jeditable);this.on_submit=this.options.submit||function(){}};d.prototype.on_container_clicked=function(a){var b,c;b=$(a.currentTarget);if(b.hasClass("EditableDescription")){c=b.find("textarea");if(0<c.length)return a=c.val(),a=a.replace(/\n\s+/g,"\n"),a=a.replace(/<br>/g,"\n"),c.val(a);a=b.html();a=a.replace(/\n\s+/g,"\n");a=a.replace(/<br>/g,"\n");return b.html(a)}};d.prototype.on_value_changed=
function(a){var b;a=a.replace(/\n\s+/,"\n");this.is_valid_value(a)&&(b={user_list:{},_method:"put"},b.user_list[this.field]=a,b=pe.routes.Request.from_current_location("api_user_list",b),b.post(this.on_value_submitted));this.on_submit();return a.replace(/\n/g,"<br>")};d.prototype.on_value_submitted=function(a){a=a.instance.url_param;if(this.current_url_params.id!==a)return window.location=pe.routes.build_path("user_list",{user_id:this.current_url_params.user_id,id:a})};d.prototype.is_valid_value=
function(a){return this.allow_empty_value||!(_.isEmpty(a.replace(/\s+/g,""))||this.options.jeditable.placeholder===a)};d.prototype.is_valid=function(){return this.is_valid_value(this.container.html())};c.EditableListField=d}).call(this);
