pe.VenueSearcher=function(){pe.init_widget(this,null)};
pe.VenueSearcher.prototype.get_matching_venues=function(a,c){!a.has_filters("city")||"all"===a.get_filter("city")?c([]):pe.ajax_loader.city_venues.load({city_id:a.get_filter("city"),timestamp:pe.venues_timestamp()},function(b){$.each(b,function(b,a){a.disabled=null});b=pe.VenueSearcher.filter_by_result_types(b,a);b=pe.VenueSearcher.filter_by_neighborhood(b,a);b=pe.VenueSearcher.filter_by_character(b,a);b=pe.VenueSearcher.filter_by_venue_types(b,a);b=pe.VenueSearcher.filter_by_tags(b,a);b=pe.VenueSearcher.filter_by_venue_name(b,
a);b=pe.VenueSearcher.filter_by_fulltext(b,a);b=pe.VenueSearcher.filter_by_performer_name(b,a);pe.VenueSearcher.mark_hotspots(b,a);pe.VenueSearcher.mark_venue_map_visibility(b,a);c(b)})};pe.VenueSearcher.filter_by_city=function(a,c){var b=c.get_filter("city");return!b?a:$.map(a,function(a){if(a.city===b)return a})};
pe.VenueSearcher.filter_by_character=function(a,c){var b=c.get_filter("characters");if(!b||4===b.length)return a;if(0===b.length)return[];var d=[];-1<b.indexOf("adriana")&&$.each(a,function(b,a){3<=a.rating_adriana&&!pe.map_tools.venues_contain_venue(d,a.id)&&d.push(a)});-1<b.indexOf("lucas")&&$.each(a,function(b,a){3<=a.rating_lucas&&!pe.map_tools.venues_contain_venue(d,a.id)&&d.push(a)});-1<b.indexOf("jonah")&&$.each(a,function(b,a){3<=a.rating_jonah&&!pe.map_tools.venues_contain_venue(d,a.id)&&
d.push(a)});-1<b.indexOf("emma")&&$.each(a,function(b,a){3<=a.rating_emma&&!pe.map_tools.venues_contain_venue(d,a.id)&&d.push(a)});return d};pe.VenueSearcher.filter_by_fulltext=function(a,c){var b=c.get_filter("fulltext");return!b?a:$.map(a,function(a){if(pe.text_contains_query(pe.venue_search_text(a),b))return a})};pe.VenueSearcher.filter_by_neighborhood=function(a,c){var b=c.get_filter("neighborhood");if(!b||"all"===b)return a;$.each(a,function(a,c){c.neighborhood_id!==b&&(c.disabled=!0)});return a};
pe.VenueSearcher.filter_by_performer_name=function(a,c){if(!c.get_filter("performer_name"))return a;$.each(a,function(a,c){c.disabled=!0});return a};pe.VenueSearcher.filter_by_result_types=function(a,c){var b=c.get_filter("result_types");if(!b||-1<b.indexOf("venues"))return a;if(-1<b.indexOf("hotspots")){var d=new Date(c.get_filter("start_date_or_default")),e=(b=c.get_filter("end_date"))?new Date(b):d;return $.map(a,function(a){if(pe.VenueSearcher.venue_is_hotspot_in_date_range(a,d,e))return a})}return[]};
pe.VenueSearcher.filter_by_tags=function(a,c){var b=c.get_filter("tags");if(!b)return a;var b=pe.VenueSearcher.remove_event_tags(b),d=pe.structured_tags_as_flat_array(b);return $.map(a,function(a){if(pe.array_contains(a.tags,d))return a})};pe.VenueSearcher.filter_by_venue_name=function(a,c){var b=c.get_filter("venue_name");return!b?a:$.map(a,function(a){if(-1<b.indexOf(a.name))return a})};
pe.VenueSearcher.filter_by_venue_types=function(a,c){var b=c.get_filter("Venue Type");return!b||"all"===b?a:$.grep(a,function(a){return pe.array_match(b,a.all_venue_types)})};pe.VenueSearcher.find_used_tags=function(a,c){var b={};$.each(a,function(a,e){$.each(c,function(c,g){$.each(e,function(c,e){-1<g.tags.indexOf(c)&&(b[a]||(b[a]={}),b[a][c]||(b[a][c]=[]));$.each(e,function(e,f){if(g.tags.indexOf(f)>-1){b[a]||(b[a]={});b[a][c]||(b[a][c]=[]);b[a][c].push(f)}})})})});return b};
pe.VenueSearcher.mark_hotspots=function(a,c){var b=new Date(c.get_filter("start_date_or_default")),d=new Date(c.get_filter("end_date_or_default"));$.each(a,function(a,c){c.hotspot=pe.VenueSearcher.venue_is_hotspot_in_date_range(c,b,d)})};pe.VenueSearcher.find_hotspots=function(a){return $.grep(a,function(a){return a.hotspot})};pe.VenueSearcher.find_map_hotspots=function(a){return $.map(a,function(a){if(a.map_icon===pe.Map.marker_types.HOTSPOT)return a})};
pe.VenueSearcher.find_map_venues=function(a){return $.map(a,function(a){if(a.map_icon===pe.Map.marker_types.VENUE)return a})};pe.VenueSearcher.mark_venue_map_visibility=function(a,c){var b=c.get_filter("result_types"),d=b?-1<b.indexOf("venues"):!0,e=b?-1<b.indexOf("hotspots"):!0;$.each(a,function(a,b){b.map_icon=b.hotspot?pe.Map.marker_types.HOTSPOT:pe.Map.marker_types.VENUE;d?(b.map_visibility=!0,b.hotspot&&!e&&(b.map_icon=pe.Map.marker_types.VENUE)):b.map_visibility=!(!b.hotspot||!e)})};
pe.VenueSearcher.get_day_of_week_range=function(a,c){if(6<pe.days_between_dates(a,c))return[0,1,2,3,4,5,6];if(!c||a===c)return[a.getDay()];var b=[],d=a.getDay(),e=c.getDay();b.push(d);do d+=1,6<d&&(d=0),b.push(d);while(d!==e);return b};pe.VenueSearcher.remove_event_tags=function(a){var c={};$.each(a,function(a,d){"Event Type"!==a&&(c[a]=d)});return c};
pe.VenueSearcher.venue_is_hotspot_in_date_range=function(a,c,b){if(0===c-b)return pe.VenueSearcher.venue_is_hotspot_on_date(a,c.getDay());c=pe.VenueSearcher.get_day_of_week_range(c,b);return pe.array_match(a.hotspot_days,c)};pe.VenueSearcher.venue_is_hotspot_on_date=function(a,c){return-1<a.hotspot_days.indexOf(c)};
