pe.routes.map={search_autocomplete:"{{city_id}}/search/autocomplete.ehtml/",api_user_list:"/api/user_lists/{{id}}",api_reorder_user_list:"/api/user_lists/{{id}}/reorder",api_user_list_favorites:"/api/user_lists/{{id}}/favorites",api_favorite:"/api/favorites/{{id}}",api_favorite_vote_yes:"/api/favorites/{{id}}/vote_yes",api_favorite_vote_huh:"/api/favorites/{{id}}/vote_huh",holiday:"/{{city_id}}/holidays/{{id}}-7",holiday_comments:"/services/holidays/{{id}}/comments",holiday_reactions:"/holidays/{{id}}/reactions/all",
new_holiday_reactions:"/holidays/{{id}}/reactions",holiday_calendar:"/{{city_id}}/holidays/{{id}}-7/calendar",holiday_photos:"/api/{{city_id}}/holidays/{{id}}/photos",holiday_map_venues:"/api/maps/holidays/{{slug}}/venues",holiday_map_events:"/api/maps/holidays/{{slug}}/events",venue_map_popup:"/venues/{{venue_id}}/map_popup",map_venues:"/api/cities/{{city_id}}/maps/venues",map_events:"/api/cities/{{city_id}}/maps/events",map_neighborhood_venues:"/api/maps/neighborhoods/{{neighborhood_id}}/venues",
map_neighborhood_events:"/api/maps/neighborhoods/{{neighborhood_id}}/events",map_neighborhood_endpoint_venues:"/api/maps/neighborhoods/{{neighborhood_id}}/endpoints/{{endpoint_id}}/venues",map_neighborhood_endpoint_events:"/api/maps/neighborhoods/{{neighborhood_id}}/endpoints/{{endpoint_id}}/events",user_list_map_venues:"/api/maps/users/{{user_id}}/lists/{{id}}/venues",user_list_map_events:"/api/maps/users/{{user_id}}/lists/{{id}}/events",create_button_user_dashboard_event:"/users/{{user_id}}/dashboard/buttons/{{id}}",
generate_button_user_dashboard_event:"/users/{{user_id}}/dashboard/buttons/{{id}}/generate",boxoffice:"/users/{{user_id}}/dashboard/{{id}}/boxoffice",boxoffice_check_ticket_number:"/users/{{user_id}}/dashboard/{{id}}/boxoffice/{{ticket_number}}/check",user_list:"/users/{{user_id}}/lists/{{id}}",user_lists:"/users/{{user_id}}/lists",user_comments:"/users/{{user_id}}/comments",user_reviews:"/users/{{user_id}}/reviews",list_items:"/lists/{{id}}/list_items",list_comments:"/services/lists/{{id}}/comments",
list_reactions:"/lists/{{id}}/reactions/all",new_list_reactions:"/lists/{{id}}/reactions",user_personalities:"/users/{{id}}/personalities",user:"/users/{{id}}",api_user:"/api/users/{{id}}",event:"/{{city_id}}/{{*endpoints}}/{{id}}-1",tickets:"/{{city_id}}/{{*endpoints}}/{{id}}-1/tickets",purchase_tickets:"/{{city_id}}/{{*endpoints}}/{{id}}-1/tickets/purchase",tickets_purchase_form:"/{{city_id}}/{{*endpoints}}/{{id}}-1/tickets/purchase_form",tickets_confirmation:"/{{city_id}}/{{*endpoints}}/{{id}}-1/tickets/confirmation",
api_ticket_orders:"/api/ticket_orders",api_close_ticket_order:"/api/ticket_orders/{{id}}/close",api_apply_ticket_order_promo_code:"/api/ticket_orders/apply_promo",api_remove_ticket_order_promo_code:"/api/ticket_orders/remove_promo",api_ticket_orders_disable_pending:"/api/ticket_orders/disable_pending",api_ticket_orders_countdown_seconds:"/api/ticket_orders/countdown_seconds",api_ticket_order_status:"/api/ticket_orders/{{id}}/status",admin_event_ticket_types:"/admin/events/{{event_id}}/ticket_types",
admin_event_ticket_promo_codes:"/admin/events/{{event_id}}/ticket_promo_codes",update_status_admin_event_ticket_promo_codes:"/admin/events/{{event_id}}/ticket_promo_codes/{{id}}/update_status",event_type_tags:"/api/tags/event_types",find_your_scene:"/services/find_your_scene.ehtml",missing_info:"/services/contact_messages/missing_info.ehtml",send_message:"/services/contact_messages/",subscription_select:"/services/subscriptions/web.ehtml",subscriptions_create:"/services/subscriptions/web",creeper_dialog:"/services/creeper.ehtml",
creeper_subscribe:"/services/creeper/subscribe",creeper_close:"/services/creeper/close",character:"/pe-reviewers/{{id}}.ehtml",ask_party_earth:"/api/questions",mobile_subscribe:"/services/subscriptions/mobile",client_signup_form:"/clients/forms.ehtml"};pe.routes.build_path=function(a,b){var c=pe.routes.map[a],e=c.match(/\{\{\*(.+)\}\}/);_.each(e,function(a){b[a]&&(b[a]=b[a].join("/"))});c=c.replace(/\*/,"");b=b||{};return pe.routes.clean_url(pe.templatize(c,b))};
pe.routes.clean_url=function(a){return("/"+a).replace(/#[^$\/]+/,"").replace(/(^[^?]+)([^:])\/\//,"$1$2/").replace(/\/\//g,"/")};pe.routes.current_url_params=function(){var a=pe.routes.recognize_path(window.location.pathname);return a?a.params:{}};
pe.routes.recognize_path=function(a){a=pe.routes.clean_url(a);var b,c,e=_.find(_.keys(pe.routes.map),function(e){b=pe.routes.map[e];c=RegExp(b.replace(/\//g,"\\/").replace(/\{\{[^\{\}]+\}\}/g,"(.+)"));return c.test(a)});if(e){for(var f=_.map(b.match(/\{\{[^\}]+\}\}/g),function(a){return a.replace(/\{|\}/g,"")}),g=a.match(c).slice(1,99),h={params:{}},j=function(a){return!_.isEmpty(a)},d=0;d<f.length;d++)"*"==f[d][0]&&(f[d]=f[d].replace(/\*/g,""),g[d]=_.select(g[d].replace(/\*/g,"").split("/"),j)),
h.params[f[d]]=g[d];h.path_info={name:e,template:b};return h}return!1};pe.routes.Request=function(a,b,c){pe.routes.map[a]?(this.path=a,"object"!==typeof b&&(b={id:b}),this.params=b,this.callback=c):alert("This path is not registered in the routes map.")};pe.routes.Request.factory=function(a,b,c){return new pe.routes.Request(a,b,c)};pe.routes.Request.from_current_location=function(a,b,c){b=b||{};var e=pe.routes.current_url_params();return new pe.routes.Request(a,_.extend(e,b),c)};
pe.routes.Request.prototype.ajax=function(a,b){var c="function"===typeof b?b:this.callback;$.ajax({url:this.build_path(),data:this.params,type:a,success:c})};pe.routes.Request.prototype.build_path=function(){return pe.routes.build_path(this.path,this.params)};pe.routes.Request.prototype.get=function(a){this.ajax("GET",a)};pe.routes.Request.prototype.post=function(a){this.ajax("POST",a)};
(function(){var a=function(a,b){return function(){return a.apply(b,arguments)}},b=pe,c=function(b){this.form=b;this.on_submit=a(this.on_submit,this);this.display_error=a(this.display_error,this);this.on_form_response=a(this.on_form_response,this);this.errors_container=this.form.find(".Errors");this.errors_container.hide();this.submitted=!1;this.form.submit(this.on_submit);this.submit_button=this.form.find("input[type=submit]");this.submit_button.show();this.form.find("input,select").keypress(function(a){return 13!==
a.keyCode})};c.prototype.on_form_response=function(a){$("body").css("cursor","default");if(0===a.status)return this.errors_container.hide(),window.location=pe.routes.build_path("purchase_tickets",pe.routes.current_url_params());this.submit_button.css("opacity",1);this.display_error(a.message);this.reload_table();return this.submitted=!1};c.prototype.display_error=function(a){25<a.length?this.errors_container.addClass("two_lines"):this.errors_container.removeClass("two_lines");this.errors_container.html(a);
return this.errors_container.show()};c.prototype.on_submit=function(a){a.preventDefault();this.submitted||(this.submit_form(),this.submitted=!0);return!1};c.prototype.reload_table=function(){var a,b,c;b=this.form.find(".ReloadArea");b.css("opacity",0.5);c=b.data("url");a=this.form.find('[name="ticket_order[promo]"]');0<a.length&&(c+="?promo="+a.val());return $.get(c,function(a){return b.replaceWith(a)})};c.prototype.submit_form=function(){this.submit_button.css("opacity",0.5);$("body").css("cursor",
"wait");return $.post(pe.routes.build_path("api_ticket_orders"),this.form.serialize(),this.on_form_response,"json")};b.OrderTicketsForm=c}).call(this);
