pe.PageSlideScroller=function(a,d){pe.init_widget(this,a);var b=$.extend({scroll_duration:1100,inactive_button_class:"loop_back",loop_scrolling:!0},d);this.scroller_container=this.container.find(".ScreensContainer");this.current_item=0;this.scroll_duration=b.scroll_duration;this.inactive_button_class=b.inactive_button_class;this.individual_items=this.scroller_container.find(".IndividualItem");this.single_item_width=b.single_item_width||this.individual_items.width();this.items_count=this.individual_items.length;
this.next_button=this.container.find(".NextButton");this.previous_button=this.container.find(".PreviousButton");this.page_display_container=this.container.find(".PageDisplay");this.dots_container=$(this.page_display_container.selector+" .Dot");this.dots_container.live("click",this.callback(this.dot_clicked));this.page_display_format=b.page_display_format||pe.PageSlideScroller.dots_template(this.items_count);this.loop_scrolling=b.loop_scrolling;if(this.enable_buttons=1<this.items_count){this.next_button.click(this.callback(this.next_button_clicked));
this.previous_button.click(this.callback(this.previous_button_clicked));var b=this.individual_items.first(),c=this.individual_items.last();this.loop_scrolling&&(c.clone().insertBefore(b),b.clone().insertAfter(c));this.update_display();this.update_page_display()}else this.next_button.addClass("disabled"),this.previous_button.addClass("disabled")};
pe.PageSlideScroller.dots_template=function(a){for(var a=Math.min(a,4),d=["one","two","three","four"],b="<ul class='page_count slide{{current_item_number}}'>",c=0;c<=a-1;c++)b+="<li class='Dot dot "+d[c]+"' data-page_number='"+c+"'></li>";return b+"</ul>"};
pe.PageSlideScroller.prototype.animate_scrolling=function(a){this.enable_buttons=!1;this.current_item=a;this.update_page_display();this.scroller_container.animate({left:"-"+this.compute_scroll_offset(this.current_item)+"px"},this.scroll_duration,"cubicEaseInOut",this.callback(this.update_display))};
pe.PageSlideScroller.prototype.update_display=function(){this.current_item=this.constraint_page(this.current_item);this.previous_button.toggleClass(this.inactive_button_class,0>=this.current_item);this.next_button.toggleClass(this.inactive_button_class,this.current_item>=this.items_count-1);this.scroller_container.css("left","-"+this.compute_scroll_offset(this.current_item)+"px");this.enable_buttons=!0};
pe.PageSlideScroller.prototype.update_page_display=function(){this.page_display_container.html(pe.templatize(this.page_display_format,{current_item_number:this.constraint_page(this.current_item)+1,items_count:this.items_count}))};pe.PageSlideScroller.prototype.compute_scroll_offset=function(a){return(a+(this.loop_scrolling?1:0))*this.single_item_width};
pe.PageSlideScroller.prototype.constraint_page=function(a){return this.loop_scrolling?a>=this.items_count?0:0>a?this.items_count-1:a:Math.max(Math.min(a,this.items_count-1),0)};pe.PageSlideScroller.prototype.next_button_clicked=function(){if(this.enable_buttons){var a=this.current_item+1;this.loop_scrolling||(a=Math.min(a,this.items_count-1));a!=this.current_item&&this.animate_scrolling(a)}};
pe.PageSlideScroller.prototype.previous_button_clicked=function(){if(this.enable_buttons){var a=this.current_item-1;this.loop_scrolling||(a=Math.max(a,0));a!=this.current_item&&this.animate_scrolling(a)}};pe.PageSlideScroller.prototype.dot_clicked=function(a){this.animate_scrolling($(a.currentTarget).data("page_number")-0)};
