(function(g){function n(){function a(h){h=1E12>h?d?performance.now()+performance.timing.navigationStart:b():h||b();1E3<=h-e&&(m._updateTargets(),e=h);c(a)}this.regional=[];this.regional[""]={labels:"Years Months Weeks Days Hours Minutes Seconds".split(" "),labels1:"Year Month Week Day Hour Minute Second".split(" "),compactLabels:["y","m","w","d"],whichLabels:null,digits:"0123456789".split(""),timeSeparator:":",isRTL:!1};this._defaults={until:null,since:null,timezone:null,serverSync:null,format:"dHMS",
layout:"",compact:!1,significant:0,description:"",expiryUrl:"",expiryText:"",alwaysExpire:!1,onExpiry:null,onTick:null,tickInterval:1};g.extend(this._defaults,this.regional[""]);this._serverSyncs=[];var b="function"==typeof Date.now?Date.now:function(){return(new Date).getTime()},d=window.performance&&"function"==typeof window.performance.now,c=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||
null,e=0;!c||g.noRequestAnimationFrame?(g.noRequestAnimationFrame=null,setInterval(function(){m._updateTargets()},980)):(e=window.animationStartTime||window.webkitAnimationStartTime||window.mozAnimationStartTime||window.oAnimationStartTime||window.msAnimationStartTime||b(),c(a))}g.extend(n.prototype,{markerClassName:"hasCountdown",propertyName:"countdown",_rtlClass:"countdown_rtl",_sectionClass:"countdown_section",_amountClass:"countdown_amount",_rowClass:"countdown_row",_holdingClass:"countdown_holding",
_showClass:"countdown_show",_descrClass:"countdown_descr",_timerTargets:[],setDefaults:function(a){this._resetExtraLabels(this._defaults,a);g.extend(this._defaults,a||{})},UTCDate:function(a,b,d,c,e,h,f,g){"object"==typeof b&&b.constructor==Date&&(g=b.getMilliseconds(),f=b.getSeconds(),h=b.getMinutes(),e=b.getHours(),c=b.getDate(),d=b.getMonth(),b=b.getFullYear());var k=new Date;k.setUTCFullYear(b);k.setUTCDate(1);k.setUTCMonth(d||0);k.setUTCDate(c||1);k.setUTCHours(e||0);k.setUTCMinutes((h||0)-(30>
Math.abs(a)?60*a:a));k.setUTCSeconds(f||0);k.setUTCMilliseconds(g||0);return k},periodsToSeconds:function(a){return 31557600*a[0]+2629800*a[1]+604800*a[2]+86400*a[3]+3600*a[4]+60*a[5]+a[6]},_attachPlugin:function(a,b){a=g(a);if(!a.hasClass(this.markerClassName)){var d={options:g.extend({},this._defaults),_periods:[0,0,0,0,0,0,0]};a.addClass(this.markerClassName).data(this.propertyName,d);this._optionPlugin(a,b)}},_addTarget:function(a){this._hasTarget(a)||this._timerTargets.push(a)},_hasTarget:function(a){return-1<
g.inArray(a,this._timerTargets)},_removeTarget:function(a){this._timerTargets=g.map(this._timerTargets,function(b){return b==a?null:b})},_updateTargets:function(){for(var a=this._timerTargets.length-1;0<=a;a--)this._updateCountdown(this._timerTargets[a])},_optionPlugin:function(a,b,d){a=g(a);var c=a.data(this.propertyName);if(!b||"string"==typeof b&&null==d){var e=b;return(b=(c||{}).options)&&e?b[e]:b}a.hasClass(this.markerClassName)&&(b=b||{},"string"==typeof b&&(e=b,b={},b[e]=d),b.layout&&(b.layout=
b.layout.replace(/&lt;/g,"<").replace(/&gt;/g,">")),this._resetExtraLabels(c.options,b),d=c.options.timezone!=b.timezone,g.extend(c.options,b),this._adjustSettings(a,c,null!=b.until||null!=b.since||d),b=new Date,(c._since&&c._since<b||c._until&&c._until>b)&&this._addTarget(a[0]),this._updateCountdown(a,c))},_updateCountdown:function(a,b){var d=g(a);if(b=b||d.data(this.propertyName)){d.html(this._generateHTML(b)).toggleClass(this._rtlClass,b.options.isRTL);if(g.isFunction(b.options.onTick)){var c=
"lap"!=b._hold?b._periods:this._calculatePeriods(b,b._show,b.options.significant,new Date);(1==b.options.tickInterval||0==this.periodsToSeconds(c)%b.options.tickInterval)&&b.options.onTick.apply(a,[c])}if("pause"!=b._hold&&(b._since?b._now.getTime()<b._since.getTime():b._now.getTime()>=b._until.getTime())&&!b._expiring){b._expiring=!0;if(this._hasTarget(a)||b.options.alwaysExpire)this._removeTarget(a),g.isFunction(b.options.onExpiry)&&b.options.onExpiry.apply(a,[]),b.options.expiryText&&(c=b.options.layout,
b.options.layout=b.options.expiryText,this._updateCountdown(a,b),b.options.layout=c),b.options.expiryUrl&&(window.location=b.options.expiryUrl);b._expiring=!1}else"pause"==b._hold&&this._removeTarget(a);d.data(this.propertyName,b)}},_resetExtraLabels:function(a,b){var d=!1,c;for(c in b)if("whichLabels"!=c&&c.match(/[Ll]abels/)){d=!0;break}if(d)for(c in a)c.match(/[Ll]abels[02-9]|compactLabels1/)&&(a[c]=null)},_adjustSettings:function(a,b,d){for(var c=0,c=null,e=0;e<this._serverSyncs.length;e++)if(this._serverSyncs[e][0]==
b.options.serverSync){c=this._serverSyncs[e][1];break}null!=c?(c=b.options.serverSync?c:0,a=new Date):(c=g.isFunction(b.options.serverSync)?b.options.serverSync.apply(a,[]):null,a=new Date,c=c?a.getTime()-c.getTime():0,this._serverSyncs.push([b.options.serverSync,c]));e=b.options.timezone;e=null==e?-a.getTimezoneOffset():e;if(d||!d&&null==b._until&&null==b._since)b._since=b.options.since,null!=b._since&&(b._since=this.UTCDate(e,this._determineTime(b._since,null)),b._since&&c&&b._since.setMilliseconds(b._since.getMilliseconds()+
c)),b._until=this.UTCDate(e,this._determineTime(b.options.until,a)),c&&b._until.setMilliseconds(b._until.getMilliseconds()+c);b._show=this._determineShow(b)},_destroyPlugin:function(a){a=g(a);a.hasClass(this.markerClassName)&&(this._removeTarget(a[0]),a.removeClass(this.markerClassName).empty().removeData(this.propertyName))},_pausePlugin:function(a){this._hold(a,"pause")},_lapPlugin:function(a){this._hold(a,"lap")},_resumePlugin:function(a){this._hold(a,null)},_hold:function(a,b){var d=g.data(a,
this.propertyName);if(d){if("pause"==d._hold&&!b){d._periods=d._savePeriods;var c=d._since?"-":"+";d[d._since?"_since":"_until"]=this._determineTime(c+d._periods[0]+"y"+c+d._periods[1]+"o"+c+d._periods[2]+"w"+c+d._periods[3]+"d"+c+d._periods[4]+"h"+c+d._periods[5]+"m"+c+d._periods[6]+"s");this._addTarget(a)}d._hold=b;d._savePeriods="pause"==b?d._periods:null;g.data(a,this.propertyName,d);this._updateCountdown(a,d)}},_getTimesPlugin:function(a){a=g.data(a,this.propertyName);return!a?null:"pause"==
a._hold?a._savePeriods:!a._hold?a._periods:this._calculatePeriods(a,a._show,a.options.significant,new Date)},_determineTime:function(a,b){var d;if(null==a)d=b;else if("string"==typeof a){d=a.toLowerCase();for(var c=new Date,e=c.getFullYear(),h=c.getMonth(),f=c.getDate(),g=c.getHours(),k=c.getMinutes(),c=c.getSeconds(),j=/([+-]?[0-9]+)\s*(s|m|h|d|w|o|y)?/g,l=j.exec(d);l;){switch(l[2]||"s"){case "s":c+=parseInt(l[1],10);break;case "m":k+=parseInt(l[1],10);break;case "h":g+=parseInt(l[1],10);break;case "d":f+=
parseInt(l[1],10);break;case "w":f+=7*parseInt(l[1],10);break;case "o":h+=parseInt(l[1],10);f=Math.min(f,m._getDaysInMonth(e,h));break;case "y":e+=parseInt(l[1],10),f=Math.min(f,m._getDaysInMonth(e,h))}l=j.exec(d)}d=new Date(e,h,f,g,k,c,0)}else"number"==typeof a?(d=new Date,d.setTime(d.getTime()+1E3*a)):d=a;d&&d.setMilliseconds(0);return d},_getDaysInMonth:function(a,b){return 32-(new Date(a,b,32)).getDate()},_normalLabels:function(a){return a},_generateHTML:function(a){var b=this;a._periods=a._hold?
a._periods:this._calculatePeriods(a,a._show,a.options.significant,new Date);for(var d=!1,c=0,e=a.options.significant,h=g.extend({},a._show),f=0;6>=f;f++)d|="?"==a._show[f]&&0<a._periods[f],h[f]="?"==a._show[f]&&!d?null:a._show[f],c+=h[f]?1:0,e-=0<a._periods[f]?1:0;for(var p=[!1,!1,!1,!1,!1,!1,!1],f=6;0<=f;f--)a._show[f]&&(a._periods[f]?p[f]=!0:(p[f]=0<e,e--));var k=a.options.compact?a.options.compactLabels:a.options.labels,j=a.options.whichLabels||this._normalLabels,d=function(c){var d=a.options["compactLabels"+
j(a._periods[c])];return h[c]?b._translateDigits(a,a._periods[c])+(d?d[c]:k[c])+" ":""},e=function(c){var d=a.options["labels"+j(a._periods[c])];return!a.options.significant&&h[c]||a.options.significant&&p[c]?'<span class="'+m._sectionClass+'"><span class="'+m._amountClass+'">'+b._translateDigits(a,a._periods[c])+"</span><br/>"+(d?d[c]:k[c])+"</span>":""};return a.options.layout?this._buildLayout(a,h,a.options.layout,a.options.compact,a.options.significant,p):(a.options.compact?'<span class="'+this._rowClass+
" "+this._amountClass+(a._hold?" "+this._holdingClass:"")+'">'+d(0)+d(1)+d(2)+d(3)+(h[4]?this._minDigits(a,a._periods[4],2):"")+(h[5]?(h[4]?a.options.timeSeparator:"")+this._minDigits(a,a._periods[5],2):"")+(h[6]?(h[4]||h[5]?a.options.timeSeparator:"")+this._minDigits(a,a._periods[6],2):""):'<span class="'+this._rowClass+" "+this._showClass+(a.options.significant||c)+(a._hold?" "+this._holdingClass:"")+'">'+e(0)+e(1)+e(2)+e(3)+e(4)+e(5)+e(6))+"</span>"+(a.options.description?'<span class="'+this._rowClass+
" "+this._descrClass+'">'+a.options.description+"</span>":"")},_buildLayout:function(a,b,d,c,e,h){var f=a.options[c?"compactLabels":"labels"],p=a.options.whichLabels||this._normalLabels,k=function(b){return(a.options[(c?"compactLabels":"labels")+p(a._periods[b])]||f)[b]},j=function(b,c){return a.options.digits[Math.floor(b/c)%10]},k={desc:a.options.description,sep:a.options.timeSeparator,yl:k(0),yn:this._minDigits(a,a._periods[0],1),ynn:this._minDigits(a,a._periods[0],2),ynnn:this._minDigits(a,a._periods[0],
3),y1:j(a._periods[0],1),y10:j(a._periods[0],10),y100:j(a._periods[0],100),y1000:j(a._periods[0],1E3),ol:k(1),on:this._minDigits(a,a._periods[1],1),onn:this._minDigits(a,a._periods[1],2),onnn:this._minDigits(a,a._periods[1],3),o1:j(a._periods[1],1),o10:j(a._periods[1],10),o100:j(a._periods[1],100),o1000:j(a._periods[1],1E3),wl:k(2),wn:this._minDigits(a,a._periods[2],1),wnn:this._minDigits(a,a._periods[2],2),wnnn:this._minDigits(a,a._periods[2],3),w1:j(a._periods[2],1),w10:j(a._periods[2],10),w100:j(a._periods[2],
100),w1000:j(a._periods[2],1E3),dl:k(3),dn:this._minDigits(a,a._periods[3],1),dnn:this._minDigits(a,a._periods[3],2),dnnn:this._minDigits(a,a._periods[3],3),d1:j(a._periods[3],1),d10:j(a._periods[3],10),d100:j(a._periods[3],100),d1000:j(a._periods[3],1E3),hl:k(4),hn:this._minDigits(a,a._periods[4],1),hnn:this._minDigits(a,a._periods[4],2),hnnn:this._minDigits(a,a._periods[4],3),h1:j(a._periods[4],1),h10:j(a._periods[4],10),h100:j(a._periods[4],100),h1000:j(a._periods[4],1E3),ml:k(5),mn:this._minDigits(a,
a._periods[5],1),mnn:this._minDigits(a,a._periods[5],2),mnnn:this._minDigits(a,a._periods[5],3),m1:j(a._periods[5],1),m10:j(a._periods[5],10),m100:j(a._periods[5],100),m1000:j(a._periods[5],1E3),sl:k(6),sn:this._minDigits(a,a._periods[6],1),snn:this._minDigits(a,a._periods[6],2),snnn:this._minDigits(a,a._periods[6],3),s1:j(a._periods[6],1),s10:j(a._periods[6],10),s100:j(a._periods[6],100),s1000:j(a._periods[6],1E3)},l=d;for(d=0;6>=d;d++)j="yowdhms".charAt(d),l=l.replace(RegExp("\\{"+j+"<\\}([\\s\\S]*)\\{"+
j+">\\}","g"),!e&&b[d]||e&&h[d]?"$1":"");g.each(k,function(a,b){l=l.replace(RegExp("\\{"+a+"\\}","g"),b)});return l},_minDigits:function(a,b,d){b=""+b;if(b.length>=d)return this._translateDigits(a,b);b="0000000000"+b;return this._translateDigits(a,b.substr(b.length-d))},_translateDigits:function(a,b){return(""+b).replace(/[0-9]/g,function(b){return a.options.digits[b]})},_determineShow:function(a){a=a.options.format;var b=[];b[0]=a.match("y")?"?":a.match("Y")?"!":null;b[1]=a.match("o")?"?":a.match("O")?
"!":null;b[2]=a.match("w")?"?":a.match("W")?"!":null;b[3]=a.match("d")?"?":a.match("D")?"!":null;b[4]=a.match("h")?"?":a.match("H")?"!":null;b[5]=a.match("m")?"?":a.match("M")?"!":null;b[6]=a.match("s")?"?":a.match("S")?"!":null;return b},_calculatePeriods:function(a,b,d,c){a._now=c;a._now.setMilliseconds(0);var e=new Date(a._now.getTime());a._since?c.getTime()<a._since.getTime()?a._now=c=e:c=a._since:(e.setTime(a._until.getTime()),c.getTime()>a._until.getTime()&&(a._now=c=e));var h=[0,0,0,0,0,0,
0];if(b[0]||b[1]){var f=m._getDaysInMonth(c.getFullYear(),c.getMonth()),g=m._getDaysInMonth(e.getFullYear(),e.getMonth()),g=e.getDate()==c.getDate()||e.getDate()>=Math.min(f,g)&&c.getDate()>=Math.min(f,g),g=Math.max(0,12*(e.getFullYear()-c.getFullYear())+e.getMonth()-c.getMonth()+(e.getDate()<c.getDate()&&!g||g&&60*(60*e.getHours()+e.getMinutes())+e.getSeconds()<60*(60*c.getHours()+c.getMinutes())+c.getSeconds()?-1:0));h[0]=b[0]?Math.floor(g/12):0;h[1]=b[1]?g-12*h[0]:0;c=new Date(c.getTime());f=c.getDate()==
f;g=m._getDaysInMonth(c.getFullYear()+h[0],c.getMonth()+h[1]);c.getDate()>g&&c.setDate(g);c.setFullYear(c.getFullYear()+h[0]);c.setMonth(c.getMonth()+h[1]);f&&c.setDate(g)}var k=Math.floor((e.getTime()-c.getTime())/1E3);c=function(a,c){h[a]=b[a]?Math.floor(k/c):0;k-=h[a]*c};c(2,604800);c(3,86400);c(4,3600);c(5,60);c(6,1);if(0<k&&!a._since){a=[1,12,4.3482,7,24,60,60];c=6;e=1;for(f=6;0<=f;f--)b[f]&&(h[c]>=e&&(h[c]=0,k=1),0<k&&(h[f]++,k=0,c=f,e=1)),e*=a[f]}if(d)for(f=0;6>=f;f++)d&&h[f]?d--:d||(h[f]=
0);return h}});var q=["getTimes"];g.fn.countdown=function(a){var b=Array.prototype.slice.call(arguments,1),d;d="option"==a&&(0==b.length||1==b.length&&"string"==typeof b[0])?!0:-1<g.inArray(a,q);return d?m["_"+a+"Plugin"].apply(m,[this[0]].concat(b)):this.each(function(){if("string"==typeof a){if(!m["_"+a+"Plugin"])throw"Unknown command: "+a;m["_"+a+"Plugin"].apply(m,[this].concat(b))}else m._attachPlugin(this,a||{})})};var m=g.countdown=new n})(jQuery);
(function(){pe.on_expire=function(){window.onbeforeunload=null;$(".Timer").html("0:00");alert("The time limit has been exceeded and your tickets have been released. \n\nThe purpose of the time limit is to give all fans a fair shot at tickets and ensure tickets are available to as many people as possible. We are sorry for the inconvenience.");$("body").css("cursor","wait");return pe.routes.Request.factory("api_ticket_orders_disable_pending").post(function(){return window.location=pe.event_tickets_path})};
pe.on_tick=function(){return $(".Timer").html($(".Timer").html().replace(/0(\d+):/,"$1:"))};$(function(){return pe.init_page_framework(function(){return pe.routes.Request.factory("api_ticket_orders_countdown_seconds").get(function(g){var n;n=new Date;n=new Date(n.getTime()+1E3*g.data.seconds);return $(".Timer").countdown({until:n,compact:!0,format:"MS",description:"",onExpiry:pe.on_expire,onTick:pe.on_tick})})})})}).call(this);
