pe.AjaxPaginator=function(a,b,c,d){pe.init_widget(this,a);a={cells_count:13,total_items:0,total_pages:1,per_page:10,initial_page:1,dots:"..."};"undefined"!==typeof c&&$.extend(a,c);this.cells=[];this.cells_container=this.container.find(".Cells");this.current_page=a.initial_page;this.next_button=this.container.find(".ShowNextPageButton");this.prev_button=this.container.find(".ShowPrevPageButton");this.referrer=d;this.mini_paginator_container=b;this.count_container=this.mini_paginator_container.find(".Total");
this.from_container=this.mini_paginator_container.find(".From");this.to_container=this.mini_paginator_container.find(".To");this.mini_paginator_next_button=this.mini_paginator_container.find(".ShowNextPageTopButton");this.mini_paginator_prev_button=this.mini_paginator_container.find(".ShowPrevPageTopButton");this.per_page=a.per_page;this.total_pages=a.total_pages;this.total_items=a.total_items;this.CELLS_COUNT=a.cells_count;this.DOTS_CELL_CONTENT=a.dots;this.update_display({page:this.current_page,
total_pages:this.total_pages});this.prev_button.click(this.callback(this.show_previous_page));this.next_button.click(this.callback(this.show_next_page));this.mini_paginator_prev_button.click(this.callback(this.show_previous_page));this.mini_paginator_next_button.click(this.callback(this.show_next_page))};pe.AjaxPaginator.events={PAGE_CHANGED:"AjaxPaginator_PageChanged"};
pe.AjaxPaginator.prototype.add_search_configuration=function(a){a.add_filter("page",this.current_page);a.add_filter("total_pages",this.total_pages);a.add_filter("total_results",this.total_items)};pe.AjaxPaginator.prototype.cell_clicked=function(a){this.set_current_page(parseInt($(a.target).data("page"),0))};pe.AjaxPaginator.prototype.cell_html=function(){return'<span class="PaginationCell inline_block"></span>'};
pe.AjaxPaginator.prototype.change_per_page_limit=function(a,b){this.current_page=Math.ceil(this.from()/b);this.per_page=b;this.total_pages=Math.ceil(this.total_items/this.per_page);this.fire_event(pe.AjaxPaginator.events.PAGE_CHANGED)};pe.AjaxPaginator.prototype.from=function(){return(this.current_page-1)*this.per_page+1};pe.AjaxPaginator.prototype.to=function(){return Math.min(this.current_page*this.per_page,this.total_items)};
pe.AjaxPaginator.prototype.read_search_configuration=function(a){var b=this.referrer?a.filter_value("page"):1,c=a.filter_value("per_page"),d=a.filter_value("total_pages"),a=a.filter_value("total_results");this.update_display({current_page:b,per_page:c,total_pages:d,total_results:a})};
pe.AjaxPaginator.prototype.render=function(a){var a=a||0,b=this.cell_html();this.cells_container.empty();$.each(this.cells,this.callback(function(c,d){var e=$(b).append(d);d===this.DOTS_CELL_CONTENT?e.addClass("Dots"):(e.addClass("Number").data("page",d),a==c?e.addClass("Current"):e.click(this.callback(this.cell_clicked)));this.cells_container.append(e)}));this.from_container.html(this.from()+"");this.to_container.html(this.to()+"");this.count_container.html(this.total_items+"")};
pe.AjaxPaginator.prototype.show_next_page=function(){this.current_page!==this.total_pages&&this.set_current_page(this.current_page+1)};pe.AjaxPaginator.prototype.show_previous_page=function(){1!==this.current_page&&this.set_current_page(this.current_page-1)};pe.AjaxPaginator.prototype.set_current_page=function(a){this.current_page=a;this.fire_event(pe.AjaxPaginator.events.PAGE_CHANGED)};
pe.AjaxPaginator.prototype.update_display=function(a){a=a||{};this.total_pages=a.total_pages||1;this.current_page=a.current_page||1;this.total_items=a.total_results||0;this.per_page=a.per_page||10;this.container.toggle(0<this.total_items);this.mini_paginator_container.toggle(0<this.total_items);if(0!==this.total_items){this.cells=[];var a=Math.min(this.CELLS_COUNT,this.total_pages),b=Math.floor((a-4)/2),c=0,c=this.current_page<=1+b+1?this.current_page-1:this.current_page>=this.total_pages-b-1?a-(this.total_pages-
this.current_page)-1:Math.floor(a/2);this.cells[c]=this.current_page;this.cells[0]=1;this.cells[a-1]=this.total_pages;b=0;for(b=c+1;b<a-1;b++)this.cells[b]=this.cells[b-1]+1;for(b=c-1;0<b;b--)this.cells[b]=this.cells[b+1]-1;if(1<a&&(1!=this.total_pages-this.cells[a-2]&&(this.cells[a-2]=this.DOTS_CELL_CONTENT),1!=this.cells[1]-1))this.cells[1]=this.DOTS_CELL_CONTENT;this.render(c);a=this.current_page===this.total_pages;c=1===this.current_page;this.prev_button.toggleClass("disabled",c);this.next_button.toggleClass("disabled",
a);this.mini_paginator_prev_button.toggleClass("disabled",c);this.mini_paginator_next_button.toggleClass("disabled",a)}};
