pe.mouse_position={};pe.mouse_position.x=0;pe.mouse_position.y=0;pe.mouse_position.on_mouse_move=function(a){pe.mouse_position.x=a.pageX;pe.mouse_position.y=a.pageY};pe.mouse_position.track=function(){$("body").mousemove(pe.mouse_position.on_mouse_move)};
pe.Map2=function(a,b){pe.init_widget(this,a);this.options=b;this.options.bubbles=this.options.bubbles||"ALL";this.options.min_zoom=this.options.min_zoom||11;this.zoom=b.zoom||10;this.map=new google.maps.Map(a[0],{center:new google.maps.LatLng(b.latitude,b.longitude),mapTypeControlOptions:{style:google.maps.MapTypeControlStyle.DROPDOWN_MENU},mapTypeId:b.mapTypeId,minZoom:b.min_zoom,navigationControlOptions:{style:google.maps.NavigationControlStyle.SMALL},scrollwheel:b.scrollwheel,zoom:b.zoom});var c=
new google.maps.OverlayView;c.draw=function(){};c.setMap(this.map);this.overlay=c;pe.mouse_position.track();this.tooltip_div=$('<div class="new_map_tooltip" style="display:none;"></div>');$("body").append(this.tooltip_div);this.infopopup_div=$('<div class="map_infowindow" style="display:none;"></div>');$("body").append(this.infopopup_div);this.markers=[]};pe.Map2.events={MARKER_CLICKED:"Map_MARKER_CLICKED",MARKER_HOVERED:"Map_MARKER_HOVERED",MARKER_BLURRED:"Map_MARKER_BLURRED"};
pe.Map2.marker_types={EVENT:"EVENT",USER_LOCATION:"USER_LOCATION",VENUE:"VENUE"};
pe.Map2.prototype.add_marker=function(a){var b=new google.maps.Marker({position:new google.maps.LatLng(a.latitude,a.longitude),map:this.map,icon:a.icon,cursor:"pointer",zIndex:a.z_index});b.bubble_html=a.bubble_html||"";b.popup_html=a.popup_html||"";b.type=a.type;b.object_id=a.object_id;b.z_index=a.z_index;b.clicked=!1;b.hovered=!1;var c=this;google.maps.event.addListener(b,"click",function(){c.fire_event(pe.Map2.events.MARKER_CLICKED,this)});google.maps.event.addListener(b,"mouseover",function(){c.fire_event(pe.Map2.events.MARKER_HOVERED,
this)});google.maps.event.addListener(b,"mouseout",function(){c.fire_event(pe.Map2.events.MARKER_BLURRED,this)});this.markers.push(b)};pe.Map2.prototype.find_marker_by_id=function(a){return _.detect(this.markers,function(b){return b.object_id===a})};pe.Map2.prototype.get_center_coordinates=function(){var a=this.map.getCenter();return{latitude:a.lat(),longitude:a.lng()}};
pe.Map2.prototype.highlight_marker=function(a){_.each(this.markers,function(a){this.shade_marker(a)},this);a.setIcon(pe.Map2.icon_path(a.type,a.object_id,!0));a.setZIndex(1E3)};pe.Map2.prototype.shade_marker=function(a){a.setIcon(pe.Map2.icon_path(a.type,a.object_id));a.setZIndex(a.z_index)};
pe.Map2.icon_path=function(a,b,c){if(a===pe.Map2.marker_types.USER_LOCATION)return"http://www.partyearth.com/assets/map/location.png?"+pe.assets_timestamp();a={type:a.toLowerCase(),id:pe.Map2.format_marker_id(b),timestamp:pe.assets_timestamp()};return pe.templatize(c?"http://cdn.partyearth.com/assets/map/pins/selected/map/{{id}}.png?{{timestamp}}":"http://cdn.partyearth.com/assets/map/pins/{{type}}/map/{{id}}.png?{{timestamp}}",a)};
pe.Map2.format_marker_id=function(a){return 3<a.length?"0000":"0000".substr(0,4-a.length)+a};pe.Map2.prototype.locate=function(a,b){(new google.maps.Geocoder).geocode({address:a},this.callback(function(a,d){if(d==google.maps.GeocoderStatus.OK){var e=a[0].geometry.location;this.map.setCenter(e);b&&b.success&&b.success(e)}else b&&b.fail&&b.fail()}))};pe.Map2.prototype.marker_position_on_map=function(a){var b=this.overlay.getProjection(),a=a.getPosition();return b.fromLatLngToContainerPixel(a)};
pe.Map2.prototype.marker_position_on_page=function(a){a=this.marker_position_on_map(a);return{x:this.container.offset().left+a.x,y:this.container.offset().top+a.y}};pe.Map2.marker_type=function(a){switch(a){case "EVENT":return pe.Map2.marker_types.EVENT;case "VENUE":return pe.Map2.marker_types.VENUE;case "USER_LOCATION":return pe.Map2.marker_types.USER_LOCATION;default:return alert("Unknown marker type")}};
pe.Map2.prototype.set_map_to_fit_markers=function(){if(this.markers.length){var a=new google.maps.LatLngBounds;_.each(this.markers,function(b){a.extend(b.getPosition())},this);this.map.setOptions({minZoom:null});this.map.fitBounds(a);var b=this.map.getZoom(),c=this.zoom;17<b&&this.map.setZoom(c);b>this.options.min_zoom&&(b=this.options.min_zoom);this.map.setOptions({minZoom:b})}};
pe.Map2.prototype.set_objects=function(a){$.each(this.markers,this.callback(function(a,c){c.setMap(null)}));this.markers=[];a.length&&($.each(a,this.callback(function(b,c){if(c.lat&&c.lng){var d=pe.Map2.marker_type(c.type),e=c.id;this.add_marker({type:d,icon:pe.Map2.icon_path(d,e),object_id:e,latitude:c.lat,longitude:c.lng,bubble_html:c.bubble_html,popup_html:c.popup_html,z_index:a.length-b})}})),this.set_map_to_fit_markers())};
pe.TabsSection=function(a,b){pe.init_widget(this,a);this.selected_tab="";this.tabs=this.container.find("a[rel]");this.tabs.click(this.callback(this.tab_clicked));this.select_tab(b||"all_results")};pe.TabsSection.events={CHANGED:"TabsSection_CHANGED"};pe.TabsSection.tabs={ALL_RESULTS:"all_results",THINGS_TO_DO:"things_to_do",BARS_AND_CLUBS:"bars_and_clubs",RESTAURANTS:"restaurants",EVENT_VENUES:"event_venues",EVENTS:"events",ENTERTAINERS:"entertainers",TEAMS:"teams"};
pe.TabsSection.venue_tabs={ALL_RESULTS:"all_results",THINGS_TO_DO:"things_to_do",BARS_AND_CLUBS:"bars_and_clubs",RESTAURANTS:"restaurants",EVENT_VENUES:"event_venues"};pe.TabsSection.tab_names=_.uniq(_.values(pe.TabsSection.tabs));pe.TabsSection.prototype.add_search_configuration=function(a){a.add_filter("category",this.get_selected_tab_name())};pe.TabsSection.prototype.get_selected_tab_name=function(){return this.selected_tab};
pe.TabsSection.prototype.read_search_configuration=function(a){this.select_tab(a.filter_value("category")||"all_results")};pe.TabsSection.prototype.select_tab=function(a){a=(a||"").replace(/-/g,"_");_.contains(pe.TabsSection.tab_names,a)||(a="all_results");this.selected_tab=a;this.tabs.removeClass("selected");this.tabs.filter("[rel="+a+"]").addClass("selected")};
pe.TabsSection.prototype.tab_clicked=function(a){a=$(a.currentTarget);a.hasClass("disabled")||(a=a.attr("rel")+"",this.selected_tab!=a&&(this.select_tab(a),pe.fire_global_event(pe.TabsSection.events.CHANGED,a)))};pe.TabsSection.prototype.update_tab_counters=function(a){this.tabs.addClass("disabled");_.each(pe.TabsSection.tab_names,this.callback(function(b){var c=this.tabs.filter("[rel="+b+"]"),b=a[b]||0;0!==b&&c.removeClass("disabled");c.find(".Counter").html("("+b+")")}))};
pe.MapSection=function(a,b,c){pe.init_widget(this,a);this.result_list_section=c;this.city_data=b;this.map=void 0;pe.map_floater.bind_event(pe.Floater.events.TOP_REACHED,this.callback(this.on_floater_top_reached));pe.map_floater.bind_event(pe.Floater.events.FLOATING,this.callback(this.on_floater_floating));this.update_pins();pe.bind_global_event(pe.TabsSection.events.CHANGED,this.callback(this.on_tab_changed));pe.bind_global_event(pe.ResultListSection.events.RESULT_HOVERED,this.callback(this.on_result_list_hover));
pe.bind_global_event(pe.ResultListSection.events.RESULT_BLURRED,this.callback(this.on_result_list_blur))};pe.MapSection.events={MARKER_BLURRED:"MapSection_MARKER_BLURRED",MARKER_HOVERED:"MapSection_MARKER_HIGHLIGHTED",MARKER_CLICKED:"MapSection_MARKER_CLICKED",PINS_UPDATED:"MapSection_PinsUpdated"};pe.MapSection.prototype.add_search_configuration=function(a){if(this.map){var b=this.map.get_center_coordinates();a.add_filter("map",[b.latitude,b.longitude])}};
pe.MapSection.prototype.close_button_clicked=function(a){a.clicked=!1};
pe.MapSection.prototype.create_map=function(){this.map=new pe.Map2(this.container,{latitude:this.city_data.latitude,longitude:this.city_data.longitude,mapTypeId:google.maps.MapTypeId.ROADMAP,min_zoom:7,scrollwheel:!1,zoom:this.city_data.default_zoom_level});this.map.bind_event(pe.Map2.events.MARKER_BLURRED,this.callback(this.on_marker_blur));this.map.bind_event(pe.Map2.events.MARKER_HOVERED,this.callback(this.on_marker_hover));this.map.bind_event(pe.Map2.events.MARKER_CLICKED,this.callback(this.on_marker_click))};
pe.MapSection.prototype.get_map=function(){return this.map};
pe.MapSection.prototype.on_floater_floating=function(){if(this.map){this.map.infopopup_div.appendTo(pe.map_floater.floater);this.map.tooltip_div.appendTo(pe.map_floater.floater);var a=_.detect(this.map.markers,function(a){return a.clicked}),b=_.detect(this.map.markers,function(a){return a.hovered});a&&(a=this.map.marker_position_on_map(a),this.set_popup_position(this.container,a));b&&(a=this.map.marker_position_on_map(b),this.set_hover_position(this.container,a))}};
pe.MapSection.prototype.on_floater_top_reached=function(){if(this.map){this.map.infopopup_div.appendTo("body");this.map.tooltip_div.appendTo("body");var a=_.detect(this.map.markers,function(a){return a.clicked}),b=_.detect(this.map.markers,function(a){return a.hovered});a&&(a=this.map.marker_position_on_page(a),this.set_popup_position($("body"),a));b&&(a=this.map.marker_position_on_page(b),this.set_hover_position($("body"),a))}};
pe.MapSection.prototype.on_marker_click=function(a,b){0<b.popup_html.length&&(b.clicked=!0,b.hovered=!1,this.show_popup(b));pe.fire_global_event(pe.MapSection.events.MARKER_CLICKED,[b])};pe.MapSection.prototype.on_marker_blur=function(a,b){this.map.tooltip_div.hide();b.hovered=!1;this.map.shade_marker(b);pe.fire_global_event(pe.MapSection.events.MARKER_BLURRED,[b])};
pe.MapSection.prototype.on_marker_hover=function(a,b){if(!b.clicked&&0<b.bubble_html.length){b.hovered=!0;this.map.tooltip_div.html(b.bubble_html);var c,d;this.map.tooltip_div.parent().is("body")?(c=this.map.marker_position_on_page(b),d=$("body")):(c=this.map.marker_position_on_map(b),d=this.container);this.set_hover_position(d,c);this.map.tooltip_div.show()}this.map.highlight_marker(b);pe.fire_global_event(pe.MapSection.events.MARKER_HOVERED,[b])};
pe.MapSection.prototype.set_hover_position=function(a,b){this.map.tooltip_div.css("right",a.width()-b.x+30);this.map.tooltip_div.css("top",b.y-42)};pe.MapSection.prototype.set_popup_position=function(a,b){this.map.infopopup_div.css("right",a.width()-b.x+30);this.map.infopopup_div.css("top",b.y-73)};pe.MapSection.prototype.on_result_list_blur=function(a,b){var c=this.map.find_marker_by_id(b);c&&this.map.shade_marker(c)};
pe.MapSection.prototype.on_result_list_hover=function(a,b){var c=this.map.find_marker_by_id(b);c&&this.map.highlight_marker(c)};pe.MapSection.prototype.on_tab_changed=function(a,b){var c=b!==pe.TabsSection.tabs.TEAMS&&b!==pe.TabsSection.tabs.ENTERTAINERS;c&&!this.map&&this.create_map();this.toggle(c)};
pe.MapSection.prototype.show_popup=function(a){this.map.tooltip_div.hide();this.map.infopopup_div.html(a.popup_html);var b,c;this.map.infopopup_div.parent().is("body")?(b=this.map.marker_position_on_page(a),c=$("body")):(b=this.map.marker_position_on_map(a),c=this.container);this.set_popup_position(c,b);(new pe.CloseButton($(this.map.infopopup_div),pe.CloseButton.close_methods.HIDE)).bind_event(pe.CloseButton.events.CLOSED,this.callback(this.close_button_clicked,a));pe.convert_to_rounded_corners(this.map.infopopup_div.find(".ConvertToRoundedCorners"));
this.map.infopopup_div.show()};
pe.MapSection.prototype.update_pins=function(){if(this.map){this.map.infopopup_div.hide();var a=this.result_list_section.result_list.find('.Result:not(:".Performer") .Number'),b={},c=this;0<a.length&&(b=$.map(a,function(a){var a=$(a),b="Venue"==a.data("type")?c.venue_bubble_html(a):c.event_bubble_html(a),f="Venue"==a.data("type")?c.venue_popup_html(a):c.event_popup_html(a);return{id:a.parent("li").data("number").toString(),lat:a.data("lat"),lng:a.data("lng"),type:a.data("type").toUpperCase(),bubble_html:b,
popup_html:f,venue_id:a.data("venue_id")}}));this.map.set_objects(b);pe.fire_global_event(pe.MapSection.events.PINS_UPDATED)}};
pe.MapSection.prototype.event_bubble_html=function(a){return"1"!==window.map_popups?"":"<div class='tooltip_content event'><div class='point_wrapper'><div class='point'></div><div class='inner_point'></div></div><p class='result_name'>"+a.data("venue_name")+'</p><div class="inner_divider dashed"></div><p class=\'result_types small_text\'><span class="result_date inline_block">'+$.datepicker.formatDate("M d",new Date(a.data("event_date")))+'</span><a href="'+a.data("event_path")+'">'+a.data("event_name")+
"</a></p></div>"};
pe.MapSection.prototype.event_popup_html=function(a){if("1"!==window.map_popups)return"";var b=a.parent("li"),c=b.find(".NeighborhoodLink"),c=0<c.length?'<p><span class="neighborhood_label caps small_text">neighborhood:</span>'+c.html()+"</p>":"",d=this.result_list_section.result_list.find('.Result.Event .Number[data-venue_id="'+a.data("venue_id")+'"]'),d=$.map(d,function(a){a=$(a);return{venue_name:a.data("venue_name"),name:a.data("event_name"),url:a.data("event_path"),date:new Date(a.data("event_date"))}}).sort(function(a,b){return a.date>
b.date?1:a.date<b.date?-1:0}).slice(0,3),d=$.map(d,function(a){return'<p class="event_date_name small_text"><span class="event_date inline_block">'+$.datepicker.formatDate("M d",a.date)+'</span><a href="'+a.url+'">'+a.name+"</a></p>"}).join("");return'<div class="map_infowindow_content event"><div class="CloseButton close_btn" title="Close"></div><div class="point"></div><div class="inner_point"></div>'+(_.isEmpty(a.data("venue_path"))?'<p class="venue_name nourl">'+a.data("venue_name")+"</p>":'<p><a class="venue_name inline_block black_link border_link" href="'+
a.data("venue_path")+'">'+a.data("venue_name")+"</a></p>")+c+'<p class="address">'+b.find(".AddressAndPhone").html()+'</p><p class="directions">'+a.data("get_directions_link")+'</p><div class="inner_divider dashed"></div>'+d+'<div class="inner_divider solid"></div><p class="see_all float_right"><a class="small_text border_link" href="'+a.data("venue_path")+'#schedule">SEE ALL EVENTS</a> &rarr;</p><div class="clear"></div></div>'};
pe.MapSection.prototype.venue_bubble_html=function(a){if("1"!==window.map_popups)return"";var b=a.parent("li");return"<div class='tooltip_content venue'><div class='point_wrapper'><div class='point'></div><div class='inner_point'></div></div><p class='result_name'>"+a.data("name")+"</p><p class='result_types'>"+b.find(".VenueTypes").html()+"</p></div>"};
pe.MapSection.prototype.venue_popup_html=function(a){if("1"!==window.map_popups)return"";var b=a.parent("li"),c=b.find(".NeighborhoodLink"),c=0<c.length?'<p><span class="neighborhood_label caps small_text">neighborhood:</span>'+c.html()+"</p>":"";return'<div class="map_infowindow_content venue"><div class="CloseButton close_btn" title="Close"></div><div class="point"></div><div class="inner_point"></div><p><a class="venue_name inline_block black_link border_link" href="'+a.data("path")+'">'+a.data("name")+
"</a></p>"+c+"<p>"+b.find(".PhotoWithLink").html()+'</p><p class="type"><span class="result_tag venue inline_block caps">venue</span> <span class="result_types">'+b.find(".VenueTypes").html()+'</span></p><p class="address">'+b.find(".AddressAndPhone").html()+'</p><p class="directions">'+a.data("get_directions_link")+'</p><div class="clear"></div></div>'};
