pe.EventHelperTools={};pe.EventHelperTools.autocomplete_closed=function(){pe.EventHelperTools.autocomplete_open=!1};pe.EventHelperTools.autocomplete_opened=function(){pe.EventHelperTools.autocomplete_open=!0};pe.EventHelperTools.remove_comma_at_the_end=function(a){return!a?"":a.replace(/,$/,"")};
pe.EventHelperTools.show_message=function(a,b){a.removeClass("wrong correct new").parent().find(".errors").remove().find(".message").remove();b?a.addClass("wrong").after('<span class="errors">'+b+"</span>"):a.addClass("correct")};pe.EventHelperTools.validate_url=function(a){return!a?!0:/^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i.test(a)};
pe.AutoSuggestModule=function(a,b,c){pe.init_widget(this,a);c.preFill=c.preFill||{};c.minChars=c.minChars||3;c.selectedValuesProp=c.selectedValuesProp||"value";this.options=c;this.input_field=this.container.find(".AutoSuggestInput");this.input_field.autoSuggest(b,this.options);this.selected_entries_container=this.container.find(".as-selections");this.selected_data_ids_field=this.container.find(".as-values")};
pe.AutoSuggestModule.prototype.add_entries=function(a){a&&0!==a.length&&$.each(a,this.callback(function(a,c){this.add_entry(c)}))};pe.AutoSuggestModule.prototype.add_entry=function(a){if(0>$.inArray(a[this.options.selectedValuesProp].toString(),this.val().split(",")))window.AutoSuggest_hacks[this.input_field[0].id](a,Math.floor(1001*Math.random()).toString())};pe.AutoSuggestModule.prototype.last_li=function(){return this.selected_entries_container.find(".as-selection-item:last")};
pe.AutoSuggestModule.prototype.last_value=function(){return _.last(this.val().split(","))};pe.AutoSuggestModule.prototype.remove_last_entry=function(){this.last_li().find(".as-close").click()};pe.AutoSuggestModule.prototype.replace_last_entry=function(a){this.remove_last_entry();this.add_entry(a)};pe.AutoSuggestModule.prototype.set_val=function(a){a&&this.selected_data_ids_field.val(a+",")};pe.AutoSuggestModule.prototype.val=function(){return pe.EventHelperTools.remove_comma_at_the_end(this.selected_data_ids_field.val().toString())};
pe.accentMap={"&":"and","\u00e0":"a","\u00e1":"a","\u00e2":"a","\u00e3":"a","\u00e4":"a","\u00e5":"a","\u00e7":"c","\u00c0":"a","\u00c1":"a","\u00e8":"e","\u00e9":"e","\u00ea":"e","\u00eb":"e","\u00c8":"e","\u00c9":"e","\u00ec":"i","\u00f1":"n","\u00ed":"i","\u00ee":"i","\u00ef":"i","\u00f2":"o","\u00f3":"o","\u00f4":"o","\u00f5":"o","\u00f6":"o","\u00f9":"u","\u00fa":"u","\u00fb":"u","\u00fc":"u","!":"i",$:"s","-":""," ":"","'":""};
pe.animated_scrolling=function(a,b){if(0!==a.length){var c=a.offset().top-(b||25);$("html,body").stop().animate({scrollTop:c+"px"},800,"cubicEaseInOut",function(){return!1})}};pe.scrolling=function(a,b){if(0!==a.length){var c=a.offset().top-(b||25);$("html,body").scrollTop(c)}};pe.days_of_week="Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(",");pe.array_contains=function(a,b){return _.isArray(b)?0===_.difference(b,a).length:-1<_.indexOf(a,b)};
pe.arrays_equal=function(a,b){if(!a&&!b||!a&&0===b.length||0===a.length&&!b)return!0;if(a.length!=b.length)return!1;for(var c=a.sort(),d=b.sort(),e=0,f=a.length;e<f;e++)if(c[e]!==d[e])return!1;return!0};pe.array_match=function(a,b){var c=!1;$.each(a,function(a,e){if(-1<b.indexOf(e))return c=!0,!1});return c};pe.array_merge=function(a,b){var c=a.concat(b);c.sort();return c};
pe.array_remove=function(a,b){return!a?a:pe.is_array(b)?$.grep(a,function(a){return-1===b.indexOf(a)}):$.grep(a,function(a){return a!==b})};pe.assign_photo_size=function(a,b,c){return!a?"/assets/no_image_"+c+".png":"original"===b?a.replace("xxx.jpg",b+".jpg"):a.replace("xxx.jpg","s"+b+".jpg")};pe.remove_timestamp_from_asset_url=function(a){return a.split("?")[0]};pe.browser_is_ie8=function(){return $.browser.msie&&"8.0"===$.browser.version};
pe.build_dob_field_name=function(a,b,c){return[a||"user","[",b?b+"_":"","dob(",c,"i)]"].join("")};pe.capitalise_first_letter=function(a){return null===a?"":a.charAt(0).toUpperCase()+a.slice(1)};pe.classes_starting_with=function(a,b){return $.map(a.attr("class").split(/\s+/),function(a){if(pe.string_starts_with(a,b))return a})};pe.compare=function(a,b){return pe.is_array(a)&&pe.is_array(b)?pe.arrays_equal(a,b):a===b};
pe.convert_to_rounded_corners=function(a){a=a||$(".ConvertToRoundedCorners");a.each(function(a,c){var d=$(c);d.removeClass("ConvertToRoundedCorners");d.addClass("rounded_corner_wrapper");$('<div class="rounded_corner top_left"></div>').appendTo(d);$('<div class="rounded_corner top_right"></div>').appendTo(d);$('<div class="rounded_corner bottom_left"></div>').appendTo(d);$('<div class="rounded_corner bottom_right"></div>').appendTo(d)});return a};
pe.convert_to_tabbed_pod=function(a,b){return $.map(a,function(a){a=$(a);if(!a.hasClass("ConvertToTabbedPod"))return alert("format_tabbed_pod: element to convert must have class ConvertToTabbedPod. It only has "+a[0].className);var d=a.children("ul");d.addClass("tab");d.children("li").each(function(a,b){var b=$(b),c=b.html();b.html(pe.templatize('<div class="left_end pod_sprite float_left"></div>{{content}}<div class="right_end pod_sprite float_left"></div>',{content:c}))});var e=d.html();d.remove();
var d=a.html(),f=pe.classes_starting_with(a,"width");if(0===f.length)return alert("no width class found");if(1<f.length)return alert("more than 1 width class found");var g=f[0].substr(5);a.addClass("tabs");a.removeClass("ConvertToTabs");a.removeClass(f[0]);a.html(pe.templatize('<div><table class="width{{width}}" cellpadding="0" cellspacing="0"><tbody><tr><td class="header" colspan="4"><div class="header_row"><ul class="tab">{{headers}}</ul><div class="mid_section"></div><div class="right_corner pod_sprite"></div></div></td></tr><tr class="content_container"><td class="left_side pod_sides"></td><td class="content">{{content}}</td><td class="right_side pod_sides"></td></tr><tr class="footer_row"><td class="left_corner pod_sprite"></td><td class="mid_section"></td><td class="right_corner pod_sprite"></td></tr></tbody></table></div>',
{width:g,headers:e,content:d}));var e=a.children().tabs(b),h=["first","second","third","fourth"];a.find("ul.tab li").each(function(a,b){$(b).addClass(h[a])});return e})};
pe.new_convert_to_tabbed_pod=function(a,b){return $.map(a,function(a){a=$(a);if(!a.hasClass("ConvertToTabbedPod"))return alert("format_tabbed_pod: element to convert must have class ConvertToTabbedPod. It only has "+a[0].className);var d=a.children("ul"),e=d.html();d.remove();var d=a.html(),f=pe.classes_starting_with(a,"width");if(0===f.length)return alert("no width class found");if(1<f.length)return alert("more than 1 width class found");var g=f[0].substr(5);a.addClass("tabs");a.removeClass("ConvertToTabs");
a.removeClass(f[0]);a.html(pe.templatize('<div class="width{{width}}"><ul class="tab">{{headers}}</ul>{{content}}</div>',{width:g,headers:e,content:d}));var e=a.children().tabs(b),h=["first","second","third","fourth"];a.find("ul.tab li").each(function(a,b){$(b).addClass(h[a])});return e})};pe.date_string=function(a){return"string"===typeof a?a:a.getMonth()+1+"/"+a.getDate()+"/"+a.getFullYear()};
pe.days_between_dates=function(a,b){var c="string"===typeof a?Date.parse(a):a,d="string"===typeof b?Date.parse(b):b;return Math.abs(Math.floor((c-d)/864E5))};pe.event_search_text=function(a){var b=[a.name,a.description,a.location_name,a.category,a.neighborhood_name,a.neighborhood_id];a.tags&&$.each(a.tags,function(a,d){b.push(d)});a.performer_names&&$.each(a.performer_names,function(a,d){b.push(d)});return b.join(" ")};pe.fetch_photo_id_from_url=function(a){return a.split("/photos/")[1]};
pe.fix_ie7_rendering_bug=function(){$(".ConvertToTabbedPod").addClass("IeSucks")};pe.format_date=function(a){return a.getMonth()+1+"/"+a.getDate()+"/"+a.getFullYear()};pe.format_price=function(a){var b=Math.floor(a/100).toString(),a=(a%100).toString();2>a.length&&(a="0"+a);return"$"+b+"."+a};pe.format_duration=function(a,b){if(!a)return"0:00";var c=Math.floor(a%60);return pe.string_padding_left(Math.floor(a/60).toString(),b||1,"0")+":"+pe.string_padding_left(c.toString(),2,"0")};
pe.get_url_parameter=function(a,b){var c=RegExp("[\\?&]"+b+"=([^&]+)","i").exec(a);return c?c[1]:null};pe.hash_length=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};pe.hashes_equal=function(a,b){if(a===b)return!0;if(pe.hash_length(a)!=pe.hash_length(b))return!1;for(var c in a){var d=a[c],e=b[c];if(pe.is_array(d)){if(!pe.arrays_equal(d,e))return!1}else if(d!==e)return!1}return!0};
pe.hashes_match=function(a,b){for(var c in a){var d=a[c],e=b[c];if(pe.is_array(d)){if(!pe.array_contains(e,d))return!1}else if(d!==e)return!1}return!0};pe.https=function(a){return-1===window.location.href.indexOf("https://")?a:a.replace("http://","https://")};pe.inject=function(a,b,c){var d=b;$.each(a,function(a,b){d=c(d,b)});return d};pe.install_easing=function(){jQuery.easing.cubicEaseInOut=function(a,b,c,d){b=c+d;return 1>(a/=0.5)?b/2*a*a*a+c:b/2*((a-=2)*a*a+2)+c}};
pe.is_array=function(a){return!(!a||!("object"===typeof a&&"number"===typeof a.length&&"function"===typeof a.splice&&!a.propertyIsEnumerable("length")))};pe.is_valid_credit_card_number=function(a){return!!a.match(/^\d{4}(\s*|\s*\-\s*)?\d{4}(\s*|\s*\-\s*)?\d{4}(\s*|\s*\-\s*)?\d{4}$/)};pe.is_valid_date=function(a){return!a.match(/^(\d{1,2})(\/|-)(\d{1,2})(\/|-)(\d{4})$/)?!1:a!==$.datepicker.formatDate("m/d/yy",new Date(a))?a===$.datepicker.formatDate("mm/dd/yy",new Date(a)):!0};
pe.is_valid_zip_code=function(a){return!!a.match(/^\d{5}(\s*\-\s*\d{4})?$/)};pe.load=function(a){pe.assert(a,"error loading data");return a};pe.link_title_for_city=function(a){return"See the latest hotspots and events happening in "+a+"."};pe.link_title_for_city_party_climate=function(a){return"Check out the overview and photos of "+a+"."};
pe.link_title_for_event=function(a,b){return b?"Check out event details, photos and videos of "+a+" at "+b+".":"Check out event details, photos and videos of "+a+"."};pe.link_title_for_neighborhood=function(a,b){return"Check out "+a+" description, photos, and venues in "+b+"."};pe.link_title_for_performer=function(a){return"See the latest "+a+" schedule, photos, videos and news."};
pe.link_title_for_reviewer=function(a){switch(a){case "Lucas":return"Meet Lucas, the quintessential fun- loving, pub-crawling \u201cguy\u2019s guy\u201d. Learn about his personality and ratings.";case "Adriana":return"Meet Adriana, the epitome of a cosmopolitan girl. Learn about her personality and ratings.";case "Jonah":return"Meet Jonah, an affable, non-mainstream guy with natural curiosity about people and cultures. Learn about his personality and ratings.";case "Emma":return"Meet Emma, a lively, witty, and sociable \u201cgirl next door\u201d. Learn about her personality and ratings.";
case "All":return"Meet Lucas, Adriana, Jonah and Emma. Learn how their personalities can help you maximize your social experiences in your city and your travels."}};pe.link_title_for_venue=function(a,b,c){return c?"Check out the review, photos, videos, map and events schedule of "+a+" - "+c+" in "+b+".":"Check out the review, photos, videos, map and events schedule of "+a+" in "+b+"."};
pe.normalize=function(a){for(var b="",c=0,d=a.length;c<d;c++)var e=a.charAt(c),f=pe.accentMap[e],b=b+("undefined"===typeof f?e:f);return b};pe.object_hash_from_array=function(a){var b={};$.each(a,function(a,d){b[d.id]=d});return b};pe.object_length=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};pe.parse_price=function(a){return Math.ceil(100*parseFloat(a.substring(1)))};
pe.prepare_autocomplete_data=function(a){var b=[];$.each(a,function(a,d){$.each(d,function(d,f){f.category=a;b.push(f)})});return b};pe.remove_anchor_from_url=function(a){return a?a.split("#")[0]:""};pe.set_autocomplete_source=function(a,b,c){var d=RegExp($.ui.autocomplete.escapeRegex(pe.normalize(b.term)),"i");c($.grep(pe.prepare_autocomplete_data(a),function(a){a=a.label||a.value||a;return d.test(a)||d.test(pe.normalize(a))}))};
pe.shuffle_array=function(a){if(!a)return[];for(var b,c,d=a.length;d;)b=parseInt(Math.random()*d,10),c=a[--d],a[d]=a[b],a[b]=c;return a};pe.string_padding_left=function(a,b,c){for(;a.length<b;)a=c+a;return a};pe.structured_tags_as_flat_array=function(a){var b=[];$.each(a,function(a,d){$.merge(b,d)});return b};pe.text_contains_query=function(a,b){var c=b.split(" "),d=!0;$.each(c,function(b,c){if(-1===a.indexOf(c))return d=!1,!0});return d};pe.today_date_string=function(){return pe.date_string(new Date)};
pe.venue_search_text=function(a){var b=[a.name,a.description,a.address,a.hotspot_text,a.neighborhood_name];a.types&&$.each(a.types,function(a,d){b.push(d)});a.tags&&$.each(a.tags,function(a,d){b.push(d)});return b.join(" ")};pe.xor=function(a,b){return!!(a?!b:b)};
pe.NewPerformerDialogForm=function(a,b,c,d){pe.init_widget(this,a);this.success_callback_method=c;this.cancel_callback_method=d;this.dialog_box=$(this.dialog_html(b));this.performer_name_input=this.dialog_box.find(".PerformerName");this.performer_url_input=this.dialog_box.find(".PerformerURL");this.performer_description_input=this.dialog_box.find(".PerformerDescription");this.dialog_box.dialog({modal:!0,show:!1,close:this.callback(this.close_button_clicked),buttons:{"Create Performer":this.callback(this.create_button_clicked),
Close:this.callback(this.close_button_clicked)}})};pe.NewPerformerDialogForm.prototype.close_button_clicked=function(){this.destroy_dialog();this.cancel_callback_method()};
pe.NewPerformerDialogForm.prototype.create_button_clicked=function(){var a=this.performer_name_input.val();if(!a)return pe.EventHelperTools.show_message(this.performer_name_input,"Name is required"),!1;if(150<a.length)return pe.EventHelperTools.show_message(this.performer_name_input,"Name is too long"),!1;var b=this.performer_url_input.val();if(b&&!pe.EventHelperTools.validate_url(b))return pe.EventHelperTools.show_message(this.performer_url_input,"Please input a valid url"),!1;$.ajax({url:"/admin/events_admin/performer_create",
type:"POST",data:{name:a,url:b,description:this.performer_description_input.val()},error:pe.ajax_error,success:this.callback(function(a){a.error?pe.EventHelperTools.show_message(this.performer_name_input,a.error):(this.destroy_dialog(),this.success_callback_method(a))})})};pe.NewPerformerDialogForm.prototype.destroy_dialog=function(){this.dialog_box.dialog("destroy");this.dialog_box.remove()};
pe.NewPerformerDialogForm.prototype.dialog_html=function(a){return'<div title="Create Performer"><ul><li><label><strong>Only Entertainer Type can be created in the Events Importer</strong></label><br></li><li><label for="performer_name">Name</label> <input name="performer_name" class="PerformerName" value="'+a+'"></li><li><label for="performer_url">Official Site</label> <input name="performer_url" class="PerformerURL" value=""></li><li><label for="performer_description">Description</label> <textarea name="performer_description" class="PerformerDescription"></textarea></li></ul></div>'};
pe.PerformerAutocomplete=function(a,b){pe.init_widget(this,a);this.performer_autocomplete_field=this.container.find(".PerformerAutocompleteInput");this.performer_autocomplete_field.blur(this.callback(this.performer_autocomplete_field_blurred));this.autosuggest_module=new pe.AutoSuggestModule(this.container,b,{startText:"",emptyText:"Press Tab or Type Comma to create a performer",selectedItemProp:"label",selectedValuesProp:"value",searchObjProps:"search",queryParam:"term",neverSubmit:!0,preFill:this.performer_autocomplete_field.data("event-data"),
resultClick:this.callback(this.search_result_clicked),selectionAdded:this.callback(this.search_result_selection_added)});this.last_valid_input=this.val()};pe.PerformerAutocomplete.events={CHANGED:"PerformerAutocomplete_CHANGED",SELECTED:"PerformerAutocomplete_SELECTED"};pe.PerformerAutocomplete.prototype.as_enum=function(){return{performer_ids:this.val().split(",")}};
pe.PerformerAutocomplete.prototype.add_performers=function(a){this.autosuggest_module.add_entries(a);this.last_valid_input=this.val();if(a&&0<a.length){var b=_.flatten($.map(a,function(a){return a.content_tag_ids})),a=_.flatten($.map(a,function(a){return a.type_ids}));this.fire_event(pe.PerformerAutocomplete.events.SELECTED,{content_tag_ids:b,type_ids:a})}};pe.PerformerAutocomplete.prototype.display_message=function(a){pe.EventHelperTools.show_message(this.performer_autocomplete_field,a)};
pe.PerformerAutocomplete.prototype.open_new_performer_dialog_form=function(){new pe.NewPerformerDialogForm(this.container,this.performer_autocomplete_field.val(),this.callback(this.replace_last_performer),this.callback(this.remove_last_selected_performer))};pe.PerformerAutocomplete.prototype.performer_autocomplete_field_blurred=function(){this.value_changed()&&(this.last_valid_input=this.val(),this.fire_event(pe.PerformerAutocomplete.events.CHANGED,this.as_enum()));this.display_message("")};
pe.PerformerAutocomplete.prototype.remove_last_selected_performer=function(){this.autosuggest_module.remove_last_entry()};pe.PerformerAutocomplete.prototype.replace_last_performer=function(a){this.autosuggest_module.replace_last_entry(a)};pe.PerformerAutocomplete.prototype.search_result_clicked=function(a){this.fire_event(pe.PerformerAutocomplete.events.SELECTED,{content_tag_ids:a.attributes.content_tag_ids,type_ids:a.attributes.type_ids})};
pe.PerformerAutocomplete.prototype.search_result_selection_added=function(){this.autosuggest_module&&this.performer_autocomplete_field.val()===this.autosuggest_module.last_value()&&this.open_new_performer_dialog_form()};pe.PerformerAutocomplete.prototype.val=function(){return this.autosuggest_module.val()};pe.PerformerAutocomplete.prototype.value_changed=function(){return this.last_valid_input!==this.val()};
