pe.EventHelperTools={};pe.EventHelperTools.autocomplete_closed=function(){pe.EventHelperTools.autocomplete_open=!1};pe.EventHelperTools.autocomplete_opened=function(){pe.EventHelperTools.autocomplete_open=!0};pe.EventHelperTools.remove_comma_at_the_end=function(a){return!a?"":a.replace(/,$/,"")};
pe.EventHelperTools.show_message=function(a,c){a.removeClass("wrong correct new").parent().find(".errors").remove().find(".message").remove();c?a.addClass("wrong").after('<span class="errors">'+c+"</span>"):a.addClass("correct")};pe.EventHelperTools.validate_url=function(a){return!a?!0:/^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i.test(a)};
pe.AutoSuggestModule=function(a,c,b){pe.init_widget(this,a);b.preFill=b.preFill||{};b.minChars=b.minChars||3;b.selectedValuesProp=b.selectedValuesProp||"value";this.options=b;this.input_field=this.container.find(".AutoSuggestInput");this.input_field.autoSuggest(c,this.options);this.selected_entries_container=this.container.find(".as-selections");this.selected_data_ids_field=this.container.find(".as-values")};
pe.AutoSuggestModule.prototype.add_entries=function(a){a&&0!==a.length&&$.each(a,this.callback(function(a,b){this.add_entry(b)}))};pe.AutoSuggestModule.prototype.add_entry=function(a){if(0>$.inArray(a[this.options.selectedValuesProp].toString(),this.val().split(",")))window.AutoSuggest_hacks[this.input_field[0].id](a,Math.floor(1001*Math.random()).toString())};pe.AutoSuggestModule.prototype.last_li=function(){return this.selected_entries_container.find(".as-selection-item:last")};
pe.AutoSuggestModule.prototype.last_value=function(){return _.last(this.val().split(","))};pe.AutoSuggestModule.prototype.remove_last_entry=function(){this.last_li().find(".as-close").click()};pe.AutoSuggestModule.prototype.replace_last_entry=function(a){this.remove_last_entry();this.add_entry(a)};pe.AutoSuggestModule.prototype.set_val=function(a){a&&this.selected_data_ids_field.val(a+",")};pe.AutoSuggestModule.prototype.val=function(){return pe.EventHelperTools.remove_comma_at_the_end(this.selected_data_ids_field.val().toString())};
pe.RecurringParentAutocomplete=function(a,c){pe.init_widget(this,a);this.autosuggest_input_field=this.container.find(".RecurringParentAutocompleteInput");this.autosuggest_input_field.blur(this.callback(this.autosuggest_input_field_blurred));this.autosuggest_module=new pe.AutoSuggestModule(this.container,c,{startText:"",emptyText:"No recurring event found",queryParam:"term",selectedItemProp:"label",selectedValuesProp:"value",searchObjProps:"label",neverSubmit:!0,selectionLimit:1,preFill:this.autosuggest_input_field.data("event-data"),
selectionAdded:this.callback(this.search_result_selection_added),selectionRemoved:this.callback(this.selection_removed)});this.last_valid_input=this.val()};pe.RecurringParentAutocomplete.events={CHANGED:"RecurringParentAutocomplete_CHANGED",REMOVED:"RecurringParentAutocomplete_REMOVED",SELECTED:"RecurringParentAutocomplete_SELECTED"};pe.RecurringParentAutocomplete.prototype.as_enum=function(){return{recurring_parent_id:this.val()}};
pe.RecurringParentAutocomplete.prototype.autosuggest_input_field_blurred=function(){this.value_changed()&&(this.last_valid_input=this.val(),this.fire_event(pe.RecurringParentAutocomplete.events.CHANGED,this.as_enum()));this.display_message("")};pe.RecurringParentAutocomplete.prototype.display_message=function(a){pe.EventHelperTools.show_message(this.autosuggest_input_field,a)};
pe.RecurringParentAutocomplete.prototype.search_result_selection_added=function(){this.autosuggest_module&&(this.autosuggest_input_field.val()===this.autosuggest_module.last_value()?(this.autosuggest_module.remove_last_entry(),this.display_message("Cannot create recurring parent. Please select from list")):$.ajax({url:"/admin/events_admin/recurring_parent_event_data",data:{recurring_parent_id:this.val()},error:pe.ajax_error,success:this.callback(function(a){a.error?(this.autosuggest_module.remove_last_entry(),
this.display_message(a.error)):this.fire_event(pe.RecurringParentAutocomplete.events.SELECTED,a)})}))};pe.RecurringParentAutocomplete.prototype.selection_removed=function(a){$(a).remove();this.fire_event(pe.RecurringParentAutocomplete.events.REMOVED,null)};pe.RecurringParentAutocomplete.prototype.value_changed=function(){return this.last_valid_input!==this.val()};pe.RecurringParentAutocomplete.prototype.val=function(){return this.autosuggest_module.val()};
