pe.EventHelperTools={};pe.EventHelperTools.autocomplete_closed=function(){pe.EventHelperTools.autocomplete_open=!1};pe.EventHelperTools.autocomplete_opened=function(){pe.EventHelperTools.autocomplete_open=!0};pe.EventHelperTools.remove_comma_at_the_end=function(a){return!a?"":a.replace(/,$/,"")};
pe.EventHelperTools.show_message=function(a,b){a.removeClass("wrong correct new").parent().find(".errors").remove().find(".message").remove();b?a.addClass("wrong").after('<span class="errors">'+b+"</span>"):a.addClass("correct")};pe.EventHelperTools.validate_url=function(a){return!a?!0:/^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i.test(a)};
pe.AutoSuggestModule=function(a,b,c){pe.init_widget(this,a);c.preFill=c.preFill||{};c.minChars=c.minChars||3;c.selectedValuesProp=c.selectedValuesProp||"value";this.options=c;this.input_field=this.container.find(".AutoSuggestInput");this.input_field.autoSuggest(b,this.options);this.selected_entries_container=this.container.find(".as-selections");this.selected_data_ids_field=this.container.find(".as-values")};
pe.AutoSuggestModule.prototype.add_entries=function(a){a&&0!==a.length&&$.each(a,this.callback(function(a,c){this.add_entry(c)}))};pe.AutoSuggestModule.prototype.add_entry=function(a){if(0>$.inArray(a[this.options.selectedValuesProp].toString(),this.val().split(",")))window.AutoSuggest_hacks[this.input_field[0].id](a,Math.floor(1001*Math.random()).toString())};pe.AutoSuggestModule.prototype.last_li=function(){return this.selected_entries_container.find(".as-selection-item:last")};
pe.AutoSuggestModule.prototype.last_value=function(){return _.last(this.val().split(","))};pe.AutoSuggestModule.prototype.remove_last_entry=function(){this.last_li().find(".as-close").click()};pe.AutoSuggestModule.prototype.replace_last_entry=function(a){this.remove_last_entry();this.add_entry(a)};pe.AutoSuggestModule.prototype.set_val=function(a){a&&this.selected_data_ids_field.val(a+",")};pe.AutoSuggestModule.prototype.val=function(){return pe.EventHelperTools.remove_comma_at_the_end(this.selected_data_ids_field.val().toString())};
pe.CityAutocomplete=function(a,b){pe.init_widget(this,a);this.city_input_field=this.container.find(".CityAutocompleteInput");this.city_input_field.blur(this.callback(this.city_input_field_blurred));this.city_ids=$.map(b,function(a){return a.value.toString()});this.autosuggest_module=new pe.AutoSuggestModule(this.container,b,{startText:"",emptyText:"No city found",selectedItemProp:"label",selectedValuesProp:"value",searchObjProps:"label",neverSubmit:!0,selectionLimit:1,preFill:this.city_input_field.data("event-data"),
selectionAdded:this.callback(this.search_result_selection_added)});this.last_valid_input=this.val()};pe.CityAutocomplete.events={CHANGED:"CityAutocomplete_CHANGED"};pe.CityAutocomplete.prototype.add_cities=function(a){this.autosuggest_module.add_entries(a);this.last_valid_input=this.val()};pe.CityAutocomplete.prototype.as_enum=function(){return{city_ids:this.val().split(",")}};
pe.CityAutocomplete.prototype.city_input_field_blurred=function(){this.value_changed()&&(this.last_valid_input=this.val(),this.fire_event(pe.CityAutocomplete.events.CHANGED,this.as_enum()));this.display_message("")};pe.CityAutocomplete.prototype.display_message=function(a){pe.EventHelperTools.show_message(this.city_input_field,a)};
pe.CityAutocomplete.prototype.search_result_selection_added=function(){this.autosuggest_module&&!pe.array_contains(this.city_ids,this.autosuggest_module.last_value())&&(this.autosuggest_module.remove_last_entry(),this.display_message("Please select cities from the list."))};pe.CityAutocomplete.prototype.val=function(){return this.autosuggest_module.val()};pe.CityAutocomplete.prototype.value_changed=function(){return this.last_valid_input!==this.val()};
pe.ContentTagsAutocomplete=function(a,b){pe.init_widget(this,a);this.content_tags_input_field=this.container.find(".ContentTagsAutocompleteInput");this.content_tags_input_field.blur(this.callback(this.content_tags_input_field_blurred));this.content_tag_ids=$.map(b,function(a){return a.value.toString()});this.autosuggest_module=new pe.AutoSuggestModule(this.container,b,{selectedItemProp:"label",selectedValuesProp:"value",searchObjProps:"label",startText:"",minChars:2,neverSubmit:!0,preFill:this.content_tags_input_field.data("event-data"),
selectionAdded:this.callback(this.search_result_selection_added)});this.last_valid_input=this.val()};pe.ContentTagsAutocomplete.events={CHANGED:"ContentTagsAutocomplete_CHANGED"};pe.ContentTagsAutocomplete.prototype.add_content_tags=function(a){this.autosuggest_module.add_entries(a);this.last_valid_input=this.val()};pe.ContentTagsAutocomplete.prototype.as_enum=function(){return{content_tag_ids:this.val().split(",")}};
pe.ContentTagsAutocomplete.prototype.content_tags_input_field_blurred=function(){this.value_changed()&&(this.last_valid_input=this.val(),this.fire_event(pe.ContentTagsAutocomplete.events.CHANGED,this.as_enum()));pe.EventHelperTools.show_message(this.content_tags_input_field,"")};
pe.ContentTagsAutocomplete.prototype.search_result_selection_added=function(){this.autosuggest_module&&!pe.array_contains(this.content_tag_ids,this.autosuggest_module.last_value())&&(this.autosuggest_module.remove_last_entry(),pe.EventHelperTools.show_message(this.content_tags_input_field,"Please select tags from the list."))};pe.ContentTagsAutocomplete.prototype.val=function(){return this.autosuggest_module.val()};
pe.ContentTagsAutocomplete.prototype.value_changed=function(){return this.val()!==this.last_valid_input};
pe.EndpointAutocomplete=function(a,b){pe.init_widget(this,a);this.endpoint_input_field=this.container.find(".EndpointAutocompleteInput");this.endpoint_input_field.blur(this.callback(this.endpoint_input_field_blurred));this.endpoint_ids=$.map(b,function(a){return a.value.toString()});this.autosuggest_module=new pe.AutoSuggestModule(this.container,b,{startText:"",emptyText:"No endpoint found",selectedItemProp:"label",selectedValuesProp:"value",searchObjProps:"search",neverSubmit:!0,selectionLimit:1,
preFill:this.endpoint_input_field.data("event-data"),selectionAdded:this.callback(this.search_result_selection_added),selectionRemoved:this.callback(this.selection_removed)});this.last_valid_input=this.val()};pe.EndpointAutocomplete.events={CHANGED:"EndpointAutocomplete_CHANGED",REMOVED:"EndpointAutocomplete_REMOVED"};
pe.EndpointAutocomplete.prototype.add_endpoint=function(a){a&&(this.val()?this.autosuggest_module.replace_last_entry(a[0]):this.autosuggest_module.add_entries(a),this.last_valid_input=this.val())};pe.EndpointAutocomplete.prototype.as_enum=function(){return{ordered_endpoint_ids:this.val().split(",")}};
pe.EndpointAutocomplete.prototype.endpoint_input_field_blurred=function(){this.val()?(this.value_changed()&&(this.last_valid_input=this.val(),this.fire_event(pe.EndpointAutocomplete.events.CHANGED,this.as_enum())),this.display_message("")):this.display_message("Endpoint is required")};pe.EndpointAutocomplete.prototype.display_message=function(a){pe.EventHelperTools.show_message(this.endpoint_input_field,a)};pe.EndpointAutocomplete.prototype.restore_value=function(){this.autosuggest_module.set_val(this.last_valid_input)};
pe.EndpointAutocomplete.prototype.search_result_selection_added=function(){this.autosuggest_module&&!pe.array_contains(this.endpoint_ids,this.autosuggest_module.last_value())&&(this.autosuggest_module.remove_last_entry(),this.display_message("Please select endpoints from the list."))};pe.EndpointAutocomplete.prototype.selection_removed=function(a){this.fire_event(pe.EndpointAutocomplete.events.REMOVED,a)};pe.EndpointAutocomplete.prototype.val=function(){return this.autosuggest_module.val()};
pe.EndpointAutocomplete.prototype.value_changed=function(){return this.last_valid_input!==this.val()};pe.EventDatesTextModule=function(a){pe.init_widget(this,a);this.dates_input_field=this.container.find(".EventDatesTextInput");this.dates_input_field.blur(this.callback(this.dates_input_field_blurred));this.last_valid_input=this.val()};pe.EventDatesTextModule.events={CHANGED:"EventDatesTextModule_CHANGED"};pe.EventDatesTextModule.prototype.as_enum=function(){return{event_dates_text:this.val()}};
pe.EventDatesTextModule.prototype.dates_input_field_blurred=function(){this.is_valid(this.callback(function(a,b){a?(this.value_changed()&&(this.last_valid_input=this.val(),this.fire_event(pe.EventDatesTextModule.events.CHANGED,this.as_enum())),this.display_message("")):this.display_message(b)}))};pe.EventDatesTextModule.prototype.display_message=function(a){pe.EventHelperTools.show_message(this.dates_input_field,a)};
pe.EventDatesTextModule.prototype.is_valid=function(a){this.value_changed()||a(!0,"");$.ajax({url:"/api/events/check_dates",data:{dates:this.val()},error:pe.ajax_error,success:function(b){"error"==b.message&&a(!0,"Please enter valid event dates")}})};pe.EventDatesTextModule.prototype.val=function(){return this.dates_input_field.val().toString()};pe.EventDatesTextModule.prototype.value_changed=function(){return this.last_valid_input!==this.val()};
pe.EventTypesAutocomplete=function(a,b){pe.init_widget(this,a);this.event_types_input_field=this.container.find(".EventTypesAutocompleteInput");this.event_types_input_field.blur(this.callback(this.event_types_input_field_blurred));this.event_type_ids=$.map(b,function(a){return a.value.toString()});this.autosuggest_module=new pe.AutoSuggestModule(this.container,b,{selectedItemProp:"label",selectedValuesProp:"value",searchObjProps:"label",startText:"",minChars:2,neverSubmit:!0,preFill:this.event_types_input_field.data("event-data"),
selectionAdded:this.callback(this.search_result_selection_added)});this.last_valid_input=this.val()};pe.EventTypesAutocomplete.events={CHANGED:"EventTypesAutocomplete_CHANGED"};pe.EventTypesAutocomplete.prototype.as_enum=function(){return{type_ids:this.val().split(",")}};pe.EventTypesAutocomplete.prototype.add_event_types=function(a){this.autosuggest_module.add_entries(a);this.last_valid_input=this.val()};
pe.EventTypesAutocomplete.prototype.display_message=function(a){pe.EventHelperTools.show_message(this.event_types_input_field,a)};pe.EventTypesAutocomplete.prototype.event_types_input_field_blurred=function(){this.val()?(this.value_changed()&&(this.last_valid_input=this.val(),this.fire_event(pe.EventTypesAutocomplete.events.CHANGED,this.as_enum())),this.display_message("")):this.display_message("Event Types are required")};pe.EventTypesAutocomplete.prototype.is_valid=function(){return!!this.val()};
pe.EventTypesAutocomplete.prototype.search_result_selection_added=function(){this.autosuggest_module&&!pe.array_contains(this.event_type_ids,this.autosuggest_module.last_value())&&(this.autosuggest_module.remove_last_entry(),this.display_message("Please select types from the list."))};pe.EventTypesAutocomplete.prototype.val=function(){return this.autosuggest_module.val()};pe.EventTypesAutocomplete.prototype.value_changed=function(){return this.val()!==this.last_valid_input};
pe.EventWebsiteModule=function(a){pe.init_widget(this,a);this.website_input_field=this.container.find(".EventWebsite");this.website_input_field.blur(this.callback(this.website_input_field_blurred));this.last_valid_input=this.val()};pe.EventWebsiteModule.events={CHANGED:"EventWebsiteModule_CHANGED"};pe.EventWebsiteModule.prototype.as_enum=function(){return{url:this.val()}};pe.EventWebsiteModule.prototype.display_message=function(a){pe.EventHelperTools.show_message(this.website_input_field,a)};
pe.EventWebsiteModule.prototype.is_valid=function(){return!this.val()?!0:pe.EventHelperTools.validate_url(this.val())};pe.EventWebsiteModule.prototype.set_value=function(a){this.website_input_field.val(a);this.last_valid_input=a};pe.EventWebsiteModule.prototype.val=function(){return this.website_input_field.val().toString()};
pe.EventWebsiteModule.prototype.website_input_field_blurred=function(){this.is_valid()?(this.val()!==this.last_valid_input&&(this.last_valid_input=this.val(),this.fire_event(pe.EventWebsiteModule.events.CHANGED,this.as_enum())),pe.EventHelperTools.show_message(this.website_input_field,"")):pe.EventHelperTools.show_message(this.website_input_field,"Please enter a valid url.")};
pe.ParentEventAutocomplete=function(a,b){pe.init_widget(this,a);this.parent_input_field=this.container.find(".ParentEventAutocompleteInput");this.parent_input_field.blur(this.callback(this.parent_input_field_blurred));this.autosuggest_module=new pe.AutoSuggestModule(this.container,b,{startText:"",emptyText:"No parent event found",queryParam:"term",selectedItemProp:"label",selectedValuesProp:"value",searchObjProps:"label",neverSubmit:!0,selectionLimit:1,preFill:this.parent_input_field.data("event-data"),
selectionAdded:this.callback(this.search_result_selection_added)});this.last_valid_input=this.val()};pe.ParentEventAutocomplete.events={CHANGED:"ParentEventAutocomplete_CHANGED"};pe.ParentEventAutocomplete.prototype.as_enum=function(){return{parent_id:this.val()}};pe.ParentEventAutocomplete.prototype.add_parent_event=function(a){this.autosuggest_module.add_entry(a)};pe.ParentEventAutocomplete.prototype.display_message=function(a){pe.EventHelperTools.show_message(this.parent_input_field,a)};
pe.ParentEventAutocomplete.prototype.parent_input_field_blurred=function(){this.value_changed()&&(this.last_valid_input=this.val(),this.fire_event(pe.ParentEventAutocomplete.events.CHANGED,this.as_enum()));this.display_message("")};pe.ParentEventAutocomplete.prototype.search_result_selection_added=function(){this.autosuggest_module&&this.parent_input_field.val()===this.autosuggest_module.last_value()&&(this.autosuggest_module.remove_last_entry(),this.display_message("Cannot create parent event. Please select from list"))};
pe.ParentEventAutocomplete.prototype.val=function(){return this.autosuggest_module.val()};pe.ParentEventAutocomplete.prototype.value_changed=function(){return this.last_valid_input!==this.val()};
pe.accentMap={"&":"and","\u00e0":"a","\u00e1":"a","\u00e2":"a","\u00e3":"a","\u00e4":"a","\u00e5":"a","\u00e7":"c","\u00c0":"a","\u00c1":"a","\u00e8":"e","\u00e9":"e","\u00ea":"e","\u00eb":"e","\u00c8":"e","\u00c9":"e","\u00ec":"i","\u00f1":"n","\u00ed":"i","\u00ee":"i","\u00ef":"i","\u00f2":"o","\u00f3":"o","\u00f4":"o","\u00f5":"o","\u00f6":"o","\u00f9":"u","\u00fa":"u","\u00fb":"u","\u00fc":"u","!":"i",$:"s","-":""," ":"","'":""};
pe.animated_scrolling=function(a,b){if(0!==a.length){var c=a.offset().top-(b||25);$("html,body").stop().animate({scrollTop:c+"px"},800,"cubicEaseInOut",function(){return!1})}};pe.scrolling=function(a,b){if(0!==a.length){var c=a.offset().top-(b||25);$("html,body").scrollTop(c)}};pe.days_of_week="Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(",");pe.array_contains=function(a,b){return _.isArray(b)?0===_.difference(b,a).length:-1<_.indexOf(a,b)};
pe.arrays_equal=function(a,b){if(!a&&!b||!a&&0===b.length||0===a.length&&!b)return!0;if(a.length!=b.length)return!1;for(var c=a.sort(),d=b.sort(),e=0,f=a.length;e<f;e++)if(c[e]!==d[e])return!1;return!0};pe.array_match=function(a,b){var c=!1;$.each(a,function(a,e){if(-1<b.indexOf(e))return c=!0,!1});return c};pe.array_merge=function(a,b){var c=a.concat(b);c.sort();return c};
pe.array_remove=function(a,b){return!a?a:pe.is_array(b)?$.grep(a,function(a){return-1===b.indexOf(a)}):$.grep(a,function(a){return a!==b})};pe.assign_photo_size=function(a,b,c){return!a?"/assets/no_image_"+c+".png":"original"===b?a.replace("xxx.jpg",b+".jpg"):a.replace("xxx.jpg","s"+b+".jpg")};pe.remove_timestamp_from_asset_url=function(a){return a.split("?")[0]};pe.browser_is_ie8=function(){return $.browser.msie&&"8.0"===$.browser.version};
pe.build_dob_field_name=function(a,b,c){return[a||"user","[",b?b+"_":"","dob(",c,"i)]"].join("")};pe.capitalise_first_letter=function(a){return null===a?"":a.charAt(0).toUpperCase()+a.slice(1)};pe.classes_starting_with=function(a,b){return $.map(a.attr("class").split(/\s+/),function(a){if(pe.string_starts_with(a,b))return a})};pe.compare=function(a,b){return pe.is_array(a)&&pe.is_array(b)?pe.arrays_equal(a,b):a===b};
pe.convert_to_rounded_corners=function(a){a=a||$(".ConvertToRoundedCorners");a.each(function(a,c){var d=$(c);d.removeClass("ConvertToRoundedCorners");d.addClass("rounded_corner_wrapper");$('<div class="rounded_corner top_left"></div>').appendTo(d);$('<div class="rounded_corner top_right"></div>').appendTo(d);$('<div class="rounded_corner bottom_left"></div>').appendTo(d);$('<div class="rounded_corner bottom_right"></div>').appendTo(d)});return a};
pe.convert_to_tabbed_pod=function(a,b){return $.map(a,function(a){a=$(a);if(!a.hasClass("ConvertToTabbedPod"))return alert("format_tabbed_pod: element to convert must have class ConvertToTabbedPod. It only has "+a[0].className);var d=a.children("ul");d.addClass("tab");d.children("li").each(function(a,b){var b=$(b),c=b.html();b.html(pe.templatize('<div class="left_end pod_sprite float_left"></div>{{content}}<div class="right_end pod_sprite float_left"></div>',{content:c}))});var e=d.html();d.remove();
var d=a.html(),f=pe.classes_starting_with(a,"width");if(0===f.length)return alert("no width class found");if(1<f.length)return alert("more than 1 width class found");var g=f[0].substr(5);a.addClass("tabs");a.removeClass("ConvertToTabs");a.removeClass(f[0]);a.html(pe.templatize('<div><table class="width{{width}}" cellpadding="0" cellspacing="0"><tbody><tr><td class="header" colspan="4"><div class="header_row"><ul class="tab">{{headers}}</ul><div class="mid_section"></div><div class="right_corner pod_sprite"></div></div></td></tr><tr class="content_container"><td class="left_side pod_sides"></td><td class="content">{{content}}</td><td class="right_side pod_sides"></td></tr><tr class="footer_row"><td class="left_corner pod_sprite"></td><td class="mid_section"></td><td class="right_corner pod_sprite"></td></tr></tbody></table></div>',
{width:g,headers:e,content:d}));var e=a.children().tabs(b),h=["first","second","third","fourth"];a.find("ul.tab li").each(function(a,b){$(b).addClass(h[a])});return e})};
pe.new_convert_to_tabbed_pod=function(a,b){return $.map(a,function(a){a=$(a);if(!a.hasClass("ConvertToTabbedPod"))return alert("format_tabbed_pod: element to convert must have class ConvertToTabbedPod. It only has "+a[0].className);var d=a.children("ul"),e=d.html();d.remove();var d=a.html(),f=pe.classes_starting_with(a,"width");if(0===f.length)return alert("no width class found");if(1<f.length)return alert("more than 1 width class found");var g=f[0].substr(5);a.addClass("tabs");a.removeClass("ConvertToTabs");
a.removeClass(f[0]);a.html(pe.templatize('<div class="width{{width}}"><ul class="tab">{{headers}}</ul>{{content}}</div>',{width:g,headers:e,content:d}));var e=a.children().tabs(b),h=["first","second","third","fourth"];a.find("ul.tab li").each(function(a,b){$(b).addClass(h[a])});return e})};pe.date_string=function(a){return"string"===typeof a?a:a.getMonth()+1+"/"+a.getDate()+"/"+a.getFullYear()};
pe.days_between_dates=function(a,b){var c="string"===typeof a?Date.parse(a):a,d="string"===typeof b?Date.parse(b):b;return Math.abs(Math.floor((c-d)/864E5))};pe.event_search_text=function(a){var b=[a.name,a.description,a.location_name,a.category,a.neighborhood_name,a.neighborhood_id];a.tags&&$.each(a.tags,function(a,d){b.push(d)});a.performer_names&&$.each(a.performer_names,function(a,d){b.push(d)});return b.join(" ")};pe.fetch_photo_id_from_url=function(a){return a.split("/photos/")[1]};
pe.fix_ie7_rendering_bug=function(){$(".ConvertToTabbedPod").addClass("IeSucks")};pe.format_date=function(a){return a.getMonth()+1+"/"+a.getDate()+"/"+a.getFullYear()};pe.format_price=function(a){var b=Math.floor(a/100).toString(),a=(a%100).toString();2>a.length&&(a="0"+a);return"$"+b+"."+a};pe.format_duration=function(a,b){if(!a)return"0:00";var c=Math.floor(a%60);return pe.string_padding_left(Math.floor(a/60).toString(),b||1,"0")+":"+pe.string_padding_left(c.toString(),2,"0")};
pe.get_url_parameter=function(a,b){var c=RegExp("[\\?&]"+b+"=([^&]+)","i").exec(a);return c?c[1]:null};pe.hash_length=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};pe.hashes_equal=function(a,b){if(a===b)return!0;if(pe.hash_length(a)!=pe.hash_length(b))return!1;for(var c in a){var d=a[c],e=b[c];if(pe.is_array(d)){if(!pe.arrays_equal(d,e))return!1}else if(d!==e)return!1}return!0};
pe.hashes_match=function(a,b){for(var c in a){var d=a[c],e=b[c];if(pe.is_array(d)){if(!pe.array_contains(e,d))return!1}else if(d!==e)return!1}return!0};pe.https=function(a){return-1===window.location.href.indexOf("https://")?a:a.replace("http://","https://")};pe.inject=function(a,b,c){var d=b;$.each(a,function(a,b){d=c(d,b)});return d};pe.install_easing=function(){jQuery.easing.cubicEaseInOut=function(a,b,c,d){b=c+d;return 1>(a/=0.5)?b/2*a*a*a+c:b/2*((a-=2)*a*a+2)+c}};
pe.is_array=function(a){return!(!a||!("object"===typeof a&&"number"===typeof a.length&&"function"===typeof a.splice&&!a.propertyIsEnumerable("length")))};pe.is_valid_credit_card_number=function(a){return!!a.match(/^\d{4}(\s*|\s*\-\s*)?\d{4}(\s*|\s*\-\s*)?\d{4}(\s*|\s*\-\s*)?\d{4}$/)};pe.is_valid_date=function(a){return!a.match(/^(\d{1,2})(\/|-)(\d{1,2})(\/|-)(\d{4})$/)?!1:a!==$.datepicker.formatDate("m/d/yy",new Date(a))?a===$.datepicker.formatDate("mm/dd/yy",new Date(a)):!0};
pe.is_valid_zip_code=function(a){return!!a.match(/^\d{5}(\s*\-\s*\d{4})?$/)};pe.load=function(a){pe.assert(a,"error loading data");return a};pe.link_title_for_city=function(a){return"See the latest hotspots and events happening in "+a+"."};pe.link_title_for_city_party_climate=function(a){return"Check out the overview and photos of "+a+"."};
pe.link_title_for_event=function(a,b){return b?"Check out event details, photos and videos of "+a+" at "+b+".":"Check out event details, photos and videos of "+a+"."};pe.link_title_for_neighborhood=function(a,b){return"Check out "+a+" description, photos, and venues in "+b+"."};pe.link_title_for_performer=function(a){return"See the latest "+a+" schedule, photos, videos and news."};
pe.link_title_for_reviewer=function(a){switch(a){case "Lucas":return"Meet Lucas, the quintessential fun- loving, pub-crawling \u201cguy\u2019s guy\u201d. Learn about his personality and ratings.";case "Adriana":return"Meet Adriana, the epitome of a cosmopolitan girl. Learn about her personality and ratings.";case "Jonah":return"Meet Jonah, an affable, non-mainstream guy with natural curiosity about people and cultures. Learn about his personality and ratings.";case "Emma":return"Meet Emma, a lively, witty, and sociable \u201cgirl next door\u201d. Learn about her personality and ratings.";
case "All":return"Meet Lucas, Adriana, Jonah and Emma. Learn how their personalities can help you maximize your social experiences in your city and your travels."}};pe.link_title_for_venue=function(a,b,c){return c?"Check out the review, photos, videos, map and events schedule of "+a+" - "+c+" in "+b+".":"Check out the review, photos, videos, map and events schedule of "+a+" in "+b+"."};
pe.normalize=function(a){for(var b="",c=0,d=a.length;c<d;c++)var e=a.charAt(c),f=pe.accentMap[e],b=b+("undefined"===typeof f?e:f);return b};pe.object_hash_from_array=function(a){var b={};$.each(a,function(a,d){b[d.id]=d});return b};pe.object_length=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};pe.parse_price=function(a){return Math.ceil(100*parseFloat(a.substring(1)))};
pe.prepare_autocomplete_data=function(a){var b=[];$.each(a,function(a,d){$.each(d,function(d,f){f.category=a;b.push(f)})});return b};pe.remove_anchor_from_url=function(a){return a?a.split("#")[0]:""};pe.set_autocomplete_source=function(a,b,c){var d=RegExp($.ui.autocomplete.escapeRegex(pe.normalize(b.term)),"i");c($.grep(pe.prepare_autocomplete_data(a),function(a){a=a.label||a.value||a;return d.test(a)||d.test(pe.normalize(a))}))};
pe.shuffle_array=function(a){if(!a)return[];for(var b,c,d=a.length;d;)b=parseInt(Math.random()*d,10),c=a[--d],a[d]=a[b],a[b]=c;return a};pe.string_padding_left=function(a,b,c){for(;a.length<b;)a=c+a;return a};pe.structured_tags_as_flat_array=function(a){var b=[];$.each(a,function(a,d){$.merge(b,d)});return b};pe.text_contains_query=function(a,b){var c=b.split(" "),d=!0;$.each(c,function(b,c){if(-1===a.indexOf(c))return d=!1,!0});return d};pe.today_date_string=function(){return pe.date_string(new Date)};
pe.venue_search_text=function(a){var b=[a.name,a.description,a.address,a.hotspot_text,a.neighborhood_name];a.types&&$.each(a.types,function(a,d){b.push(d)});a.tags&&$.each(a.tags,function(a,d){b.push(d)});return b.join(" ")};pe.xor=function(a,b){return!!(a?!b:b)};
pe.NewPerformerDialogForm=function(a,b,c,d){pe.init_widget(this,a);this.success_callback_method=c;this.cancel_callback_method=d;this.dialog_box=$(this.dialog_html(b));this.performer_name_input=this.dialog_box.find(".PerformerName");this.performer_url_input=this.dialog_box.find(".PerformerURL");this.performer_description_input=this.dialog_box.find(".PerformerDescription");this.dialog_box.dialog({modal:!0,show:!1,close:this.callback(this.close_button_clicked),buttons:{"Create Performer":this.callback(this.create_button_clicked),
Close:this.callback(this.close_button_clicked)}})};pe.NewPerformerDialogForm.prototype.close_button_clicked=function(){this.destroy_dialog();this.cancel_callback_method()};
pe.NewPerformerDialogForm.prototype.create_button_clicked=function(){var a=this.performer_name_input.val();if(!a)return pe.EventHelperTools.show_message(this.performer_name_input,"Name is required"),!1;if(150<a.length)return pe.EventHelperTools.show_message(this.performer_name_input,"Name is too long"),!1;var b=this.performer_url_input.val();if(b&&!pe.EventHelperTools.validate_url(b))return pe.EventHelperTools.show_message(this.performer_url_input,"Please input a valid url"),!1;$.ajax({url:"/admin/events_admin/performer_create",
type:"POST",data:{name:a,url:b,description:this.performer_description_input.val()},error:pe.ajax_error,success:this.callback(function(a){a.error?pe.EventHelperTools.show_message(this.performer_name_input,a.error):(this.destroy_dialog(),this.success_callback_method(a))})})};pe.NewPerformerDialogForm.prototype.destroy_dialog=function(){this.dialog_box.dialog("destroy");this.dialog_box.remove()};
pe.NewPerformerDialogForm.prototype.dialog_html=function(a){return'<div title="Create Performer"><ul><li><label><strong>Only Entertainer Type can be created in the Events Importer</strong></label><br></li><li><label for="performer_name">Name</label> <input name="performer_name" class="PerformerName" value="'+a+'"></li><li><label for="performer_url">Official Site</label> <input name="performer_url" class="PerformerURL" value=""></li><li><label for="performer_description">Description</label> <textarea name="performer_description" class="PerformerDescription"></textarea></li></ul></div>'};
pe.PerformerAutocomplete=function(a,b){pe.init_widget(this,a);this.performer_autocomplete_field=this.container.find(".PerformerAutocompleteInput");this.performer_autocomplete_field.blur(this.callback(this.performer_autocomplete_field_blurred));this.autosuggest_module=new pe.AutoSuggestModule(this.container,b,{startText:"",emptyText:"Press Tab or Type Comma to create a performer",selectedItemProp:"label",selectedValuesProp:"value",searchObjProps:"search",queryParam:"term",neverSubmit:!0,preFill:this.performer_autocomplete_field.data("event-data"),
resultClick:this.callback(this.search_result_clicked),selectionAdded:this.callback(this.search_result_selection_added)});this.last_valid_input=this.val()};pe.PerformerAutocomplete.events={CHANGED:"PerformerAutocomplete_CHANGED",SELECTED:"PerformerAutocomplete_SELECTED"};pe.PerformerAutocomplete.prototype.as_enum=function(){return{performer_ids:this.val().split(",")}};
pe.PerformerAutocomplete.prototype.add_performers=function(a){this.autosuggest_module.add_entries(a);this.last_valid_input=this.val();if(a&&0<a.length){var b=_.flatten($.map(a,function(a){return a.content_tag_ids})),a=_.flatten($.map(a,function(a){return a.type_ids}));this.fire_event(pe.PerformerAutocomplete.events.SELECTED,{content_tag_ids:b,type_ids:a})}};pe.PerformerAutocomplete.prototype.display_message=function(a){pe.EventHelperTools.show_message(this.performer_autocomplete_field,a)};
pe.PerformerAutocomplete.prototype.open_new_performer_dialog_form=function(){new pe.NewPerformerDialogForm(this.container,this.performer_autocomplete_field.val(),this.callback(this.replace_last_performer),this.callback(this.remove_last_selected_performer))};pe.PerformerAutocomplete.prototype.performer_autocomplete_field_blurred=function(){this.value_changed()&&(this.last_valid_input=this.val(),this.fire_event(pe.PerformerAutocomplete.events.CHANGED,this.as_enum()));this.display_message("")};
pe.PerformerAutocomplete.prototype.remove_last_selected_performer=function(){this.autosuggest_module.remove_last_entry()};pe.PerformerAutocomplete.prototype.replace_last_performer=function(a){this.autosuggest_module.replace_last_entry(a)};pe.PerformerAutocomplete.prototype.search_result_clicked=function(a){this.fire_event(pe.PerformerAutocomplete.events.SELECTED,{content_tag_ids:a.attributes.content_tag_ids,type_ids:a.attributes.type_ids})};
pe.PerformerAutocomplete.prototype.search_result_selection_added=function(){this.autosuggest_module&&this.performer_autocomplete_field.val()===this.autosuggest_module.last_value()&&this.open_new_performer_dialog_form()};pe.PerformerAutocomplete.prototype.val=function(){return this.autosuggest_module.val()};pe.PerformerAutocomplete.prototype.value_changed=function(){return this.last_valid_input!==this.val()};
pe.RecurringParentAutocomplete=function(a,b){pe.init_widget(this,a);this.autosuggest_input_field=this.container.find(".RecurringParentAutocompleteInput");this.autosuggest_input_field.blur(this.callback(this.autosuggest_input_field_blurred));this.autosuggest_module=new pe.AutoSuggestModule(this.container,b,{startText:"",emptyText:"No recurring event found",queryParam:"term",selectedItemProp:"label",selectedValuesProp:"value",searchObjProps:"label",neverSubmit:!0,selectionLimit:1,preFill:this.autosuggest_input_field.data("event-data"),
selectionAdded:this.callback(this.search_result_selection_added),selectionRemoved:this.callback(this.selection_removed)});this.last_valid_input=this.val()};pe.RecurringParentAutocomplete.events={CHANGED:"RecurringParentAutocomplete_CHANGED",REMOVED:"RecurringParentAutocomplete_REMOVED",SELECTED:"RecurringParentAutocomplete_SELECTED"};pe.RecurringParentAutocomplete.prototype.as_enum=function(){return{recurring_parent_id:this.val()}};
pe.RecurringParentAutocomplete.prototype.autosuggest_input_field_blurred=function(){this.value_changed()&&(this.last_valid_input=this.val(),this.fire_event(pe.RecurringParentAutocomplete.events.CHANGED,this.as_enum()));this.display_message("")};pe.RecurringParentAutocomplete.prototype.display_message=function(a){pe.EventHelperTools.show_message(this.autosuggest_input_field,a)};
pe.RecurringParentAutocomplete.prototype.search_result_selection_added=function(){this.autosuggest_module&&(this.autosuggest_input_field.val()===this.autosuggest_module.last_value()?(this.autosuggest_module.remove_last_entry(),this.display_message("Cannot create recurring parent. Please select from list")):$.ajax({url:"/admin/events_admin/recurring_parent_event_data",data:{recurring_parent_id:this.val()},error:pe.ajax_error,success:this.callback(function(a){a.error?(this.autosuggest_module.remove_last_entry(),
this.display_message(a.error)):this.fire_event(pe.RecurringParentAutocomplete.events.SELECTED,a)})}))};pe.RecurringParentAutocomplete.prototype.selection_removed=function(a){$(a).remove();this.fire_event(pe.RecurringParentAutocomplete.events.REMOVED,null)};pe.RecurringParentAutocomplete.prototype.value_changed=function(){return this.last_valid_input!==this.val()};pe.RecurringParentAutocomplete.prototype.val=function(){return this.autosuggest_module.val()};
pe.TextInputModule=function(a,b){pe.init_widget(this,a);this.attribute_key=b;this.input_field=this.container.find("input");this.input_field.blur(this.callback(this.input_field_blurred));this.last_input=this.val()};pe.TextInputModule.events={BLURRED:"TextInputModule_BLURRED",CHANGED:"TextInputModule_CHANGED"};pe.TextInputModule.prototype.as_enum=function(){var a={};a[this.attribute_key]=this.val();return a};
pe.TextInputModule.prototype.input_field_blurred=function(){this.last_input!==this.val()&&(this.last_input=this.val(),this.fire_event(pe.TextInputModule.events.CHANGED,this.as_enum()));this.fire_event(pe.TextInputModule.events.BLURRED);pe.EventHelperTools.show_message(this.input_field,"")};pe.TextInputModule.prototype.set_value=function(a){a&&(this.input_field.val(a),this.last_input=a)};pe.TextInputModule.prototype.val=function(){return this.input_field.val().toString()};
pe.NewVenueDialogForm=function(a,b,c,d,e,f){pe.init_widget(this,a);this.success_callback_method=e;this.cancel_callback_method=f;this.city_data_ids=$.map(c,function(a){return a.value.toString()});this.endpoint_ids=$.map(d,function(a){return a.value.toString()});this.dialog_box=$(this.dialog_html(b));this.venue_name_input=this.dialog_box.find(".VenueName");this.venue_city_input=this.dialog_box.find(".VenueCity");this.venue_endpoint_input=this.dialog_box.find(".VenueEndpoint");this.venue_address_input=
this.dialog_box.find(".VenueFullAddress");this.dialog_box.dialog({modal:!0,show:!1,close:this.callback(this.close_button_clicked),buttons:{"Create Venue":this.callback(this.create_button_clicked),Close:this.callback(this.close_button_clicked)}});this.venue_endpoints_autosuggest=new pe.AutoSuggestModule(this.dialog_box.find(".EndpointInputContainer"),d,{startText:"Select an Endpoint",emptyText:"No Endpoint found",selectedItemProp:"label",selectedValuesProp:"value",searchObjProps:"search",neverSubmit:!0,
selectionLimit:1});this.venue_city_autosuggest_module=new pe.AutoSuggestModule(this.dialog_box.find(".CityInputContainer"),c,{startText:"Select a City",emptyText:"No city found",selectedItemProp:"label",selectedValuesProp:"value",searchObjProps:"label",neverSubmit:!0,selectionLimit:1})};pe.NewVenueDialogForm.prototype.close_button_clicked=function(){this.destroy_dialog();this.cancel_callback_method()};
pe.NewVenueDialogForm.prototype.create_button_clicked=function(){var a=this.venue_name_input.val();if(!a)return pe.EventHelperTools.show_message(this.venue_name_input,"Name is required"),!1;if(150<a.length)return pe.EventHelperTools.show_message(this.venue_name_input,"Name is too long"),!1;var b=this.venue_city_autosuggest_module.val();if(!b)return pe.EventHelperTools.show_message(this.venue_city_input,"City is required"),!1;if(!pe.array_contains(this.city_data_ids,b))return pe.EventHelperTools.show_message(this.venue_city_input,
"Select a valid city from the list"),!1;var c=this.venue_endpoints_autosuggest.val();if(!c)return pe.EventHelperTools.show_message(this.venue_endpoint_input,"Endpoint is required"),!1;if(!pe.array_contains(this.endpoint_ids,c))return pe.EventHelperTools.show_message(this.venue_endpoint_input,"Select a valid endpoint from the list"),!1;$.ajax({url:"/admin/events_admin/venue_create",type:"POST",data:{name:a,city_id:b,endpoint_id:c,full_address:this.venue_address_input.val()},error:pe.ajax_error,success:this.callback(function(a){a.error?
pe.EventHelperTools.show_message(this.venue_name_input,a.error):(this.destroy_dialog(),this.success_callback_method(a))})})};pe.NewVenueDialogForm.prototype.destroy_dialog=function(){this.dialog_box.dialog("destroy");this.dialog_box.remove()};pe.NewVenueDialogForm.prototype.dialog_html=function(a){return'<div title="Create Venue"><ul><li><label for="venue_name">Name</label> <input name="venue_name" class="VenueName" value="'+a+'"></li><li class="CityInputContainer"><input name="venue_city" class="VenueCity AutoSuggestInput" value=""></li><li class="EndpointInputContainer"><input name="venue_endpoint" class="VenueEndpoint AutoSuggestInput" value=""></li><li><label for="venue_address">Full Address</label> <textarea name="venue_address" class="VenueFullAddress"></textarea></li></ul></div>'};
pe.VenueAutocomplete=function(a,b,c,d){pe.init_widget(this,a);this.city_data_source=c;this.venue_endpoints_data=d;this.venue_input_field=this.container.find(".VenueAutocompleteInput");this.venue_input_field.blur(this.callback(this.venue_input_field_blurred));this.autosuggest_module=new pe.AutoSuggestModule(this.container,b,{startText:"",emptyText:"Press Tab or type comma to create a new venue",selectedItemProp:"label",selectedValuesProp:"value",searchObjProps:"search",queryParam:"term",neverSubmit:!0,
preFill:this.venue_input_field.data("event-data"),resultClick:this.callback(this.search_result_clicked),selectionAdded:this.callback(this.search_result_selection_added)});this.city_id=this.get_city_id(this.venue_input_field.data("event-data"));this.last_valid_input=this.val()};pe.VenueAutocomplete.events={CHANGED:"VenueAutocomplete_CHANGED"};pe.VenueAutocomplete.prototype.add_venues=function(a){this.autosuggest_module.add_entries(a);this.last_valid_input=this.val()};
pe.VenueAutocomplete.prototype.as_enum=function(){return{venue_ids:this.val().split(",")}};pe.VenueAutocomplete.prototype.display_message=function(a){pe.EventHelperTools.show_message(this.venue_input_field,a)};pe.VenueAutocomplete.prototype.get_city_id=function(a){return!a?null:a[0].city_id};
pe.VenueAutocomplete.prototype.open_new_venue_dialog_form=function(){new pe.NewVenueDialogForm(this.container,this.venue_input_field.val(),this.city_data_source,this.venue_endpoints_data,this.callback(this.replace_last_venue),this.callback(this.remove_last_venue))};pe.VenueAutocomplete.prototype.remove_last_venue=function(){this.autosuggest_module.remove_last_entry()};pe.VenueAutocomplete.prototype.replace_last_venue=function(a){this.autosuggest_module.replace_last_entry(a);this.search_result_selection_added()};
pe.VenueAutocomplete.prototype.search_result_clicked=function(a){a=a.attributes.city_id||null;if(this.city_id&&a!==this.city_id)return this.autosuggest_module.remove_last_entry(),this.display_message("Please select venues from the same city"),!1;this.city_id=a};pe.VenueAutocomplete.prototype.search_result_selection_added=function(){this.autosuggest_module&&this.venue_input_field.val()===this.autosuggest_module.last_value()&&this.open_new_venue_dialog_form()};pe.VenueAutocomplete.prototype.val=function(){return this.autosuggest_module.val()};
pe.VenueAutocomplete.prototype.value_changed=function(){return this.last_valid_input!==this.val()};pe.VenueAutocomplete.prototype.venue_input_field_blurred=function(){this.value_changed()&&(this.last_valid_input=this.val(),this.fire_event(pe.VenueAutocomplete.events.CHANGED,this.as_enum()));this.display_message("")};
pe.RowModule=function(a,b,c,d,e,f){pe.init_widget(this,a);this.city_data=b;this.event_type_data=c;this.content_tags_data=d;this.event_endpoints_data=e;this.venue_endpoints_data=f;this.event_id=this.container.data("event-id")||"";this.input_widgets=[];this.event_creation_in_process=!1;this.recurring_event_autocomplete=new pe.RecurringParentAutocomplete(this.container.find(".RecurringParentAutocompleteContainer"),"/api/events/recurring_parents");this.recurring_event_autocomplete.bind_event(pe.RecurringParentAutocomplete.events.REMOVED,
this.callback(this.recurring_parent_removed));this.recurring_event_autocomplete.bind_event(pe.RecurringParentAutocomplete.events.SELECTED,this.callback(this.recurring_parent_selected));this.input_widgets.push(this.recurring_event_autocomplete);this.parent_event_autocomplete=new pe.ParentEventAutocomplete(this.container.find(".ParentEventAutocompleteContainer"),"/api/events/parents");this.input_widgets.push(this.parent_event_autocomplete);this.endpoint_autocomplete=new pe.EndpointAutocomplete(this.container.find(".EndpointAutocompleteContainer"),
e);this.endpoint_autocomplete.bind_event(pe.EndpointAutocomplete.events.REMOVED,this.callback(this.endpoint_removed));this.input_widgets.push(this.endpoint_autocomplete);this.event_dates_text_module=new pe.EventDatesTextModule(this.container.find(".EventDatesTextContainer"));this.input_widgets.push(this.event_dates_text_module);this.is_recurring_checkbox=this.container.find(".IsRecurring");this.performer_autocomplete=new pe.PerformerAutocomplete(this.container.find(".PerformerAutocompleteContainer"),
"/api/events/performers");this.performer_autocomplete.bind_event(pe.PerformerAutocomplete.events.SELECTED,this.callback(this.performer_selected));this.input_widgets.push(this.performer_autocomplete);this.event_name_module=new pe.TextInputModule(this.container.find(".EventNameContainer"),"name");this.input_widgets.push(this.event_name_module);this.venues_autocomplete=new pe.VenueAutocomplete(this.container.find(".VenueAutocompleteContainer"),"/api/events/venues",b,f);this.input_widgets.push(this.venues_autocomplete);
this.cities_autocomplete=new pe.CityAutocomplete(this.container.find(".CityAutocompleteContainer"),b);this.input_widgets.push(this.cities_autocomplete);this.event_types_autocomplete=new pe.EventTypesAutocomplete(this.container.find(".EventTypeAutocompleteContainer"),c);this.input_widgets.push(this.event_types_autocomplete);this.content_tags_autocomplete=new pe.ContentTagsAutocomplete(this.container.find(".ContentTagsAutocompleteContainer"),d);this.input_widgets.push(this.content_tags_autocomplete);
this.event_description_module=new pe.TextInputModule(this.container.find(".EventDescriptionContainer"),"description");this.input_widgets.push(this.event_description_module);this.event_website_module=new pe.EventWebsiteModule(this.container.find(".EventWebsiteContainer"));this.input_widgets.push(this.event_website_module);this.event_price_module=new pe.TextInputModule(this.container.find(".EventTicketPricesContainer"),"price");this.input_widgets.push(this.event_price_module);this.event_comments_module=
new pe.TextInputModule(this.container.find(".EventCommentsContainer"),"comment");this.input_widgets.push(this.event_comments_module);this.clone_button=this.container.find(".CloneButton");this.clone_button.click(this.callback(this.clone_button_clicked));this.delete_button=this.container.find(".DeleteButton");this.delete_button.click(this.callback(this.delete_button_clicked));this.resubmit_button=this.container.find(".ResubmitButton");this.event_id?(this.intialize_event_update_handlers(),this.resubmit_button.click(this.callback(this.resubmit_button_clicked))):
(this.resubmit_button.hide(),this.event_comments_module.bind_event(pe.TextInputModule.events.BLURRED,this.callback(this.event_comments_field_blurred)))};pe.RowModule.prototype.add_new_row=function(a){this.container.after(a);(new pe.RowModule(a,this.city_data,this.event_type_data,this.content_tags_data,this.event_endpoints_data,this.venue_endpoints_data)).recurring_event_autocomplete.autosuggest_input_field.focus()};pe.RowModule.prototype.attribute_changed=function(a,b){this.is_valid()&&this.update_event_attributes(b)};
pe.RowModule.prototype.clone_button_clicked=function(){this.is_valid()&&(this.event_id?this.clone_row():this.create_event(this.callback(function(a){a.error?this.recurring_event_autocomplete.display_message(a.error):(this.event_id=a.id,this.event_name_module.set_value(a.name),this.intialize_event_update_handlers(),this.clone_row())})))};pe.RowModule.prototype.clone_row=function(){$.ajax({url:"/admin/events_admin/cloned_event_row",type:"GET",data:{event_id:this.event_id},error:pe.ajax_error,success:this.callback(function(a){this.add_new_row($(a))})})};
pe.RowModule.prototype.create_event=function(a){this.event_creation_in_process=!0;this.clone_button.hide();$.ajax({url:"/admin/events_admin/event_create",type:"POST",data:{event:this.get_event_attributes()},error:this.callback(function(){this.event_creation_in_process=!1;this.clone_button.show();pe.ajax_error()}),success:this.callback(function(b){this.event_creation_in_process=!1;this.clone_button.show();a(b)})})};
pe.RowModule.prototype.delete_button_clicked=function(){this.event_id?$.ajax({url:"/admin/events_admin/event_delete",type:"PUT",data:{event_id:this.event_id},error:pe.ajax_error,success:this.callback(function(a){a?this.recurring_event_autocomplete.display_message(a):this.container.remove()})}):this.container.remove()};
pe.RowModule.prototype.event_comments_field_blurred=function(a){!this.event_id&&!this.event_creation_in_process&&(a.preventDefault(),this.is_valid()&&this.create_event(this.callback(function(a){a.error?this.recurring_event_autocomplete.display_message(a.error):(this.event_id=a.id,this.event_name_module.set_value(a.name),this.intialize_event_update_handlers(),pe.ajax_loader.event_row_template.load(this.callback(function(a){this.add_new_row($(a))})))})))};
pe.RowModule.prototype.event_location_changed=function(){if(this.is_valid()){var a={};$.extend(a,this.cities_autocomplete.as_enum());$.extend(a,this.venues_autocomplete.as_enum());this.update_event_attributes(a)}};pe.RowModule.prototype.endpoint_removed=function(a,b){this.recurring_event_autocomplete.val()?(this.endpoint_autocomplete.restore_value(),this.endpoint_autocomplete.display_message("Endpoint cannot be removed")):$(b).remove()};
pe.RowModule.prototype.get_event_attributes=function(){var a={};$.each(this.input_widgets,this.callback(function(b,c){$.extend(a,c.as_enum())}));a.is_recurring_event=this.is_recurring_checkbox.is(":checked");return a};pe.RowModule.get_tags_using_ids=function(a,b){return $.map(a,function(a){if(-1<$.inArray(a.value,b))return a})};pe.RowModule.intialize_event_row_modules=function(a,b,c,d,e){$.each($(".EventRowModule"),function(f,g){new pe.RowModule($(g),a,b,c,d,e)})};
pe.RowModule.prototype.intialize_event_update_handlers=function(){this.cities_autocomplete.bind_event(pe.CityAutocomplete.events.CHANGED,this.callback(this.event_location_changed));this.content_tags_autocomplete.bind_event(pe.ContentTagsAutocomplete.events.CHANGED,this.callback(this.attribute_changed));this.endpoint_autocomplete.bind_event(pe.EndpointAutocomplete.events.CHANGED,this.callback(this.attribute_changed));this.event_comments_module.bind_event(pe.TextInputModule.events.CHANGED,this.callback(this.attribute_changed));
this.event_dates_text_module.bind_event(pe.EventDatesTextModule.events.CHANGED,this.callback(this.attribute_changed));this.event_description_module.bind_event(pe.TextInputModule.events.CHANGED,this.callback(this.attribute_changed));this.event_name_module.bind_event(pe.TextInputModule.events.CHANGED,this.callback(this.attribute_changed));this.event_price_module.bind_event(pe.TextInputModule.events.CHANGED,this.callback(this.attribute_changed));this.event_types_autocomplete.bind_event(pe.EventTypesAutocomplete.events.CHANGED,
this.callback(this.attribute_changed));this.event_website_module.bind_event(pe.EventWebsiteModule.events.CHANGED,this.callback(this.attribute_changed));this.is_recurring_checkbox.click(this.callback(this.is_recurring_checkbox_clicked));this.parent_event_autocomplete.bind_event(pe.ParentEventAutocomplete.events.CHANGED,this.callback(this.attribute_changed));this.performer_autocomplete.bind_event(pe.PerformerAutocomplete.events.CHANGED,this.callback(this.performer_changed));this.recurring_event_autocomplete.bind_event(pe.RecurringParentAutocomplete.events.CHANGED,
this.callback(this.recurring_parent_changed));this.venues_autocomplete.bind_event(pe.VenueAutocomplete.events.CHANGED,this.callback(this.event_location_changed))};pe.RowModule.prototype.is_recurring_checkbox_clicked=function(){this.is_valid()&&this.update_event_attributes({is_recurring_event:this.is_recurring_checkbox.is(":checked")})};
pe.RowModule.prototype.is_valid=function(){var a=!0;this.recurring_event_autocomplete.val()&&this.is_recurring_checkbox.is(":checked")?(this.recurring_event_autocomplete.display_message("A recurring event cannot have a recurring parent."),a=!1):this.recurring_event_autocomplete.display_message("");this.parent_event_autocomplete.val()&&this.is_recurring_checkbox.is(":checked")?(this.parent_event_autocomplete.display_message("A recurring event cannot have a recurring parent."),a=!1):this.parent_event_autocomplete.display_message("");
this.endpoint_autocomplete.val()?this.endpoint_autocomplete.display_message(""):(this.endpoint_autocomplete.display_message("Endpoint is required"),a=!1);this.event_dates_text_module.val()&&this.is_recurring_checkbox.is(":checked")?(this.event_dates_text_module.display_message("A recurring event cannot have event dates."),a=!1):!this.event_dates_text_module.val()&&!this.is_recurring_checkbox.is(":checked")?(this.event_dates_text_module.display_message("Please enter event dates."),a=!1):this.event_dates_text_module.display_message("");
this.cities_autocomplete.val()&&this.venues_autocomplete.val()?(this.venues_autocomplete.display_message("An event cannot have both cities and venues."),a=!1):!this.cities_autocomplete.val()&&!this.venues_autocomplete.val()?(this.venues_autocomplete.display_message("Please select cities or venues as event locations"),a=!1):this.venues_autocomplete.display_message("");this.event_types_autocomplete.val()?this.event_types_autocomplete.display_message(""):(this.event_types_autocomplete.display_message("Event Types is required"),
a=!1);!this.event_name_module.val()&&!this.performer_autocomplete.val()?(this.performer_autocomplete.display_message("Please enter a name or select performers."),a=!1):this.performer_autocomplete.display_message("");this.event_website_module.is_valid()?this.event_website_module.display_message(""):(this.event_website_module.display_message("Please enter a valid url"),a=!1);return a};
pe.RowModule.prototype.performer_selected=function(a,b){var c=b.content_tag_ids;c&&0<c.length&&this.content_tags_autocomplete.add_content_tags(pe.RowModule.get_tags_using_ids(this.content_tags_data,c));(c=b.type_ids)&&0<c.length&&this.event_types_autocomplete.add_event_types(pe.RowModule.get_tags_using_ids(this.event_type_data,c))};
pe.RowModule.prototype.performer_changed=function(){if(this.is_valid()){var a={};$.extend(a,this.content_tags_autocomplete.as_enum());$.extend(a,this.event_types_autocomplete.as_enum());$.extend(a,this.performer_autocomplete.as_enum());this.update_event_attributes(a)}};
pe.RowModule.prototype.recurring_parent_selected=function(a,b){this.cities_autocomplete.add_cities(b.cities);this.content_tags_autocomplete.add_content_tags(b.content_tags);this.endpoint_autocomplete.add_endpoint(b.endpoint);this.event_description_module.set_value(b.description);this.event_types_autocomplete.add_event_types(b.types);this.event_website_module.set_value(b.url);this.performer_autocomplete.add_performers(b.performers);this.venues_autocomplete.add_venues(b.venues)};
pe.RowModule.prototype.recurring_parent_changed=function(){if(this.is_valid()){var a={};$.extend(a,this.cities_autocomplete.as_enum());$.extend(a,this.content_tags_autocomplete.as_enum());$.extend(a,this.endpoint_autocomplete.as_enum());$.extend(a,this.event_description_module.as_enum());$.extend(a,this.event_types_autocomplete.as_enum());$.extend(a,this.event_website_module.as_enum());$.extend(a,this.performer_autocomplete.as_enum());$.extend(a,this.venues_autocomplete.as_enum());this.update_event_attributes(a)}};
pe.RowModule.prototype.recurring_parent_removed=function(){this.endpoint_autocomplete.autosuggest_module.remove_last_entry()};pe.RowModule.prototype.resubmit_button_clicked=function(){this.is_valid()&&this.update_event_attributes({status:"review"},this.callback(function(){this.container.remove()}))};
pe.RowModule.prototype.update_event_attributes=function(a,b){$.ajax({url:"/admin/events_admin/event_update",type:"PUT",data:{event_id:this.event_id,event:a},error:pe.ajax_error,success:this.callback(function(a){a?this.recurring_event_autocomplete.display_message(a):b&&b(!0)})})};
