jQuery&&function(c){c.extend(c.fn,{uploadify:function(d){c(this).each(function(){settings=c.extend({id:c(this).attr("id"),uploader:"uploadify.swf",script:"uploadify.php",expressInstall:null,folder:"",height:30,width:110,cancelImg:"cancel.png",wmode:"opaque",scriptAccess:"sameDomain",fileDataName:"Filedata",method:"POST",queueSizeLimit:999,simUploadLimit:1,queueID:!1,displayData:"percentage",onInit:function(){},onSelect:function(){},onQueueFull:function(){},onCheck:function(){},onCancel:function(){},
onError:function(){},onProgress:function(){},onComplete:function(){},onAllComplete:function(){}},d);var b=location.pathname,b=b.split("/");b.pop();var b=b.join("/")+"/",a={};a.uploadifyID=settings.id;a.pagepath=b;settings.buttonImg&&(a.buttonImg=escape(settings.buttonImg));settings.buttonText&&(a.buttonText=escape(settings.buttonText));settings.rollover&&(a.rollover=!0);a.script=settings.script;a.folder=escape(settings.folder);if(settings.scriptData){var e="",g;for(g in settings.scriptData)e+="&"+
g+"="+settings.scriptData[g];a.scriptData=escape(e.substr(1))}a.width=settings.width;a.height=settings.height;a.wmode=settings.wmode;a.method=settings.method;a.queueSizeLimit=settings.queueSizeLimit;a.simUploadLimit=settings.simUploadLimit;settings.hideButton&&(a.hideButton=!0);settings.fileDesc&&(a.fileDesc=settings.fileDesc);settings.fileExt&&(a.fileExt=settings.fileExt);settings.multi&&(a.multi=!0);settings.auto&&(a.auto=!0);settings.sizeLimit&&(a.sizeLimit=settings.sizeLimit);settings.checkScript&&
(a.checkScript=settings.checkScript);settings.fileDataName&&(a.fileDataName=settings.fileDataName);settings.queueID&&(a.queueID=settings.queueID);!1!==settings.onInit()&&(c(this).css("display","none"),c(this).after('<div id="'+c(this).attr("id")+'Uploader"></div>'),swfobject.embedSWF(settings.uploader,settings.id+"Uploader",settings.width,settings.height,"9.0.24",settings.expressInstall,a,{quality:"high",wmode:settings.wmode,allowScriptAccess:settings.scriptAccess}),!1==settings.queueID&&c("#"+c(this).attr("id")+
"Uploader").after('<div id="'+c(this).attr("id")+'Queue" class="uploadifyQueue"></div>'));"function"==typeof settings.onOpen&&c(this).bind("uploadifyOpen",settings.onOpen);c(this).bind("uploadifySelect",{action:settings.onSelect,queueID:settings.queueID},function(a,b,d){if(!1!==a.data.action(a,b,d)){var e=0.01*Math.round(100*(d.size/1024)),g="KB";1E3<e&&(e=0.01*Math.round(0.1*e),g="MB");e=e.toString().split(".");e=1<e.length?e[0]+"."+e[1].substr(0,2):e[0];fileName=20<d.name.length?d.name.substr(0,
20)+"...":d.name;queue="#"+c(this).attr("id")+"Queue";a.data.queueID&&(queue="#"+a.data.queueID);c(queue).append('<div id="'+c(this).attr("id")+b+'" class="uploadifyQueueItem"><div class="cancel"><a href="javascript:jQuery(\'#'+c(this).attr("id")+"').uploadifyCancel('"+b+'\')"><img src="'+settings.cancelImg+'" border="0" /></a></div><span class="fileName">'+fileName+" ("+e+g+')</span><span class="percentage"></span><div class="uploadifyProgress"><div id="'+c(this).attr("id")+b+'ProgressBar" class="uploadifyProgressBar">\x3c!--Progress Bar--\x3e</div></div></div>')}});
"function"==typeof settings.onSelectOnce&&c(this).bind("uploadifySelectOnce",settings.onSelectOnce);c(this).bind("uploadifyQueueFull",{action:settings.onQueueFull},function(a,c){!1!==a.data.action(a,c)&&alert("The queue is full.  The max size is "+c+".")});c(this).bind("uploadifyCheckExist",{action:settings.onCheck},function(a,d,e,g,m){var j={},j=e;j.folder=b+g;if(m)for(var G in e)var v=G;c.post(d,j,function(b){for(var j in b)!1!==a.data.action(a,d,e,g,m)&&(confirm("Do you want to replace the file "+
b[j]+"?")||document.getElementById(c(a.target).attr("id")+"Uploader").cancelFileUpload(j,!0,!0));m?document.getElementById(c(a.target).attr("id")+"Uploader").startFileUpload(v,!0):document.getElementById(c(a.target).attr("id")+"Uploader").startFileUpload(null,!0)},"json")});c(this).bind("uploadifyCancel",{action:settings.onCancel},function(a,b,d,e,g){!1!==a.data.action(a,b,d,e,g)&&c("#"+c(this).attr("id")+b).fadeOut(!0==g?0:250,function(){c(this).remove()})});"function"==typeof settings.onClearQueue&&
c(this).bind("uploadifyClearQueue",settings.onClearQueue);var j=[];c(this).bind("uploadifyError",{action:settings.onError},function(a,b,d,e){!1!==a.data.action(a,b,d,e)&&(j.push([b,d,e]),c("#"+c(this).attr("id")+b+" .percentage").text(" - "+e.type+" Error"),c("#"+c(this).attr("id")+b).addClass("uploadifyError"))});c(this).bind("uploadifyProgress",{action:settings.onProgress,toDisplay:settings.displayData},function(a,b,d,e){!1!==a.data.action(a,b,d,e)&&(c("#"+c(this).attr("id")+b+"ProgressBar").css("width",
e.percentage+"%"),"percentage"==a.data.toDisplay&&(displayData=" - "+e.percentage+"%"),"speed"==a.data.toDisplay&&(displayData=" - "+e.speed+"KB/s"),null==a.data.toDisplay&&(displayData=" "),c("#"+c(this).attr("id")+b+" .percentage").text(displayData))});c(this).bind("uploadifyComplete",{action:settings.onComplete},function(a,b,e,d,g){!1!==a.data.action(a,b,e,unescape(d),g)&&(c("#"+c(this).attr("id")+b+" .percentage").text(" - Completed"),c("#"+c(this).attr("id")+b).fadeOut(250,function(){c(this).remove()}))});
"function"==typeof settings.onAllComplete&&c(this).bind("uploadifyAllComplete",{action:settings.onAllComplete},function(a,b){!1!==a.data.action(a,b)&&(j=[])})})},uploadifySettings:function(d,b,a){var e=!1;c(this).each(function(){if("scriptData"==d&&null!=b){var g=a?b:c.extend(settings.scriptData,b),j="",m;for(m in g)j+="&"+m+"="+escape(g[m]);b=j.substr(1)}e=document.getElementById(c(this).attr("id")+"Uploader").updateSettings(d,b)});if(null==b){if("scriptData"==d){for(var g=unescape(e).split("&"),
j={},t=0;t<g.length;t++){var u=g[t].split("=");j[u[0]]=u[1]}e=j}return e}},uploadifyUpload:function(d){c(this).each(function(){document.getElementById(c(this).attr("id")+"Uploader").startFileUpload(d,!1)})},uploadifyCancel:function(d){c(this).each(function(){document.getElementById(c(this).attr("id")+"Uploader").cancelFileUpload(d,!0,!1)})},uploadifyClearQueue:function(){c(this).each(function(){document.getElementById(c(this).attr("id")+"Uploader").clearFileUploadQueue(!1)})}})}(jQuery);
var swfobject=function(){function c(){if(!z){try{var k=h.getElementsByTagName("body")[0].appendChild(h.createElement("span"));k.parentNode.removeChild(k)}catch(a){return}z=!0;for(var k=H.length,b=0;b<k;b++)H[b]()}}function d(k){z?k():H[H.length]=k}function b(k){if(typeof r.addEventListener!=l)r.addEventListener("load",k,!1);else if(typeof h.addEventListener!=l)h.addEventListener("load",k,!1);else if(typeof r.attachEvent!=l){var a=r;a.attachEvent("onload",k);A[A.length]=[a,"onload",k]}else if("function"==
typeof r.onload){var b=r.onload;r.onload=function(){b();k()}}else r.onload=k}function a(){var k=x.length;if(0<k)for(var a=0;a<k;a++){var b=x[a].id,c=x[a].callbackFn,d={success:!1,id:b};if(0<f.pv[0]){var h=m(b);if(h)if(F(x[a].swfVersion)&&!(f.wk&&312>f.wk))v(b,!0),c&&(d.success=!0,d.ref=e(b),c(d));else if(x[a].expressInstall&&g()){d={};d.data=x[a].expressInstall;d.width=h.getAttribute("width")||"0";d.height=h.getAttribute("height")||"0";h.getAttribute("class")&&(d.styleclass=h.getAttribute("class"));
h.getAttribute("align")&&(d.align=h.getAttribute("align"));for(var S={},h=h.getElementsByTagName("param"),q=h.length,n=0;n<q;n++)"movie"!=h[n].getAttribute("name").toLowerCase()&&(S[h[n].getAttribute("name")]=h[n].getAttribute("value"));j(d,S,b,c)}else t(h),c&&c(d)}else if(v(b,!0),c){if((b=e(b))&&typeof b.SetVariable!=l)d.success=!0,d.ref=b;c(d)}}}function e(k){var a=null;if((k=m(k))&&"OBJECT"==k.nodeName)typeof k.SetVariable!=l?a=k:(k=k.getElementsByTagName(w)[0])&&(a=k);return a}function g(){return!I&&
F("6.0.65")&&(f.win||f.mac)&&!(f.wk&&312>f.wk)}function j(a,b,c,d){I=!0;N=d||null;T={success:!1,id:c};var e=m(c);if(e){"OBJECT"==e.nodeName?(D=u(e),J=null):(D=e,J=c);a.id=U;if(typeof a.width==l||!/%$/.test(a.width)&&310>parseInt(a.width,10))a.width="310";if(typeof a.height==l||!/%$/.test(a.height)&&137>parseInt(a.height,10))a.height="137";h.title=h.title.slice(0,47)+" - Flash Player Installation";d=f.ie&&f.win?"ActiveX":"PlugIn";d="MMredirectURL="+r.location.toString().replace(/&/g,"%26")+"&MMplayerType="+
d+"&MMdoctitle="+h.title;b.flashvars=typeof b.flashvars!=l?b.flashvars+("&"+d):d;f.ie&&(f.win&&4!=e.readyState)&&(d=h.createElement("div"),c+="SWFObjectNew",d.setAttribute("id",c),e.parentNode.insertBefore(d,e),e.style.display="none",function(){4==e.readyState?e.parentNode.removeChild(e):setTimeout(arguments.callee,10)}());M(a,b,c)}}function t(a){if(f.ie&&f.win&&4!=a.readyState){var b=h.createElement("div");a.parentNode.insertBefore(b,a);b.parentNode.replaceChild(u(a),b);a.style.display="none";(function(){4==
a.readyState?a.parentNode.removeChild(a):setTimeout(arguments.callee,10)})()}else a.parentNode.replaceChild(u(a),a)}function u(a){var b=h.createElement("div");if(f.win&&f.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName(w)[0])if(a=a.childNodes)for(var c=a.length,d=0;d<c;d++)!(1==a[d].nodeType&&"PARAM"==a[d].nodeName)&&8!=a[d].nodeType&&b.appendChild(a[d].cloneNode(!0));return b}function M(a,b,c){var d,e=m(c);if(f.wk&&312>f.wk)return d;if(e)if(typeof a.id==l&&(a.id=c),f.ie&&f.win){var g=
"",j;for(j in a)a[j]!=Object.prototype[j]&&("data"==j.toLowerCase()?b.movie=a[j]:"styleclass"==j.toLowerCase()?g+=' class="'+a[j]+'"':"classid"!=j.toLowerCase()&&(g+=" "+j+'="'+a[j]+'"'));j="";for(var q in b)b[q]!=Object.prototype[q]&&(j+='<param name="'+q+'" value="'+b[q]+'" />');e.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+g+">"+j+"</object>";K[K.length]=a.id;d=m(a.id)}else{q=h.createElement(w);q.setAttribute("type",L);for(var n in a)a[n]!=Object.prototype[n]&&("styleclass"==
n.toLowerCase()?q.setAttribute("class",a[n]):"classid"!=n.toLowerCase()&&q.setAttribute(n,a[n]));for(g in b)b[g]!=Object.prototype[g]&&"movie"!=g.toLowerCase()&&(a=q,j=g,n=b[g],c=h.createElement("param"),c.setAttribute("name",j),c.setAttribute("value",n),a.appendChild(c));e.parentNode.replaceChild(q,e);d=q}return d}function Q(a){var b=m(a);b&&"OBJECT"==b.nodeName&&(f.ie&&f.win?(b.style.display="none",function(){if(4==b.readyState){var c=m(a);if(c){for(var d in c)"function"==typeof c[d]&&(c[d]=null);
c.parentNode.removeChild(c)}}else setTimeout(arguments.callee,10)}()):b.parentNode.removeChild(b))}function m(a){var b=null;try{b=h.getElementById(a)}catch(c){}return b}function F(a){var b=f.pv;a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&b[1]==a[1]&&b[2]>=a[2]?!0:!1}function G(a,b,c,d){if(!f.ie||!f.mac){var e=h.getElementsByTagName("head")[0];if(e){c=c&&"string"==typeof c?c:"screen";d&&(O=s=null);if(!s||
O!=c)d=h.createElement("style"),d.setAttribute("type","text/css"),d.setAttribute("media",c),s=e.appendChild(d),f.ie&&(f.win&&typeof h.styleSheets!=l&&0<h.styleSheets.length)&&(s=h.styleSheets[h.styleSheets.length-1]),O=c;f.ie&&f.win?s&&typeof s.addRule==w&&s.addRule(a,b):s&&typeof h.createTextNode!=l&&s.appendChild(h.createTextNode(a+" {"+b+"}"))}}}function v(a,b){if(V){var c=b?"visible":"hidden";z&&m(a)?m(a).style.visibility=c:G("#"+a,"visibility:"+c)}}function R(a){return null!=/[\\\"<>\.;]/.exec(a)&&
typeof encodeURIComponent!=l?encodeURIComponent(a):a}var l="undefined",w="object",L="application/x-shockwave-flash",U="SWFObjectExprInst",r=window,h=document,y=navigator,W=!1,H=[function(){if(W){var b=h.getElementsByTagName("body")[0],c=h.createElement(w);c.setAttribute("type",L);var d=b.appendChild(c);if(d){var e=0;(function(){if(typeof d.GetVariable!=l){var g=d.GetVariable("$version");g&&(g=g.split(" ")[1].split(","),f.pv=[parseInt(g[0],10),parseInt(g[1],10),parseInt(g[2],10)])}else if(10>e){e++;
setTimeout(arguments.callee,10);return}b.removeChild(c);d=null;a()})()}else a()}else a()}],x=[],K=[],A=[],D,J,N,T,z=!1,I=!1,s,O,V=!0,f,Y=typeof h.getElementById!=l&&typeof h.getElementsByTagName!=l&&typeof h.createElement!=l,B=y.userAgent.toLowerCase(),C=y.platform.toLowerCase(),Z=C?/win/.test(C):/win/.test(B),C=C?/mac/.test(C):/mac/.test(B),B=/webkit/.test(B)?parseFloat(B.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,P=!+"\v1",E=[0,0,0],p=null;if(typeof y.plugins!=l&&typeof y.plugins["Shockwave Flash"]==
w){if((p=y.plugins["Shockwave Flash"].description)&&!(typeof y.mimeTypes!=l&&y.mimeTypes[L]&&!y.mimeTypes[L].enabledPlugin))W=!0,P=!1,p=p.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),E[0]=parseInt(p.replace(/^(.*)\..*$/,"$1"),10),E[1]=parseInt(p.replace(/^.*\.(.*)\s.*$/,"$1"),10),E[2]=/[a-zA-Z]/.test(p)?parseInt(p.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if(typeof r.ActiveXObject!=l)try{var X=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(X&&(p=X.GetVariable("$version")))P=!0,p=p.split(" ")[1].split(","),
E=[parseInt(p[0],10),parseInt(p[1],10),parseInt(p[2],10)]}catch(aa){}f={w3:Y,pv:E,wk:B,ie:P,win:Z,mac:C};f.w3&&((typeof h.readyState!=l&&"complete"==h.readyState||typeof h.readyState==l&&(h.getElementsByTagName("body")[0]||h.body))&&c(),z||(typeof h.addEventListener!=l&&h.addEventListener("DOMContentLoaded",c,!1),f.ie&&f.win&&(h.attachEvent("onreadystatechange",function(){"complete"==h.readyState&&(h.detachEvent("onreadystatechange",arguments.callee),c())}),r==top&&function(){if(!z){try{h.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,
0);return}c()}}()),f.wk&&function(){z||(/loaded|complete/.test(h.readyState)?c():setTimeout(arguments.callee,0))}(),b(c)));f.ie&&f.win&&window.attachEvent("onunload",function(){for(var a=A.length,b=0;b<a;b++)A[b][0].detachEvent(A[b][1],A[b][2]);a=K.length;for(b=0;b<a;b++)Q(K[b]);for(var c in f)f[c]=null;f=null;for(var d in swfobject)swfobject[d]=null;swfobject=null});return{registerObject:function(a,b,c,d){if(f.w3&&a&&b){var e={};e.id=a;e.swfVersion=b;e.expressInstall=c;e.callbackFn=d;x[x.length]=
e;v(a,!1)}else d&&d({success:!1,id:a})},getObjectById:function(a){if(f.w3)return e(a)},embedSWF:function(a,b,c,e,h,m,u,q,n,p){var r={success:!1,id:b};f.w3&&!(f.wk&&312>f.wk)&&a&&b&&c&&e&&h?(v(b,!1),d(function(){c+="";e+="";var d={};if(n&&typeof n===w)for(var f in n)d[f]=n[f];d.data=a;d.width=c;d.height=e;f={};if(q&&typeof q===w)for(var s in q)f[s]=q[s];if(u&&typeof u===w)for(var t in u)f.flashvars=typeof f.flashvars!=l?f.flashvars+("&"+t+"="+u[t]):t+"="+u[t];if(F(h))s=M(d,f,b),d.id==b&&v(b,!0),r.success=
!0,r.ref=s;else{if(m&&g()){d.data=m;j(d,f,b,p);return}v(b,!0)}p&&p(r)})):p&&p(r)},switchOffAutoHideShow:function(){V=!1},ua:f,getFlashPlayerVersion:function(){return{major:f.pv[0],minor:f.pv[1],release:f.pv[2]}},hasFlashPlayerVersion:F,createSWF:function(a,b,c){if(f.w3)return M(a,b,c)},showExpressInstall:function(a,b,c,d){f.w3&&g()&&j(a,b,c,d)},removeSWF:function(a){f.w3&&Q(a)},createCSS:function(a,b,c,d){f.w3&&G(a,b,c,d)},addDomLoadEvent:d,addLoadEvent:b,getQueryParamValue:function(a){var b=h.location.search||
h.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(null==a)return R(b);for(var b=b.split("&"),c=0;c<b.length;c++)if(b[c].substring(0,b[c].indexOf("="))==a)return R(b[c].substring(b[c].indexOf("=")+1))}return""},expressInstallCallback:function(){if(I){var a=m(U);a&&D&&(a.parentNode.replaceChild(D,a),J&&(v(J,!0),f.ie&&f.win&&(D.style.display="block")),N&&N(T));I=!1}}}}();
(function(c){var d;c.rails=d={linkClickSelector:"a[data-confirm], a[data-method], a[data-remote]",formSubmitSelector:"form",formInputClickSelector:"form input[type=submit], form input[type=image], form button[type=submit], form button:not([type])",disableSelector:"input[data-disable-with], button[data-disable-with], textarea[data-disable-with]",enableSelector:"input[data-disable-with]:disabled, button[data-disable-with]:disabled, textarea[data-disable-with]:disabled",requiredInputSelector:"input[name][required],textarea[name][required]",
fileInputSelector:"input:file",CSRFProtection:function(b){var a=c('meta[name="csrf-token"]').attr("content");a&&b.setRequestHeader("X-CSRF-Token",a)},fire:function(b,a,d){a=c.Event(a);b.trigger(a,d);return!1!==a.result},confirm:function(b){return confirm(b)},ajax:function(b){return c.ajax(b)},handleRemote:function(b){var a,e,g,j=b.data("type")||c.ajaxSettings&&c.ajaxSettings.dataType;if(d.fire(b,"ajax:before")){if(b.is("form")){a=b.attr("method");e=b.attr("action");g=b.serializeArray();var t=b.data("ujs:submit-button");
t&&(g.push(t),b.data("ujs:submit-button",null))}else a=b.data("method"),e=b.attr("href"),g=null;d.ajax({url:e,type:a||"GET",data:g,dataType:j,beforeSend:function(a,c){void 0===c.dataType&&a.setRequestHeader("accept","*/*;q=0.5, "+c.accepts.script);return d.fire(b,"ajax:beforeSend",[a,c])},success:function(a,c,d){b.trigger("ajax:success",[a,c,d])},complete:function(a,c){b.trigger("ajax:complete",[a,c])},error:function(a,c,d){b.trigger("ajax:error",[a,c,d])}})}},handleMethod:function(b){var a=b.attr("href"),
d=b.data("method");b=c("meta[name=csrf-token]").attr("content");var g=c("meta[name=csrf-param]").attr("content"),a=c('<form method="post" action="'+a+'"></form>'),d='<input name="_method" value="'+d+'" type="hidden" />';void 0!==g&&void 0!==b&&(d+='<input name="'+g+'" value="'+b+'" type="hidden" />');a.hide().append(d).appendTo("body");a.submit()},disableFormElements:function(b){b.find(d.disableSelector).each(function(){var a=c(this),b=a.is("button")?"html":"val";a.data("ujs:enable-with",a[b]());
a[b](a.data("disable-with"));a.attr("disabled","disabled")})},enableFormElements:function(b){b.find(d.enableSelector).each(function(){var a=c(this),b=a.is("button")?"html":"val";if(a.data("ujs:enable-with"))a[b](a.data("ujs:enable-with"));a.removeAttr("disabled")})},allowAction:function(b){var a=b.data("confirm"),c=!1,g;if(!a)return!0;d.fire(b,"confirm")&&(c=d.confirm(a),g=d.fire(b,"confirm:complete",[c]));return c&&g},blankInputs:function(b,a,d){var g=c(),j;b.find(a||"input,textarea").each(function(){j=
c(this);if(d?j.val():!j.val())g=g.add(j)});return g.length?g:!1},nonBlankInputs:function(b,a){return d.blankInputs(b,a,!0)},stopEverything:function(b){b.stopImmediatePropagation();return!1},callFormSubmitBindings:function(b){b=b.data("events");var a=!0;void 0!==b&&void 0!==b.submit&&c.each(b.submit,function(b,c){if("function"===typeof c.handler)return a=c.handler(c.data)});return a}};"ajaxPrefilter"in c?c.ajaxPrefilter(function(b,a,c){d.CSRFProtection(c)}):c(document).ajaxSend(function(b,a){d.CSRFProtection(a)});
c(d.linkClickSelector).live("click.rails",function(b){var a=c(this);if(!d.allowAction(a))return d.stopEverything(b);if(void 0!==a.data("remote"))return d.handleRemote(a),!1;if(a.data("method"))return d.handleMethod(a),!1});c(d.formSubmitSelector).live("submit.rails",function(b){var a=c(this),e=void 0!==a.data("remote"),g=d.blankInputs(a,d.requiredInputSelector),j=d.nonBlankInputs(a,d.fileInputSelector);if(!d.allowAction(a))return d.stopEverything(b);if(g&&d.fire(a,"ajax:aborted:required",[g]))return!e;
if(e){if(j)return d.fire(a,"ajax:aborted:file",[j]);if(!c.support.submitBubbles&&!1===d.callFormSubmitBindings(a))return d.stopEverything(b);d.handleRemote(a);return!1}setTimeout(function(){d.disableFormElements(a)},13)});c(d.formInputClickSelector).live("click.rails",function(b){var a=c(this);if(!d.allowAction(a))return d.stopEverything(b);b=(b=a.attr("name"))?{name:b,value:a.val()}:null;a.closest("form").data("ujs:submit-button",b)});c(d.formSubmitSelector).live("ajax:beforeSend.rails",function(b){this==
b.target&&d.disableFormElements(c(this))});c(d.formSubmitSelector).live("ajax:complete.rails",function(b){this==b.target&&d.enableFormElements(c(this))})})(jQuery);
$(document).ready(function(){var c=window.script_data,d=$("meta[name=csrf-token]").attr("content"),b=$("meta[name=csrf-param]").attr("content");c[b]=encodeURI(encodeURIComponent(d.toString()));$("#fileInput").uploadify({script:window.upload_url,uploader:"/assets/external/uploadify/uploadify.swf",cancelImg:"/assets/external/uploadify/cancel.png",auto:!1,folder:"",scriptAcess:"always",multi:"true",fileDesc:"Please select the photos to upload",fileExt:"*.jpg;*.jpeg;*.jpe;*.gif;*.png",buttonText:"Choose photos",
scriptData:c,onAllComplete:function(){window.location.reload()},onError:function(a,b,c,d){alert(d.type+" Error: "+d.info)}});pe.init_page_framework()});
