pe.validation={};pe.validatables=[];pe.validation.autocomplete_open=!1;pe.validate_on_key_up=function(a,b){a.keyup(function(){b(a)});a.val()&&b(a);return a};pe.validate_on_blur=function(a,b,c){a.blur(function(){b(a)});!c&&a.val()&&b(a);return a};pe.validate_on_change=function(a,b,c){a.change(function(){b(a)});!c&&a.val()&&b(a);return a};
pe.validate_before_submit=function(a){a.submit(function(){pe.validation.clear_error_messages(a);a.find("input").each(function(a,b){var c=$(b);c.data("text_entered",!0);c.keyup();c.blur()});a.find("select").each(function(a,b){var c=$(b);c.data("text_entered",!0);c.change()});a.find("textarea").each(function(a,b){var c=$(b);c.data("text_entered",!0);c.keyup();c.blur()});var b=!0;$.each(pe.validatables,function(a,c){b=c.validate_on_submit()&&b});if(0<a.find(".inline-errors").length||!b){var c=a.find(".inline-errors:first").parent(),
d=c.find("input:first");0<d.length?d.is(":hidden")?(d.show(),d.focus(),d.hide()):d.focus():(d=c.find("textarea"),c=c.find('select option:selected[value=""]').parent(),d&&d.focus(),c&&c.focus());return!1}})};
pe.validate_user_exists=function(a,b){form=$(a.parents("form")[0]);form.submit(function(){pe.validation.clear_error_messages(form);$.post("/api/users/check_user_exists",{login:a.val(),password:b.val()},function(c){pe.validation.show_message(a,c.username);pe.validation.show_message(b,c.password);_.isEmpty(c)&&(form.unbind("submit"),form.submit())});return!1})};pe.validation.clear_error_messages=function(a){pe.validation.find_error_messages(a).remove()};pe.validation.find_error_messages=function(a){return a.find(".inline-errors")};
pe.validation.show_message=function(a,b){a.parent().find(".inline-errors,img").remove();b?a.after('<span class="inline-errors">'+b+"</span>"):a.after('<img src="/assets/users/check.png" />')};pe.validation.is_more_than_5_words=function(a){return!!a.match(/(\w+\s+){5}\w+/)};pe.validation.is_single_non_character=function(a){return!a?!1:!a.match(/[a-zA-Z]+/)};pe.validation.is_valid_email_address=function(a){return!!a.match(/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9])([A-Za-z0-9_\-\.])*\.([A-Za-z]{2,4})$/)};
pe.validation.is_valid_email_list=function(a){if(!a)return"Please enter at least one email.";a=a.split(",");var b="";$.each(a,function(a,d){d=$.trim(d);if(!pe.validation.is_valid_email_address(d))return b=d+" is not a valid email address.",!1});return b};pe.validation.contains_illegal_characters=function(a){return!!a.match(/[\!@#\$%\^&\*\(\)\{\}\[\]\/\=\"<>\~\;_\+\?\\]/)};
pe.validation.ensure_email_not_blank_and_is_valid=function(a){var b=a.val();if("string"===typeof b&&(b||a.data("text_entered"))){a.data("text_entered",!0);var c=a.attr("data_label")||"Email";if(0===b.length)pe.validation.show_message(a,c+" cannot be blank.");else{var d=!0,e=/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9])([A-Za-z0-9_\-\.])*\.([A-Za-z]{2,4})$/;$.each(b.split(","),function(a,b){d=d&&0<b.length&&e.test($.trim(b))});d?(pe.validation.show_message(a,""),a.data("text_entered",!0)):pe.validation.show_message(a,
"Please enter a valid email.")}}};
pe.validation.validate_name=function(a){var b=a.val();if("string"===typeof b&&(b||a.data("text_entered")))a.data("text_entered",!0),pe.validation.is_single_non_character(b)?pe.validation.show_message(a,"Please enter a valid "+pe.validation.get_name_error_message(a)+"."):pe.validation.contains_illegal_characters(b)?pe.validation.show_message(a,"Please enter a valid name."):50<b.length?pe.validation.show_message(a,"Please shorten your name."):pe.validation.is_more_than_5_words(b)?pe.validation.show_message(a,
"Please enter fewer than 5 words."):0<b.length?pe.validation.show_message(a,""):0<a[0].id.indexOf("first_name")?pe.validation.show_message(a,"Please enter your first name."):0<a[0].id.indexOf("last_name")?pe.validation.show_message(a,"Please enter your last name."):pe.validation.show_message(a,"Please enter your name.")};
pe.validation.ensure_not_blank=function(a){var b=a.val();if("string"===typeof b&&(b||a.data("text_entered")))a.data("text_entered",!0),0===a.val().length?(b=a.attr("data_label")||"Field",pe.validation.show_message(a,b+" cannot be blank.")):(pe.validation.show_message(a,""),a.data("text_entered",!0))};
pe.validation.validate_credit_card_number=function(a){var b=a.val();if(!(16>b.length)||a.data("text_entered"))a.data("text_entered",!0),"string"===typeof b&&pe.is_valid_credit_card_number(b)?pe.validation.show_message(a,""):pe.validation.show_message(a,"Please enter a valid card number.")};pe.validation.validate_email=function(a){var b=a.val();if(b||a.data("text_entered"))a.data("text_entered",!0),$.getJSON("/api/users/check_email",{email:b},function(b){pe.validation.show_message(a,b.message)})};
pe.validation.validate_edited_email=function(a,b){var c=b.val();if(c||b.data("text_entered"))b.data("text_entered",!0),$.getJSON("/api/users/"+a+"/check_edited_email",{email:c},function(a){pe.validation.show_message(b,a.message)})};
pe.validation.validate_email_format=function(a){var b=a.val(),c=/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9])([A-Za-z0-9_\-\.])*\.([A-Za-z]{2,4})$/;0<b.length&&!c.test(b)?pe.validation.show_message(a,"Please enter a valid email."):0<b.length&&c.test(b)&&(pe.validation.show_message(a,""),a.data("text_entered",!0))};pe.validation.validate_email_list=function(a){var b=a.val();"string"===typeof b&&(b=pe.validation.is_valid_email_list(b))&&pe.validation.show_message(a,b)};
pe.validation.validate_password=function(a){var b=a.val();b?0<b.length&&-1<b.indexOf(" ")?pe.validation.show_message(a,"No spaces allowed for password."):6>b.length?pe.validation.show_message(a,"Please enter a longer password."):(pe.validation.show_message(a,""),a.data("text_entered",!0)):a.data("text_entered")&&pe.validation.show_message(a,"Please enter a password.")};
pe.validation.validate_security_code=function(a){var b=a.val();if(!(3>b.length)||a.data("text_entered"))a.data("text_entered",!0),b.match(/^\d{3}$/)||pe.validation.show_message(a,"Please enter a valid security code.")};
pe.validation.validate_user_name=function(a){var b=a.val();if(!a.attr("disabled")&&(b||a.data("text_entered")))a.data("text_entered",!0),50<b.length?pe.validation.show_message(a,"Please shorten your name."):0===b.length?pe.validation.show_message(a,"Please enter a user name."):$.getJSON("/api/users/check_username",{username:b},function(b){pe.validation.show_message(a,b.message)})};
pe.validation.validate_change_of_username=function(a,b){var c=b.val();if(c||b.data("text_entered"))b.data("text_entered",!0),50<c.length?pe.validation.show_message(b,"Please shorten your name."):0===c.length?pe.validation.show_message(b,"Please enter a user name."):$.getJSON("/api/users/"+a+"/check_edited_username",{username:c},function(a){pe.validation.show_message(b,a.message)})};
pe.validation.validate_zip_code=function(a){var b=a.val();if(!(5>b.length)||a.data("text_entered"))a.data("text_entered",!0),5>b.length?pe.validation.show_message(a,"Please enter a valid zip code."):"string"===typeof b&&pe.is_valid_zip_code(b)?pe.validation.show_message(a,""):pe.validation.show_message(a,"Please enter a valid zip code.")};
pe.validation.terms_accepted=function(a){if(a.attr("checked")||a.data("text_entered"))a.data("text_entered",!0),a.attr("checked")?pe.validation.show_message(a.parent(),""):pe.validation.show_message(a.parent(),"Please accept the terms of use")};pe.validation.get_name_error_message=function(a){return 0<a[0].id.indexOf("first_name")?"first name":0<a[0].id.indexOf("last_name")?"last name":"name"};
pe.SubscribePage=function(a,b){pe.init_widget(this,a);this.subscribe_request_sent=!1;this.email_input=this.container.find(".YourEmail");this.email_input.keyup(this.callback(this.email_input_key_handler));pe.validate_on_blur(this.email_input,pe.validation.ensure_email_not_blank_and_is_valid);this.container.find(".InfieldLabel label").inFieldLabels({fadeDuration:0});this.subscription_list_input=this.container.find(".SubscriptionList");b?this.subscription_list_input.removeClass("hidden"):this.subscription_list_input.multiselect({header:!1,
selectedList:1,click:function(){if(0===$(this).multiselect("widget").find("input:checked").length)return!1}});this.subscribe_button=this.container.find(".Subscribe");this.subscribe_button.click(this.callback(this.subscribe_button_clicked));this.facebook_link_button=this.container.find(".FacebookSubscribeLink");b?this.facebook_link_button.click(this.callback(this.mobile_facebook_link_clicked)):(this.facebook_link_button.click(this.callback(function(){pe.subscription_module=this})),pe.connect_subscribe_using_facebook(this.facebook_link_button))};
pe.SubscribePage.prototype.as_enum=function(){return{list_ids:this.subscription_list_input.val()}};pe.SubscribePage.prototype.email_input_key_handler=function(a){13===a.keyCode&&this.subscribe_button.click()};pe.SubscribePage.prototype.redirect_url=function(){return window.location.protocol+"//"+window.location.host+"/subscribe/confirmed/?list_ids="+this.subscription_list_input.val()};
pe.SubscribePage.prototype.mobile_facebook_link_clicked=function(){if(null===this.subscription_list_input.val())return!1;var a={provider:"facebook",authFlow:"redirect",redirectMethod:"post",redirectURL:this.redirect_url(),context:this.as_enum()};this.facebook_link_button.data("logged-in")&&gigya&&gigya.socialize?gigya.socialize.login(a):gigya&&gigya.socialize&&gigya.socialize.addConnection(a)};
pe.SubscribePage.prototype.subscribe_button_clicked=function(){if(this.validate_on_submit())pe.add_subscriptions(this,{email:this.email_input.val()});else return this.email_input.focus(),!1};pe.SubscribePage.prototype.subscription_confirmation=function(a){this.subscribe_request_sent=!1;this.container.addClass("subscription_confirmation");this.container.html(a);pe.subscription_module=null};pe.SubscribePage.prototype.request_in_process=function(){this.subscribe_request_sent=!0;this.container.html('<div class="lspinner" style="text-align: center;"><h2>Please Wait</h2><img src="/assets/content_bg/spinner.gif"/></div>')};
pe.SubscribePage.prototype.validate_on_submit=function(){pe.validation.clear_error_messages(this.container);this.email_input.data("text_entered",!0).blur();return 0===this.container.find(".inline-errors").length};
pe.validation.ensure_email_not_blank_and_is_valid=function(a){var b=a.val();if("string"===typeof b&&(b||a.data("text_entered")))if(a.data("text_entered",!0),0===b.length)pe.validation.show_message(a,"Please enter your email address");else{var c=!0,d=/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9])([A-Za-z0-9_\-\.])*\.([A-Za-z]{2,4})$/;$.each(b.split(","),function(a,b){c=c&&0<b.length&&d.test($.trim(b))});c?(pe.validation.show_message(a,""),a.data("text_entered",!0)):pe.validation.show_message(a,"Please enter a valid email address")}};
$(document).ready(function(){var a=window.is_mobile_device;a?new pe.SubscribePage($(".SubscribeFormContainer"),a):pe.init_page_framework(function(){new pe.SubscribePage($(".SubscribeFormContainer"),a)})});
